### ISSUE TITLE
AssertionError while processing _fix_squished_place_mismatch

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#251]
We find raw -> filtered

```
2016-10-23 03:38:13,117:DEBUG:139657654888256:For raw trip 580bf83888f66356dad2d40a, found filtered trip 580c30a488f6635b29ea55be
```

This is a trip, not untracked

```
2016-10-23 03:38:13,121:DEBUG:139657654888256:_is_squished_untracked: 580bb32e88f663518b966b23 is a segmentation/raw_trip, not segmentation/raw_untracked, returning False
```

There's a minor difference between the two points (18 meters apart).

> > ecc.calDistance([-122.2588476074135, 37.87331113595317], [-122.2588238866276, 37.87347466688405])
> > 18.30262099474195

```
2016-10-23 03:38:13,124:DEBUG:139657654888256:squishing mismatch: resetting trip start_loc [-122.2588476074135, 37.87331113595317] to cleaned_start_place.location [-122.2588238866276, 37.87347466688405]
```

Note that we attempt to fix the mismatch if the coordinates are not identical

```
    if (cleaned_start_place_data.location.coordinates !=
                       raw_start_place.data.location.coordinates):
        _fix_squished_place_mismatch(cleaned_trip.user_id, cleaned_trip.get_id(),
                                     ts, cleaned_trip_data, cleaned_start_place_data)

```

We look for a location at ts = 1477155094.000022. Why? Do we find it?

```
2016-10-23 03:38:13,175:DEBUG:139657654888256:get_entry_at_ts query = {'metadata.key': 'background/filtered_location', 'user_id': UUID('8f1a6737-e8ee-4769-a1a4-da1948d886b6'), 'data.ts': 1477155094.000022}
```

Unsure, but we insert an entry at 1477154950.1033349

```
2016-10-23 03:38:13
178:DEBUG:139657654888256:Inserting entry Entry({'data': Recreatedlocation(
{u'loc': {u'type': u'Point' u'coordinates': [-122.2588238866276 37.87347466688405]}
 u'fmt_time': '2016-10-22T09:49:10.103335-07:00'
 u'ts': 1477154950.1033349
 'mode': 7
 'section': ObjectId('580c30a388f6635b29ea54ff')
 u'sensed_speed': 3.579999923706055
 'distance': 0})
 '_id': ObjectId('580c30a588f6635b29ea55dd')
 'key': 'analysis/recreated_location'})}) into timeseries
```

Then, we query for the entries for this section (1477154950.103335 -> 1477160591.999968). We find 1906 entries, which are no de-duped. and then the speeds mismatch.

```
2016-10-23 03:38:13,194:DEBUG:139657654888256:curr_query = {'$or': [{'metadata.key': 'analysis/recreated_location'}], 'user_id': UUID('8f1a6737-e8ee-4769-a1a4-da1948d886b6'), 'data.ts': {'$lte': 1477160591.999968, '$gte': 1477154950.103335}}, sort_key = data.ts
2016-10-23 03:38:13,194:DEBUG:139657654888256:orig_ts_db_keys = [], analysis_ts_db_keys = ['analysis/recreated_location']
2016-10-23 03:38:13,194:DEBUG:139657654888256:finished querying values for []
2016-10-23 03:38:13,194:DEBUG:139657654888256:finished querying values for ['analysis/recreated_location']
2016-10-23 03:38:14,055:DEBUG:139657654888256:Found 1906 results
2016-10-23 03:38:14,061:DEBUG:139657654888256:After de-duping, converted 1906 points to 1906 
2016-10-23 03:38:14,062:DEBUG:139657654888256:Returning entry with length 1906 result
2016-10-23 03:38:14,589:ERROR:139657654888256:[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] != [0.0, 0.6100873664913984, 0.05965627862873103, 0.059656275796728137, 0.05965627291921605, 0.05965627008539246, 0.059656267209699104, 0.05965626437769427, 0.059656261500180226, 0.05965625864542004]
2016-10-23 03:38:14,590:ERROR:139657654888256:Cleaning and resampling failed for user 8f1a6737-e8ee-4769-a1a4-da1948d886b6
Traceback (most recent call last):
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 72, in clean_and_resample
    last_raw_place = save_cleaned_segments_for_ts(user_id, time_query.startTs, time_query.endTs)
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 90, in save_cleaned_segments_for_ts
    return save_cleaned_segments_for_timeline(user_id, tl)
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 116, in save_cleaned_segments_for_timeline
    (last_cleaned_place, filtered_tl) = create_and_link_timeline(tl, user_id, trip_map)
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 878, in create_and_link_timeline
    link_trip_start(ts, curr_cleaned_trip, curr_cleaned_start_place, raw_start_place)
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 932, in link_trip_start
    ts, cleaned_trip_data, cleaned_start_place_data)
  File "/mnt/e-mission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 1055, in _fix_squished_place_mismatch
    assert False
AssertionError
```

**Comment by PatGendre** [comment]
Hi @shankari, I don't if it is exactly the same issue but it looked like very similar.

The pipeline for @DO3B data broke at the cleaning and resampling stage several days ago, the error is the following :
`2019-07-09 07:47:36,605:DEBUG:140484490442496:Found 2 sections, need to remove the uncommon ones...
2019-07-09 07:47:36,606:DEBUG:140484490442496:section counts = [(ObjectId('5d242a694e276da46fe56218'), 168), (ObjectId('5d242a694e276da46fe562c2'), 164)]
2019-07-09 07:47:36,607:ERROR:140484490442496:Cleaning and resampling failed for user 2775ba42-1f3f-4b4c-b026-8ffe18e7c0e8
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 84, in clean_and_resample
    last_raw_place = save_cleaned_segments_for_ts(user_id, time_query.startTs, time_query.endTs)
  File "/var/emission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 110, in save_cleaned_segments_for_ts
    return save_cleaned_segments_for_timeline(user_id, tl)
  File "/var/emission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 136, in save_cleaned_segments_for_timeline
    (last_cleaned_place, filtered_tl) = create_and_link_timeline(tl, user_id, trip_map)
  File "/var/emission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 962, in create_and_link_timeline
    link_trip_start(ts, curr_cleaned_trip, curr_cleaned_start_place, raw_start_place)
  File "/var/emission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 1016, in link_trip_start
    ts, cleaned_trip_data, cleaned_start_place_data)
  File "/var/emission/e-mission-server/emission/analysis/intake/cleaning/clean_and_resample.py", line 1157, in _fix_squished_place_mismatch
    assert(min(section_counts) == 1)
AssertionError`

Looking at [line 1157](https://github.com/fabmob/e-mission-server-fabmob/blob/7b3571a2c0c6879d31bec6db178b221c7574ae0b/emission/analysis/intake/cleaning/clean_and_resample.py#L1157) , the comments just above say `This code should work even if this assert is removed but this is the expectation we have based on the use cases we have seen so far`.
So I commented out the line, and then the clean and resample stage passed, so @DO3B has again his data available in the analysis collection.

However, this is maybe not a long term solution, I suppose the assert line was there for a good reason?

**Comment by shankari** [comment]
@PatGendre there are a bunch of asserts in the pipeline which deal primarily with how I expect it to work. I added them so that if they failed, I could go back, investigate further, and either adjust my expectation or adjust the code. Unfortunately, I don't have the time to investigate right now and I don't think you understand the pipeline well enough to investigate.

So in this case, the best option is indeed to comment out the assert. Maybe when I have time in the future, we can re-enable the assert and I can investigate it if the problem recurs.

**Comment by PatGendre** [comment]
Thanks, I leave the comment for the moment as this solves the problem for Loic's data @DO3B

**Comment by PatGendre** [comment]
@shankari @DO3B Hi, there was another assert Error in the clean and resample stage of the intake pipeline for loic's data, in line [1204](https://github.com/e-mission/e-mission-server/blob/7afe46c256298d426d03c9732a4d487748357022/emission/analysis/intake/cleaning/clean_and_resample.py#L1204) and 1210 in clean_and_resample.py.
So I commented the lines and the clean and resample has been terminated. Then I removed the comment again the lines and also for line 1155, so that we can see in the next days if the error appears again or if it was transient...

**Comment by PatGendre** [comment]
@DO3B for your info the clean and resample pipeline stage produced no error last night, although I un-commented the assert, so the assert errors were due to particular data values (so could be investigated another time if this error re-appears).

**Comment by shankari** [comment]
@PatGendre in general, unless you are actively working on the pipeline, it should be safe to comment out any asserts that you encounter. They are really there to help pipeline developers notice when something doesn't match assumptions so that they can go and investigate further.

**Comment by PatGendre** [comment]
@shankari Ok, I leave the asserts but next time if comment out an assert, I will leave the comment.
