### ISSUE TITLE
what is mode speedometer?

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#362]
I had lastly some trip sections in purple with a mode called "speedometer", which is related to "IN VEHICLE" : what is the difference with "IN CAR"?

**Comment by shankari** [comment]
The `IN_VEHICLE` mode uses a speedometer for the display 
https://github.com/e-mission/e-mission-phone/blob/master/www/js/diary/services.js#L40

The difference between `IN_VEHICLE` and `CAR` the output stage. Basically, the phone motion activity distinguishes between `WALK`, `BIKE`, `RUN` and `IN_VEHICLE`. So all sections before the mode inference step (`segmentation/raw_section` and `analysis/cleaned_section`) never have `CAR`, `CAR`, `BUS` and `TRAIN` are all subsumed into `IN_VEHICLE`.

Then the mode inference step runs and separates them out using the OSM GIS integration.
So `analysis/inferred_sections` will have the separated-out modes.

Why are you not getting `inferred_sections`? Is the pipeline not running fully?
Or have you changed your configuration https://github.com/e-mission/e-mission-server/blob/master/conf/analysis/debug.conf.json.sample#L6 to returned cleaned instead of inferred sections?

**Comment by PatGendre** [comment]
Thanks, as we don't modifiy the conf.json file, I suspect we had a pipeline not running fully.
I will check the logs...

**Comment by PatGendre** [comment]
I have checked the logs : 
there is an exception raised in "inferring transit mode" (stage 4 of the pipeline)
`2019-04-10 02:00:28,110:DEBUG:140230579087104:bbox_string = 43.28257516532126,5.40178656532126,43.28527463467874,5.40448603467874
2019-04-10 02:00:43,349:ERROR:140230579087104:Error while inferring modes, timestamp is unchanged
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 24, in predict_mode
    mip.runPredictionPipeline(user_id, time_query)
  File "/var/emission/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 52, in runPredictionPipeline
    self.predictedProb = self.predictModesStep()
  File "/var/emission/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 71, in predictModesStep
    predictedProb.append(get_prediction(i, section_entry))
  File "/var/emission/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 110, in get_prediction
    return get_motorized_prediction(i, section_entry)
  File "/var/emission/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 137, in get_motorized_prediction
    predicted_transit_mode = _get_transit_prediction(i, section_entry)
  File "/var/emission/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 173, in _get_transit_prediction
    end_transit_stops = enetm.get_stops_near(section_entry.data.end_loc, end_radius)
  File "/var/emission/e-mission-server/emission/net/ext_service/transit_matching/match_stops.py", line 71, in get_stops_near
    stops = get_public_transit_stops(lat - bbox_delta, lon - bbox_delta, lat + bbox_delta, lon + bbox_delta)
  File "/var/emission/e-mission-server/emission/net/ext_service/transit_matching/match_stops.py", line 34, in get_public_transit_stops
    if response == None or response.json() == None:
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/anaconda3/envs/emission/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/envs/emission/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/envs/emission/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-04-10 02:00:43,352:DEBUG:140230579087104:About to save object PipelineState({'_id': ObjectId('5c9c1c9b4e276d709893e809'), 'user_id': UUID('a2ad418f-74ff-4d60-8ea0-9ccf9dd5de9b'), 'pipeline_stage': 4, 'curr_run_ts': None, 'last_processed_ts': 1554044919.0, 'last_ts_run': 1554076813.2707453})
2019-04-10 02:00:43,355:DEBUG:140230579087104:After saving state PipelineState({'_id': ObjectId('5c9c1c9b4e276d709893e809'), 'user_id': UUID('a2ad418f-74ff-4d60-8ea0-9ccf9dd5de9b'), 'pipeline_stage': 4, 'curr_run_ts': None, 'last_processed_ts': 1554044919.0, 'last_ts_run': 1554076813.2707453}), list is [{'_id': ObjectId('5c9c1c964e276d709893e791'), 'user_id': UUID('a2ad418f-74ff-4d60-8ea0-9ccf9dd5de9b'), 'pipeline_stage': 0, 'curr_run_ts': None, 'last_processed_ts': 1554727022.507, 'last_ts_run': 1554854402.789213}, {'_id': ObjectId('5c9c1c974e276d709893e794'), 'user_id': UUID('a2ad418f-74ff-4d60-8ea0-9ccf9dd5de9b'), 'pipeline_stage': 6, 'curr_run_ts': None, 'last_processed_ts': None, 'last_ts_run': 1554854402.8381193}, {'_id': ObjectId('5c9c1c974e276d709893e796'), 'user_id': UUID('a2ad418f-74ff-4d60-8ea0-9ccf9dd5de9b'), 'pipeline_stage': 1, 'curr_run_ts': None, 'last_processed_ts': 1554724583.75, 'last_ts_run': 1554854402.8423872}, {'_id': ObjectId('5c9c1c9a4e276d709893e7a1'), 'user_id': UUID('a2ad418f-74ff-4d60-8ea0-9ccf9dd5de9b'), 'pipeline_stage': 2, 'curr_run_ts': None, 'last_processed_ts': 1554724462.427, 'last_ts_run': 1554854402.90114}, {'_id': ObjectId('5c9c1c9a4e276d709893e7a7'), 'user_id': UUID('a2ad418f-74ff-4d60-8ea0-9ccf9dd5de9b'), 'pipeline_stage': 3, 'curr_run_ts': None, 'last_processed_ts': 1554724462.427, 'last_ts_run': 1554854402.9124398}, {'_id': ObjectId('5c9c1c9a4e276d709893e7ad'), 'user_id': UUID('a2ad418f-74ff-4d60-8ea0-9ccf9dd5de9b'), 'pipeline_stage': 11, 'curr_run_ts': None, 'last_processed_ts': 1554724462.427, 'last_ts_run': 1554854402.9235072}, {'_id': ObjectId('5c9c1c9b4e276d709893e809'), 'user_id': UUID('a2ad418f-74ff-4d60-8ea0-9ccf9dd5de9b'), 'pipeline_stage': 4, 'curr_run_ts': None, 'last_processed_ts': 1554044919.0, 'last_ts_run': 1554076813.2707453}, {'_id': ObjectId('5c9c1c9b4e276d709893e814'), 'user_id': UUID('a2ad418f-74ff-4d60-8ea0-9ccf9dd5de9b'), 'pipeline_stage': 9, 'curr_run_ts': None, 'last_processed_ts': None, 'last_ts_run': 1554768051.6740267}]
2019-04-10 02:00:43,357:DEBUG:140230579087104:insert called with entry of type <class 'emission.core.wrapper.entry.Entry'>
2019-04-10 02:00:43,357:DEBUG:140230579087104:entry was fine, no need to fix it
2019-04-10 02:00:43,357:DEBUG:140230579087104:Inserting entry Entry({'_id': ObjectId('5cad322b4e276df10959b11f'), 'user_id': UUID('a2ad418f-74ff-4d60-8ea0-9ccf9dd5de9b'), 'metadata': Metadata({'key': 'stats/pipeline_time', 'platform': 'server', 'write_ts': 1554854443.3561354, 'time_zone': 'America/Los_Angeles', 'write_local_dt': LocalDate({'year': 2019, 'month': 4, 'day': 9, 'hour': 17, 'minute': 0, 'second': 43, 'weekday': 1, 'timezone': 'America/Los_Angeles'}), 'write_fmt_time': '2019-04-09T17:00:43.356135-07:00'}), 'data': {'name': 'MODE_INFERENCE', 'ts': 1554854443.355965, 'reading': 35.414012383669615}}) into timeseries
`

As far as I understand, this error causes the pipeline to stop and proceed to next stage.
And I checked the stage_pipeline_state collection in mongo, the pipeline stage 4 is stuck to April 1, whereas other stages are run nightly (at least for 2 users of the currently only 4 users - since mongodb clearup).

It is not clear to me, but the bbox posted seems correct, so I interpret that the error may be due to the Overpass API not responding, I don't see [in the code](https://github.com/shankari/e-mission-server/blob/ground_truth_matching/emission/net/ext_service/transit_matching/match_stops.py) how is handled the case of Overpass not responding?

Also, there is a conf file for defining the overpass URL but here the URL is hardcoded inline?

Please tell me if you need further info.

**Comment by PatGendre** [comment]
maybe I should create another issue for that question : in profile / download json dumps, the user can also choose one date, but the file has an start date and end date, would it be possible for the user to export all the timelines between 2 dates and send it gzipped by e-mail?

**Comment by shankari** [comment]
@PatGendre please create another issue :)

**Comment by PatGendre** [comment]
I could re-run the pipeline and the Speedo has disappeared :-) So I will close the issue.
But I suggest that a troubleshooting tip be added in case this happens again, I will open up an issue for that.
