### ISSUE TITLE
Custom e-mission-base client reports HTTP/1.1 500 error

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#397]
Customization: this is a debug build of the `e-mission-base` Android client in the `master` branch. Nothing has been modified except a new name in `config.xml` and `package.json`. 

Expected behavior: I should be able to log in the app with no extra warnings, just like the EmTripLog app in the play store. 

Actual behavior: While I was able to log in and land on the main app UI, the client reports HTTP/1.1 500 error: 
![image](https://user-images.githubusercontent.com/20229080/57477101-cb92fe80-724c-11e9-8bb3-0083f80b7016.png)

The key error messages in logcat are:
```
2019-05-09 11:18:09.732 25729-25729/com.aware.plugin.cmu.sup W/RenderThread: type=1400 audit(0.0:10070): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=21643 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
2019-05-09 11:18:09.910 25729-25887/com.aware.plugin.cmu.sup W/System.err: com.google.android.gms.auth.GoogleAuthException: ServiceDisabled
2019-05-09 11:18:09.910 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at com.google.android.gms.auth.zze.zzy(Unknown Source:268)
2019-05-09 11:18:09.910 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at com.google.android.gms.auth.zzd.zza(Unknown Source:22)
2019-05-09 11:18:09.911 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at com.google.android.gms.auth.zzd.zzb(Unknown Source:71)
2019-05-09 11:18:09.911 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at com.google.android.gms.auth.zzd.getToken(Unknown Source:3)
2019-05-09 11:18:09.911 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at com.google.android.gms.auth.zzd.getToken(Unknown Source:5)
2019-05-09 11:18:09.911 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at com.google.android.gms.auth.zzd.getToken(Unknown Source:8)
2019-05-09 11:18:09.911 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source:0)
2019-05-09 11:18:09.912 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at edu.berkeley.eecs.emission.cordova.jwtauth.GoogleAccountManagerAuth.getServerToken(GoogleAccountManagerAuth.java:119)
2019-05-09 11:18:09.912 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at edu.berkeley.eecs.emission.cordova.comm.CommunicationHelper.getTokenSync(CommunicationHelper.java:185)
2019-05-09 11:18:09.912 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at edu.berkeley.eecs.emission.cordova.comm.CommunicationHelper.pushGetJSON(CommunicationHelper.java:89)
2019-05-09 11:18:09.912 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at edu.berkeley.eecs.emission.cordova.comm.CommunicationHelperPlugin$1.run(CommunicationHelperPlugin.java:27)
2019-05-09 11:18:09.913 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-05-09 11:18:09.913 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-05-09 11:18:09.913 25729-25887/com.aware.plugin.cmu.sup W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-05-09 11:18:10.501 25729-25887/com.aware.plugin.cmu.sup I/RequestAddCookies: Cookie store not available in HTTP context
2019-05-09 11:18:10.608 25729-25887/com.aware.plugin.cmu.sup I/ResponseProcessCookies: Cookie store not available in HTTP context
2019-05-09 11:18:10.612 25729-25887/com.aware.plugin.cmu.sup I/CommunicationHelper: Got response org.apache.http.message.BasicHttpResponse@a647b17 with status HTTP/1.1 500 Internal Server Error
2019-05-09 11:18:10.613 25729-25887/com.aware.plugin.cmu.sup E/class com.aware.plugin.cmu.sup.R: Failed to get JSON object
```
The full log, from installation to the error, is attached here. 
[e-mission-base_log.txt](https://github.com/e-mission/e-mission-docs/files/3163483/e-mission-base_log.txt)

**Comment by shankari** [comment]
> Expected behavior: I should be able to log in the app with no extra warnings, just like the EmTripLog app in the play store.

This is not the expected behavior. If you use google auth, you have to generate a new set of tokens if you have a new custom app.
https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-phone/create_a_new_custom_client.md

> If you want to use google auth, create google auth credentials correctly for the new package name and include them into www/json/connectionConfig.json
