### ISSUE TITLE
Module 'angularLocalStorage' is not available

### ISSUE THREAD

**Issue by pgranato** [e-mission/e-mission-docs#409]
Hi,
I'm trying to set up an e-mission environment on my local machine.
I followed instructions at the following pages:

https://github.com/e-mission/e-mission-server
https://github.com/e-mission/e-mission-docs/blob/master/docs/e-mission-server/manual_install.md
https://github.com/e-mission/e-mission-devapp
https://github.com/e-mission/e-mission-phone

but when I open the app in the android simulator I get the following error:

```
[INFO:CONSOLE(17917)] "Uncaught Error: [$injector:modulerr] Failed to instantiate module emission due to:
    Error: [$injector:modulerr] Failed to instantiate module emission.controllers due to:
    Error: [$injector:modulerr] Failed to instantiate module emission.splash.updatecheck due to:
    Error: [$injector:modulerr] Failed to instantiate module emission.plugin.kvstore due to:
    Error: [$injector:modulerr] Failed to instantiate module angularLocalStorage due to:
    Error: [$injector:nomod] Module 'angularLocalStorage' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
    http://errors.angularjs.org/1.5.3/$injector/nomod?p0=angularLocalStorage
        at file:///data/user/0/edu.berkeley.eecs.emission.devapp/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:13438:12
        at file:///data/user/0/edu.berkeley.eecs.emission.devapp/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:15404:17
        at ensure (file:///data/user/0/edu.berkeley.eecs.emission.devapp/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:15328:38)
        at module (file:///data/user/0/edu.berkeley.eecs.emission.devapp/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:15402:14)
        at file:///data/user/0/edu.berkeley.eecs.emission.devapp/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:17894:22
        at forEach (file:///data/user/0/edu.berkeley.eecs.emission.devapp/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:13691:20)
        at loadModules (file:///data/user/0/edu.berkeley.eecs.emission.devapp/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:17878:5)
        at file:///data/user/0/edu.berkeley.eecs.emission.devapp/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:17895:40
        at forEach (file:///data/user/0/edu.berkeley.eecs.emission.devapp/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:13691:20)
        at loadModules (file:///data/user/0/edu.berkeley.eecs.emission.devapp/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:17878:5)
```

Does anyone have some hint on how to troubleshoot this situation?
Thanks.
Pasquale

**Comment by shankari** [comment]
@pgranato the `angularLocalStorage` module is in `www/lib/angularLocalStorage` and is installed by bower (https://github.com/e-mission/e-mission-phone/blob/master/bower.json#L23).

Do you have a `www/lib/angularLocalStorage` directory?
If not, what is the output of `bower install` (step 6 in https://github.com/e-mission/e-mission-phone/blob/master/README.md)?

**Comment by pgranato** [comment]
Thanks a lot, for some reason the bower install didn't work initially. I repeated the installation and now the app seems to work fine.
