### ISSUE TITLE
Trips will not synced up and analyzed.

### ISSUE THREAD

**Issue by atton16** [e-mission/e-mission-docs#418]
Since the last merge on `rk-unsw`, the trips are appear to stayed in draft version and not get analyzed.

I am not certain if it will not sync up to the server at all or simply the server will not analyzed.

I am trying to investigate the `loggerDB` but not what what to look for.

Here is the file for your reference. [loggerDB.zip](https://github.com/e-mission/e-mission-docs/files/3293926/loggerDB.zip)

**Comment by atton16** [comment]
Ok, so it looks like the trips get uploaded to the server correctly but none of it get analyzed.

Here is the look inside `Stage_timeseries`
<img width="1075" alt="Screen Shot 2019-06-16 at 15 01 47" src="https://user-images.githubusercontent.com/5247367/59561203-af526080-9047-11e9-85ca-a6d2f55cc115.png">

And here is the look inside `Stage_analysis_timeseries`
<img width="432" alt="Screen Shot 2019-06-16 at 14 59 26" src="https://user-images.githubusercontent.com/5247367/59561212-c8f3a800-9047-11e9-8404-5f1eb33e4a85.png">

**Comment by atton16** [comment]
Perhaps, the pipeline is in the wrong state. I will try to reset the pipeline now.

**Comment by atton16** [comment]
This is the last few lines of the log from resetting the pipeline

```bash
INFO:root:first_cleaned_place.exit = 1553353564.746 (2019-03-23T16:06:04.746000+01:00), resetting to start
INFO:root:About to delete 7119 analysis results
INFO:root:About to delete entries with keys ['segmentation/raw_trip', 'segmentation/raw_place', 'segmentation/raw_section', 'analysis/smoothing', 'analysis/recreated_location', 'analysis/cleaned_section', 'analysis/cleaned_place', 'analysis/cleaned_trip', 'inference/prediction', 'analysis/inferred_section', 'segmentation/raw_untracked', 'analysis/cleaned_untracked']
INFO:root:About to delete 8 pipeline states
INFO:root:this is not a dry run, result of removing analysis objects = {'n': 7119, 'ok': 1.0}
INFO:root:this is not a dry run, result of removing pipeline states = {'n': 8, 'ok': 1.0}
Connecting to database URL mongo-e-mission-server
Namespace(all=True, date='2015-07-21', dry_run=False, email_list=None, platform=None, user_list=None)
```

**Comment by atton16** [comment]
Now I ran the pipeline but nothing happened. The log file (`intake.stdinout`) only contain pipeline's STDOUT from `2019-06-10`

```
Connecting to database URL mongo-e-mission-server
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
2019-06-10T02:00:05.382572+00:00**********UUID 6420c449-25c1-4d42-8118-09fa78248aa6: moving to long term**********
2019-06-10T02:00:05.550280+00:00**********UUID 6420c449-25c1-4d42-8118-09fa78248aa6: filter accuracy if needed**********
2019-06-10T02:00:05.558475+00:00**********UUID 6420c449-25c1-4d42-8118-09fa78248aa6: segmenting into trips**********
2019-06-10T02:00:06.517062+00:00**********UUID 6420c449-25c1-4d42-8118-09fa78248aa6: segmenting into sections**********
2019-06-10T02:00:07.807184+00:00**********UUID 6420c449-25c1-4d42-8118-09fa78248aa6: smoothing sections**********
2019-06-10T02:00:09.166720+00:00**********UUID 6420c449-25c1-4d42-8118-09fa78248aa6: cleaning and resampling timeline**********
2019-06-10T02:00:11.801915+00:00**********UUID 6420c449-25c1-4d42-8118-09fa78248aa6: inferring transportation mode**********
2019-06-10T02:00:13.160122+00:00**********UUID 6420c449-25c1-4d42-8118-09fa78248aa6: checking active mode trips to autocheck habits**********
2019-06-10T02:00:13.163711+00:00**********UUID 6420c449-25c1-4d42-8118-09fa78248aa6: storing views to cache**********
2019-06-10T02:00:48.259362+00:00**********UUID 74fc6ede-ece0-43b5-ade3-456ebe034e3f: moving to long term**********
2019-06-10T02:00:52.240300+00:00**********UUID 74fc6ede-ece0-43b5-ade3-456ebe034e3f: filter accuracy if needed**********
2019-06-10T02:00:52.247857+00:00**********UUID 74fc6ede-ece0-43b5-ade3-456ebe034e3f: segmenting into trips**********
2019-06-10T02:00:53.250237+00:00**********UUID 74fc6ede-ece0-43b5-ade3-456ebe034e3f: segmenting into sections**********
2019-06-10T02:00:54.443101+00:00**********UUID 74fc6ede-ece0-43b5-ade3-456ebe034e3f: smoothing sections**********
2019-06-10T02:00:55.703240+00:00**********UUID 74fc6ede-ece0-43b5-ade3-456ebe034e3f: cleaning and resampling timeline**********
2019-06-10T02:00:58.070892+00:00**********UUID 74fc6ede-ece0-43b5-ade3-456ebe034e3f: inferring transportation mode**********
2019-06-10T02:00:59.445787+00:00**********UUID 74fc6ede-ece0-43b5-ade3-456ebe034e3f: checking active mode trips to autocheck habits**********
2019-06-10T02:00:59.449446+00:00**********UUID 74fc6ede-ece0-43b5-ade3-456ebe034e3f: storing views to cache**********
Traceback (most recent call last):
  File "bin/intake_multiprocess.py", line 14, in <module>
    import emission.pipeline.scheduler as eps
  File "/usr/src/app/emission/pipeline/scheduler.py", line 11, in <module>
    import pandas as pd
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/pandas/core/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/pandas/core/frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/pandas/core/series.py", line 3042, in <module>
    import pandas.plotting._core as _gfx  # noqa
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/pandas/plotting/__init__.py", line 8, in <module>
    from pandas.plotting import _converter
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/pandas/plotting/_converter.py", line 7, in <module>
    import matplotlib.units as units
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/matplotlib/__init__.py", line 1182, in <module>
    rcParams = rc_params()
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/matplotlib/__init__.py", line 1015, in rc_params
    fname = matplotlib_fname()
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/matplotlib/__init__.py", line 825, in matplotlib_fname
    configdir = _get_configdir()
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/matplotlib/__init__.py", line 680, in _get_configdir
    return _get_config_or_cache_dir(_get_xdg_config_dir())
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/matplotlib/__init__.py", line 657, in _get_config_or_cache_dir
    return _create_tmp_config_dir()
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/matplotlib/__init__.py", line 577, in _create_tmp_config_dir
    tempdir = tempfile.gettempdir()
  File "/opt/conda/envs/emission/lib/python3.6/tempfile.py", line 296, in gettemp[
```

**Comment by shankari** [comment]
It looks like you have an issue with creating a temporary directory 

```
  File "/opt/conda/envs/emission/lib/python3.6/site-packages/matplotlib/__init__.py", line 577, in _create_tmp_config_dir
    tempdir = tempfile.gettempdir()
  File "/opt/conda/envs/emission/lib/python3.6/tempfile.py", line 296, in gettemp[
```

Have you maybe run out of space? What is the output of `$ df -h`?

**Comment by atton16** [comment]
Hmm, I doubt this.
<img width="823" alt="Screen Shot 2019-06-16 at 23 00 34" src="https://user-images.githubusercontent.com/5247367/59566447-a20a9580-908a-11e9-87fb-a349be71808c.png">


I think I'd better try to restart the server.

**Comment by atton16** [comment]
So I did restart the server but this time the server refused to start.

I eventually mapped `/tmp` directory to a newly created docker volume.

Now everything is going back to usual.

Perhaps I need to update the documentation about running with docker as well.

**Comment by shankari** [comment]
> Hmm, I doubt this.

I don't see how your screenshot shows this since you do `df -h | grep home` which doesn't tell you anything about the `/tmp` directory. and the resolution indicates that the issue was with `/tmp` getting filled up. What do you store in `/tmp`? We may want to enable some kind of periodic cleanup for it.

**Comment by atton16** [comment]
We are running the server as docker container. So everything is saved under ‘/home/docker’ directory. So I have to map ‘/tmp’ of the container to docker volume and that is it.

**Comment by shankari** [comment]
@atton16 I'm glad things are working now, but the bug title seems to indicate that that this was a recent regression. Just for my own information, how was this working earlier and what changed to cause `/tmp/` to stop working? You were always using docker, so the issue with mapping `/tmp` should have always existed, right?

**Comment by atton16** [comment]
I am not certain what causes this but I am guessing that `/tmp` is full because the **system** spit every logs to that directory. I think that docker might allow a directory to inflate up to a certain limit.
So volume mapping would essentially save the files to the right location on the host machine.
