### ISSUE TITLE
Error 500 while trying to use "Filter" in e-mission-phoneapp

### ISSUE THREAD

**Issue by DO3B** [e-mission/e-mission-docs#431]
Hi, 

![image](https://user-images.githubusercontent.com/17317703/60948800-0a4c4000-a2f4-11e9-8a88-65b9bb8af505.png)

I got this error when I tried to use "Filter" in the **Dashboard** screen. The logs say that we are sending this data:

```
Sending data {"freq":"DAILY","start_time":{"year":2019,"month":7,"day":3,"weekday":null},"end_time":{"year":2019,"month":7,"day":10,"weekday":null},"metric":""}
```
And the serverside error is the following: 
```
END 2019-07-10 09:19:12.057910 POST /result/metrics/local_date 2775ba42-1f3f-4b4c-b026-8ffe18e7c0e8 0.4940342903137207
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 2004, in wrapper
    json_response = dumps(rv)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/bson/json_util.py", line 403, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/root/anaconda3/envs/emission/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/root/anaconda3/envs/emission/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/root/anaconda3/envs/emission/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/anaconda3/envs/emission/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'int64' is not JSON serializable
```

**Comment by shankari** [comment]
This is a dup of #530. I am going to track the fix there since @njriasan can help validate it.
