### ISSUE TITLE
trip segmentation error : last_ts_processed.method is None

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#436]
@shankari Hi, as we are looking more systematically at the pipeline logs, we've found an error for a user in the segmentation stage (for data from June 16 already :-( )
`2019-07-18 02:00:40,452:ERROR:139791229138688:Trip generation failed for user 3a2299d0-605a-4d92-bef8-1058d145d301
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/analysis/intake/segmentation/trip_segmentation.py", line 109, in segment_current_trips
    epq.mark_segmentation_done(user_id, get_last_ts_processed(filter_methods))
  File "/var/emission/e-mission-server/emission/analysis/intake/segmentation/trip_segmentation.py", line 165, in get_last_ts_processed
    if last_ts_processed is None or method.last_ts_processed > last_ts_processed:
TypeError: '>' not supported between instances of 'NoneType' and 'float'
`
Actually `method.last_ts_processed` is `None`

I looked a little at the code, it seems that there are two filter methods called, time and distance;
the call to DwellSegmentationTimeFilter succeeded
but the call to DwellSegmentationDistFilter failed (returned None)

**Comment by PatGendre** [comment]
as a temporary solution I skip the case so the pipeline car run to the end.
in `trip_segmentation.py`:
`def get_last_ts_processed(filter_methods):
    last_ts_processed = None
    for method in filter_methods.values():
        # 2 lines added because of exception raised
        if method.last_ts_processed is None:
            continue
        ...`

I ran the intake single pipeline for the user (without resetting it) and it seems to have processed his data.
@DO3B I will contact the user (based in Nantes) to check if he sees the data validated on the app.

**Comment by shankari** [comment]
In general, we look at both methods only when we find both kinds of data in the currently processed stream, which typically happens if/when the user switches from android to iOS or vice versa. When you contact the user, can you see if this is the case? Or if you send me the logs via email, I can see what it shows...

**Comment by PatGendre** [comment]
@Shankari Sorry for responding late. 
Good guess! This user has both installed the app on android to iOS. I talked to him recently and did not mention this pipeline problem because he won't have the time to bother about this level of detail (he's a manager;-), but if needed I can ask him to send the logs, or export the data from mongo.
