### ISSUE TITLE
a small logging error in auth.py

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#444]
when looking at the logs, I've found this error
`--- Logging error ---
Traceback (most recent call last):
  File "/root/anaconda3/envs/emission/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 447: ordinal not in range(128)
Call stack:
  File "/root/anaconda3/envs/emission/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/root/anaconda3/envs/emission/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/cheroot/workers/threadpool.py", line 109, in run
    conn.communicate()
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/cheroot/server.py", line 1152, in communicate
    req.respond()
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/cheroot/server.py", line 974, in respond
    self.server.gateway(self).respond()
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/cheroot/wsgi.py", line 131, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 1130, in __call__
    return self.wsgi(environ, start_response)
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 1104, in wsgi
    out = self._cast(self._handle(environ))
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 1998, in wrapper
    rv = callback(*a, **ka)
  File "emission/net/api/cfc_webapp.py", line 210, in getTimeseriesEntries
    user_uuid = getUUID(request)
  File "emission/net/api/cfc_webapp.py", line 464, in getUUID
    retUUID = enaa.getUUID(request, auth_method, inHeader)
  File "/var/emission/e-mission-server/emission/net/auth/auth.py", line 63, in getUUID
    retUUID = getUUIDFromToken(authMethod, userToken)
  File "/var/emission/e-mission-server/emission/net/auth/auth.py", line 37, in getUUIDFromToken
    userEmail = AuthMethodFactory.getAuthMethod(authMethod).verifyUserToken(token)
  File "/var/emission/e-mission-server/emission/net/auth/openid_auth.py", line 57, in verifyUserToken
    logging.debug("decoded_json = %s" % decoded_json)`

Actually in the decoded_json there is a field with a é (\xe9)
I changed the name for anonymity purpose ;-)

```
Message: "decoded_json = {'jti': 'd649a430-52a9-4610-bd7a-91f2abc917ed', 'exp': 1566464649, 'nbf': 0, 'iat': 1566464349, 'iss': 'https://id.indie.host/auth/realms/fabmob-io', 'aud': 'traceur', 'sub': 'a33d2488-828c-45ee-ae63-a057fea35b8b', 'typ': 'ID', 'azp': 'traceur', 'auth_time': 1566391266, 'session_state': '4887252c-8249-4889-8b04-e28b7a01b81a', 'acr': '1', 'email_verified': False, 'name': 'G\xe9rard', 'preferred_username': 'gn', 'given_name': 'Nicolas', 'family_name': 'G\xe9rard', 'email': 'gerard@gmail.com'}"
Arguments: ()
```
I guess it is a small problem, but encoding issues are too tricky for me, and it seems the app works so it is a very small issue, but I signal you the issue anyway

PS i tried in python
`encoded_json = {'jti': 'd649a430-52a9-4610-bd7a-91f2abc917ed', 'exp': 1566464649, 'nbf': 0, 'iat': 1566464349, 'iss': 'https://id.indie.host/auth/realms/fabmob-io', 'aud': 'traceur', 'sub': 'a33d2488-828c-45ee-ae63-a057fea35b8b', 'typ': 'ID', 'azp': 'traceur', 'auth_time': 1566391266, 'session_state': '4887252c-8249-4889-8b04-e28b7a01b81a', 'acr': '1', 'email_verified': False, 'name': 'G\xe9rard', 'preferred_username': 'gn', 'given_name': 'Nicolas', 'family_name': 'G\xe9rard', 'email': 'gerard@gmail.com'}`
and 
`print ("decoded_json = %s" % decoded_json))`
it works, so the encoding issue is with logging in particular?

**Comment by shankari** [comment]
It looks like logging encoding is tricky. There is a SO answer that gives a hint.
https://stackoverflow.com/a/57004134

Note: this is the only answer that is relevant to python3 - the original question and answers appear to be relevant to python2 **only**

Can you try it and see if it works?

**Comment by PatGendre** [comment]
@shankari 
If I understand well the SO page : I added in the `[webserver.conf](https://github.com/e-mission/e-mission-server/blob/master/conf/log/webserver.conf.sample)` a line with `"encoding": "UTF-8"` and restarted the server.

I'll check in the coming days if the error no longer appears, for the user(s) whose name includes a French accent...
If this works for the webserver.conf, I supposed I'll have to do the same for the `intake.conf` file?

**Comment by shankari** [comment]
yes, you should do this for all logs.
You can also test it ahead of time by adding a

```
logging.debug("trying to log unicode character é")
```

 to `cfc_webapp.py` (e.g. right around here https://github.com/e-mission/e-mission-server/blob/master/emission/net/api/cfc_webapp.py#L465) and ensure that it is logged correctly.

**Comment by shankari** [comment]
if you can confirm that this works, I can make the related change to master

**Comment by PatGendre** [comment]
I confirm : 
`2019-08-29 19:21:48,806:DEBUG:139901842319104:trying to log unicode character é`

Thank you again :-)

**Comment by PatGendre** [comment]
@shankari the issue is closed but check the PR, it has to be corrected https://github.com/e-mission/e-mission-server/pull/717#issuecomment-529511122
