### ISSUE TITLE
pipeline error in storing view to cache

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#446]
I have this blocking error in the [pipeline usercache stage](https://github.com/e-mission/e-mission-server/blob/c4471f8584ae286d8ae490c5800c2698c79a4435/emission/net/usercache/builtin_usercache_handler.py#L114)

```
2019-08-27 02:13:38,272:ERROR:140520825644800:Storing views to cache failed for user 81770b1a-ba16-4216-b316-8061b4509977
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/net/usercache/builtin_usercache_handler.py", line 109, in storeViewsToCache
    self.storeTimelineToCache(time_query)
  File "/var/emission/e-mission-server/emission/net/usercache/builtin_usercache_handler.py", line 199, in storeTimelineToCache
    uc.putDocument("diary/trips-%s"%day, day_gj_list)
  File "/var/emission/e-mission-server/emission/net/usercache/builtin_usercache.py", line 106, in putDocument
    upsert=True)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/pymongo/collection.py", line 2535, in update
    collation=collation)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/pymongo/collection.py", line 766, in _update
    codec_options=self.__write_response_codec_options).copy()
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 482, in command
    self._raise_connection_failure(error)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 610, in _raise_connection_failure
    raise error
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 477, in command
    collation=collation)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/pymongo/network.py", line 99, in command
    name, size, max_bson_size + message._COMMAND_OVERHEAD)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/pymongo/message.py", line 626, in _raise_document_too_large
    raise DocumentTooLarge("command document too large")
pymongo.errors.DocumentTooLarge: command document too large
```

Is there a way to change pipeline or mongodb config so as to avoid this error?
This user is an Android user so may have data collected in August so maybe concerned with the recent utf-8 août problem although I don't think so as this concerns data already in mongo, presumably?

**Comment by shankari** [comment]
As you can see, the error is 

```
2019-08-27 02:13:38,272:ERROR:140520825644800:Storing views to cache failed for user 81770b1a-ba16-4216-b316-8061b4509977
...
pymongo.errors.DocumentTooLarge: command document too large
```

Basically, the user appears to have a lot of data for a particular day, so when we try to pre-create and store the timeline, it is too large. You could either increase the mongodb max document size (https://docs.mongodb.com/manual/reference/limits/), or disable the `storeViewsToCache` step
https://github.com/e-mission/e-mission-server/blob/master/emission/pipeline/intake_stage.py#L162
 for a week, by which time this day will be too old to be cached and the error will disappear.

**Comment by PatGendre** [comment]
@shankari Thanks
I checked your link, in fact, it is [not possible to increase doc size](https://stackoverflow.com/questions/25553186/mongodb-and-pymongo-16mb-limit-on-document-size) in mongo, you have to use the GridFS API, which is far too complicated for me.

So the second way is to disable the storeviewstocache : I can comment the line in the code for a week, but what is the potentiel impact for the other users?
An alternative would to delete the data for this date for the user in usercache, or could this have side effects?

Also, how is it possible that a document sent from the app to usercache is larger than 16MB? Did you ever see this occurring before?
Actually I tried to just look at the JSON document in mongodb to see if the document would be a "normal" e-mission document, the request worked but when I tried to display the JSON (in robo3t) it crashed...

**Comment by shankari** [comment]
I don't see how you can look at the JSON document it mongodb since it was never saved.

```
  File "/var/emission/e-mission-server/emission/net/usercache/builtin_usercache_handler.py", line 199, in storeTimelineToCache
    uc.putDocument("diary/trips-%s"%day, day_gj_list)
  File "/var/emission/e-mission-server/emission/net/usercache/builtin_usercache.py", line 106, in putDocument
    upsert=True)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/pymongo/collection.py", line 2535, in update
    collation=collation)
```

**Comment by shankari** [comment]
> So the second way is to disable the storeviewstocache : I can comment the line in the code for a week, but what is the potentiel impact for the other users?

Nothing really. Since the pipeline execution is not guaranteed to be synchronous, the app will reconstruct the timeline from whatever has run so far. There might be a small performance impact, since the timeline has to be reconstructed instead of read from the cache.

> An alternative would to delete the data for this date for the user in usercache, or could this have side effects?

Well, the usercache has both incoming and outgoing data, so deleting everything would be bad. Deleting only outgoing data won't hurt anything, but not sure that it will help given that the error is while storing the data, not reading it.

**Comment by shankari** [comment]
> Since the pipeline execution is not guaranteed to be synchronous, the app will reconstruct the timeline from whatever has run so far. 

Because of this, you could also just try/catch and ignore the exception. Then we will continue to cache timelines for small documents but ignore for big ones.

**Comment by PatGendre** [comment]
Ok, thank you, I have commented out the storeviewtocache stage, I will try to test the intake pipeline to see if it is not visibly getting too slow and I'll reactivate this in one week.

Still, I wonder why may have caused a too big document.

**Comment by shankari** [comment]
you can add a logging statement to this method

```
@post('/timeline/getTrips/<day>')
def getTrips(day):
```

in `emission/net/api/cfc_webapp.py` to log the output before it is returned

**Comment by PatGendre** [comment]
@shankari thanks for the explanations
I checked on the intake log, I've found 2 "document too large" errors, one day with 96 trips for 1 user, one day with 169 trips for another user.

`2019-08-27 02:16:29,457:DEBUG:140520825644800:Found 0 messages in response to query {'user_id': UUID('f6356066-21a8-4113-8535-4b4df073b996'), '$or': [{'metadata.key': 'manual/incident'}], 'data.ts': {'$lte': 1564084072.071, '$gte': 1564082543.1428165}}
2019-08-27 02:16:29,457:DEBUG:140520825644800:trip count = 374, geojson count = 272
2019-08-27 02:16:29,458:DEBUG:140520825644800:Found 272 trips in seven days starting from 1564084077.071 (2019-07-25T19:47:57.071000)
2019-08-27 02:16:29,461:DEBUG:140520825644800:After binning, we have 4 bins, of which 0 are empty
2019-08-27 02:16:29,461:DEBUG:140520825644800:Adding 1 trips for day 2019-07-20
2019-08-27 02:16:29,462:DEBUG:140520825644800:Result = {'n': 1, 'nModified': 1, 'ok': 1.0, 'updatedExisting': True} after updating document diary/trips-2019-07-20
2019-08-27 02:16:29,462:DEBUG:140520825644800:Adding 34 trips for day 2019-07-23
2019-08-27 02:16:29,525:DEBUG:140520825644800:Result = {'n': 1, 'nModified': 1, 'ok': 1.0, 'updatedExisting': True} after updating document diary/trips-2019-07-23
2019-08-27 02:16:29,525:DEBUG:140520825644800:Adding 169 trips for day 2019-07-24
2019-08-27 02:16:30,608:ERROR:140520825644800:Storing views to cache failed for user f6356066-21a8-4113-8535-4b4df073b996
`

`2019-08-27 02:13:36,805:DEBUG:140520825644800:Found 0 messages in response to query {'user_id': UUID('81770b1a-ba16-4216-b316-8061b4509977'), '$or': [{'metadata.key': 'manual/incident'}], 'data.ts': {'$lte': 1564579493.375, '$gte': 1564569181.380994}}
2019-08-27 02:13:36,805:DEBUG:140520825644800:trip count = 1128, geojson count = 960
2019-08-27 02:13:36,805:DEBUG:140520825644800:Found 960 trips in seven days starting from 1564579498.375 (2019-07-31T13:24:58.375000)
2019-08-27 02:13:36,816:DEBUG:140520825644800:After binning, we have 8 bins, of which 0 are empty
2019-08-27 02:13:36,816:DEBUG:140520825644800:Adding 96 trips for day 2019-07-24
2019-08-27 02:13:37,246:DEBUG:140520825644800:Result = {'n': 1, 'nModified': 1, 'ok': 1.0, 'updatedExisting': True} after updating document diary/trips-2019-07-24
2019-08-27 02:13:37,246:DEBUG:140520825644800:Adding 96 trips for day 2019-07-25
2019-08-27 02:13:38,272:ERROR:140520825644800:Storing views to cache failed for user 81770b1a-ba16-4216-b316-8061b4509977
`

I managed to use the get_trips_for_day method for user1, the text dump of ret_geojson is 48 MB!
For user2, I don't find any data in the database for the day supposed to have 169 trips.

**Comment by PatGendre** [comment]
The save_ground_truth script works, but did not work the data I wanted to look at, though, because the [edb.get_usercache_db()](https://github.com/e-mission/e-mission-server/blob/c4471f8584ae286d8ae490c5800c2698c79a4435/bin/debug/save_ground_truth.py#L29) did not return anything, I suppose because the data is not in the usercache.

`Traceback (most recent call last):
  File "bin/debug/save_ground_truth.py", line 30, in <module>
    print("Retrieved object is of length %s" % len(tj))
TypeError: object of type 'NoneType' has no len()`

**Comment by PatGendre** [comment]
and certainly it is a good idea to catch the exception "document too large" if this happens again

**Comment by shankari** [comment]
> The save_ground_truth script works, but did not work the data I wanted to look at, though, because the edb.get_usercache_db() did not return anything, I suppose because the data is not in the usercache.

Oh yeah, the `save_ground_truth` script reads the data from the output cache. Sorry I forgot that :)

**Comment by shankari** [comment]
> I managed to use the get_trips_for_day method for user1, the text dump of ret_geojson is 48 MB!

So does it really have 96 trips? If there are 24 hours in the day, that is 2 trips/hr, which seems a little unreasonable!

> I managed to use the get_trips_for_day method for user1, the text dump of ret_geojson is 48 MB!
Something I don't understand is that when I look at the usercache for user1, I find the July 25 diary, but with only 2 raw trips? (not 96)

Not sure which one is `user1` and which one is `user2`. But assuming you have listed them in order, `user1` has `169 trips for day 2019-07-24 2019-08-27` no?

**Comment by PatGendre** [comment]
I checked again.
For one user (say user 1) I've found 189 "raw trips" in the JSON timeline on July 24.
For user 2 I cannot find so many trips around July 24 (12 raw trips on July 24).
It is not clear why I don't get the same trip number than when executing the pipeline on August 27, however there is a day for a user1 with many raw trips. Although I did not look on a map, I checked the coordinates, there are located in France, so the trips seems realistic.
Note that this error never occured again since end August.

**Comment by PatGendre** [comment]
@shankari I looked at the data, for this July 24 date, I have 189 trips in the analysis database, but actually there are 8 different trips, each replicated several times (around 20 times each). I have not idea why the data is replicated so many times for this particular day and user, do you remember other times when the same kind of issue occurs?
Anyway it did not occur again since then so I can close the issue I guess.
