### ISSUE TITLE
python package dependency errors even after conda update

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#463]
@shankari we had to reboot the server yesterday and since there is no connection from the app to the server.
We always get a CommunicationHelper log in the app with a 500 error. We don't see the 500 error in the webserver logs, though.
However, the web server is up, it is possible to access the web site, and also the web API works (heatmap, and presumably metrics).
Any suggestion of what we should test to find and fix what is going wrong?
Thanks!

**Comment by shankari** [comment]
500 error will show up in the webserver console. It is an exception thrown from somewhere in the code. May be related to the `/usercache/get` and `/usercache/put` code paths in particular so that's why the other calls work.

**Comment by PatGendre** [comment]
@shankari thanks but no 500 shows up in the webserver console log, did we configure the log badly?
It happens for usercache calls, but seemingly for any other action such as metrics, in the app log there are always the 3 same messages in that order : 
- js: error loading user data (error 500)
- class fabmob.moblity.tracker.R : Failed to get JSON object
- CommunicationHelper : got response xxx.BasicHttpResponse@ with status error 500

**Comment by shankari** [comment]
I just confirmed that 500 errors will show up in the webserver console logs. You need to find the place where you are storing the logs like the ones shown below.

-----
1. I added a forced exception to `/usercache/get`

```
 @post('/usercache/get')
 def getFromCache():
   logging.debug("Called userCache.get")
+  raise RuntimeError("please show up")
   user_uuid=getUUID(request)
   logging.debug("user_uuid %s" % user_uuid)
   to_phone = usercache.sync_server_to_phone(user_uuid)
```
1. I called the method

```
In [1]: import requests

In [4]: requests.post("http://localhost:8080/usercache/get")
Out[4]: <Response [500]>
```

1. The error showed up in the logs.

```
e-mission-server shankari$ ./e-mission-py.bash emission/net/api/cfc_webapp.py
Connecting to database URL localhost
Finished configuring logging for <RootLogger root (WARNING)>
Replaced json_dumps in plugin with the one from bson
Changing bt.json_loads from <function <lambda> at 0x1098fbd90> to <function loads at 0x10a1b40d0>
Running with HTTPS turned OFF - use a reverse proxy on production
Bottle v0.13-dev server starting up (using CherootServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

START 2019-10-09 07:16:15.291568 POST /usercache/get
END 2019-10-09 07:16:15.292214 POST /usercache/get  0.0005440711975097656
Traceback (most recent call last):
  File "/Users/shankari/e-mission/e-mission-server/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/Users/shankari/e-mission/e-mission-server/emission/net/api/bottle.py", line 1998, in wrapper
    rv = callback(*a, **ka)
  File "emission/net/api/cfc_webapp.py", line 230, in getFromCache
    raise RuntimeError("please show up")
RuntimeError: please show up
```

**Comment by shankari** [comment]
@PatGendre note that it doesn't actually say 500, it just throws an exception. Is there a "Traceback" in the logs?

>  The webserver console logging level in the conf is currently NOTSET, shall I set it to DEBUG?

That might also be the problem. It is set to `WARNING` in the default

```
        "console": {
            "class": "logging.StreamHandler",
            "level": "WARNING"
        },
...
    "root": {
        "handlers": [
            "console",
            "file",
            "errors"
        ],
        "level": "DEBUG"
    },
```

**Comment by PatGendre** [comment]
@shankari I've set to WARNING and restarted the server but I don't see anything
example:
`2019-10-09 16:56:44,800:DEBUG:140048200652544:START POST /result/metrics/timestamp
2019-10-09 16:56:44,802:DEBUG:140048200652544:metric_list = ['duration', 'median_speed', 'count', 'distance']
2019-10-09 16:56:44,804:DEBUG:140048200652544:['duration -> <function get_duration at 0x7f5f834ce598>', 'median_speed -> <function get_median_speed at 0x7f5f834ce620>', 'count -> <function get_count at 0x7f5f834ce488>', 'distance -> <function get_distance at 0x7f5f834ce510>']
2019-10-09 16:56:44,806:DEBUG:140048200652544:for user None, returning timeseries <emission.storage.timeseries.aggregate_timeseries.AggregateTimeSeries object at 0x7f5f8341c630>
2019-10-09 16:56:44,807:DEBUG:140048200652544:curr_query = {'invalid': {'$exists': False}, '$or': [{'metadata.key': 'analysis/inferred_section'}], 'data.start_ts': {'$lte': 1570623161, '$gte': 1568757600}}, sort_key = None
2019-10-09 16:56:44,809:DEBUG:140048200652544:orig_ts_db_keys = [], analysis_ts_db_keys = ['analysis/inferred_section']
2019-10-09 16:56:44,812:DEBUG:140048200652544:finished querying values for [], count = 0
2019-10-09 16:56:44,852:DEBUG:140048200652544:finished querying values for ['analysis/inferred_section'], count = 1215
2019-10-09 16:56:44,887:DEBUG:140048200652544:orig_ts_db_matches = 0, analysis_ts_db_matches = 1215`

I see user "none" so maybe I should log out and log in again? I will test that

**Comment by shankari** [comment]
> I see user "none" so maybe I should log out and log in again? I will test that

User `none` is for getting the aggregate values since this is a metrics call `/result/metrics/timestamp`

you should have a separate call to `/result/metrics/timestamp` with the user to get the user-specific entries

**Comment by PatGendre** [comment]
at last I have the correct logs !
And this is the error:
`START 2019-10-09 17:25:59.450789 POST /datastreams/find_entries/timestamp
END 2019-10-09 17:25:59.671981 POST /datastreams/find_entries/timestamp  0.22101402282714844 
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 2007, in wrapper
    rv = callback(*a, **ka)
  File "emission/net/api/cfc_webapp.py", line 210, in getTimeseriesEntries
    user_uuid = getUUID(request)
  File "emission/net/api/cfc_webapp.py", line 464, in getUUID
    retUUID = enaa.getUUID(request, auth_method, inHeader)
  File "/var/emission/e-mission-server/emission/net/auth/auth.py", line 63, in getUUID
    retUUID = getUUIDFromToken(authMethod, userToken)
  File "/var/emission/e-mission-server/emission/net/auth/auth.py", line 37, in getUUIDFromToken
    userEmail = AuthMethodFactory.getAuthMethod(authMethod).verifyUserToken(token)
  File "/var/emission/e-mission-server/emission/net/auth/openid_auth.py", line 55, in verifyUserToken
    decoded_token = jwt.JWT(key=self.jwk_keyset, jwt=token)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/jwcrypto/jwt.py", line 204, in __init__
    self.deserialize(jwt, key)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/jwcrypto/jwt.py", line 474, in deserialize
    self.token.verify(token_key)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/jwcrypto/jws.py", line 283, in verify
    'signatures' + repr(self.verifylog))
jwcrypto.jws.InvalidJWSSignature: Verification failed for all signatures['Failed: [InvalidJWSSignature("Verification failed {ImportError(\'libssl.so.1.1: cannot open shared object file: No such file or directory\',)}",)]']`

**Comment by PatGendre** [comment]
I suspect this is because yesterday I had to re-create the emission conda env, I ran the setup.sh script but for some reason I may have not installed the exact same version as required?

**Comment by shankari** [comment]
aha! first, this explains why you were not getting the error for the aggregate case. this error occurs during authentication, when we communicate with the auth server to decode the JWT that we have received from the client (e.g. `decoded_token = jwt.JWT(key=self.jwk_keyset, jwt=token)`)

**Comment by shankari** [comment]
> I suspect this is because yesterday I had to re-create the emission conda env, I ran the setup.sh script but for some reason I may have not installed the exact same version as required?

Hm. Maybe try removing and recreating the environment?

**Comment by PatGendre** [comment]
Ok, actually I have to leave the office for one hour, I will test later tonight.
Do you see any particular caveat with the SSL/openssl lib?
Again thank you so much, I was quite upset with this problem today! And I think the solution is not far:-)

**Comment by shankari** [comment]
The setup currently installs `jwcrypto` using pip. 
Apparently that causes issues on update? https://stackoverflow.com/a/36063405/4040267

It is now included in conda-forge (since the past 8 months)
https://anaconda.org/conda-forge/jwcrypto

 so if removing and recreating the environment does not work, then probably something like 

```
(emission) $ pip uninstall jwcrypto
(emission) $ conda install jwcrypto
```

should work.

LMK what you find out!

**Comment by PatGendre** [comment]
@shankari thanks!
This worked with `conda install --channel "conda-forge" jwcrypto`
No I have jwcrypto 0.6.0 instead of 0.4.2
But then there seems to be [a problem with openssl](https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_derive.html)?
```
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/var/emission/e-mission-server/emission/net/api/bottle.py", line 2007, in wrapper
    rv = callback(*a, **ka)
  File "emission/net/api/cfc_webapp.py", line 236, in getFromCache
    user_uuid=getUUID(request)
  File "emission/net/api/cfc_webapp.py", line 464, in getUUID
    retUUID = enaa.getUUID(request, auth_method, inHeader)
  File "/var/emission/e-mission-server/emission/net/auth/auth.py", line 63, in getUUID
    retUUID = getUUIDFromToken(authMethod, userToken)
  File "/var/emission/e-mission-server/emission/net/auth/auth.py", line 37, in getUUIDFromToken
    userEmail = AuthMethodFactory.getAuthMethod(authMethod).verifyUserToken(token)
  File "/var/emission/e-mission-server/emission/net/auth/openid_auth.py", line 55, in verifyUserToken
    decoded_token = jwt.JWT(key=self.jwk_keyset, jwt=token)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/jwcrypto/jwt.py", line 204, in __init__
    self.deserialize(jwt, key)
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/jwcrypto/jwt.py", line 474, in deserialize
    raise JWTMissingKeyID('No key ID in JWT header')
  File "/root/anaconda3/envs/emission/lib/python3.6/site-packages/jwcrypto/jws.py", line 283, in verify
    # verifies
jwcrypto.jws.InvalidJWSSignature: Verification failed for all signatures['Failed: [InvalidJWSSignature(\'Verification failed {ImportError("cannot import name \\\'_evp_pkey_derive\\\'",)}\',)]']

But I hesitate to install a newer version of openssl because when I first want to conda remove openssl this is impact several dozens of other packages that need to be removed too.
```

**Comment by shankari** [comment]
did you uninstall + reinstall the entire environment? did that help?

**Comment by PatGendre** [comment]
@shankari I reinstalled the conda emission env with setup.sh
and this worked !! At least for my app, but I think the problem is solved.
BTW I adapted the prefix line at the end of requirement36.yml
Actually it works when I launch the cfc webapp in a term window but when I want to launch in the background it doesn't work, but that's another question, I will check with Yann tomorrow...
Thanks a lot :-)

**Comment by shankari** [comment]
> I reinstalled the conda emission env with setup.sh and this worked !!

Woo! anaconda is supposed to take care of this kind of dependency checking, but it looks like it may sometimes mess up while updating. The solution appears to be to delete and reinstall.

Hope this helps somebody else in the future as well!
