### ISSUE TITLE
GIS based mode detection : 

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#468]
@shankari : when looking closer at the [rule_engine.py, there is a line](https://github.com/fabmob/e-mission-server-fabmob/blob/62104d3f789ade0a449123a39e672186ba8e3180/emission/analysis/classification/inference/mode/rule_engine.py#L219) which is intriguing : it checks if the public transport MODES are either BUS or TRAIN, but since this summer we added TRAM, LIGHT_RAIL and SUBWAY.
So as expected I find this error several times in the pipeline logs. I've found quite a bunch of BUS,SUBWAY and BUS,TRAM, and never 3 values for the moment - but this could well happen, too.
I suppose this should be updated ? First by commenting out this [BUS,TRAIN] check and by finding another rule of thumb for deciding which mode to choose.
And may be I should run again the pipeline afterwards...

**Comment by PatGendre** [comment]
The rule of thumb could be:
- based on speed if we have to compare TRAIN or SUBWAY with BUS, LIGHT_RAIL or TRAM
- arbitrarily choose SUBWAY if to compare with TRAIN
- arbitrarily choose LIGHT_RAIL or then TRAM or then BUS if to compare between them
If we have 3 or more modes (if could happen, in principle?), use this arbitrary rule, too.

**Comment by shankari** [comment]
I thought @DO3B fixed this in his PR. Let me check the logs...

**Comment by PatGendre** [comment]
@shankari I checked in `conf/analysis/debug.conf.json` , currently all assertions are set to `false` , because you told me it was the thing to do a few weeks ago, so as to avoid pipeline exceptions :-)

As far as I understand when classification.validityAssertions to False, this means that no exception is raised and so the pipeline code goes on, however it is not clear to me which value (i.e which mode) is returned in this case, e.g. if unique_modes=['BUS,'TRAM'] ? 
If I get it well, this will return either BUS or TRAIN depending on speeds, and the cases where we find SUBWAY, LIGHT_RAIL or TRAM are the cases where there is one single mode found, i.e. unique_modes=['TRAM']. I did not verify this, though.

**Comment by shankari** [comment]
@PatGendre congratulations, I think you have just found something that is clearly a bug.

In https://github.com/e-mission/e-mission-server/pull/709, @DO3B added code to deal with multiple returned modes correctly - i.e. if the list included `BUS` and a bunch of train modes, he would remove the `BUS` and then return the first `TRAIN` mode.
https://github.com/e-mission/e-mission-server/pull/709/files#diff-b64a9eb8dbe2ce052d4a1779485f7abdR232
If this happens a lot, we could add more rules to distinguish between the `TRAIN` modes - e.g. `logging.debug("Returning %s but could also be another train modes" % train_mapped_modes[0])`

*but* he forgot to remove the `return 'TRAIN'` line and I didn't catch it in the review either. So that code never gets executed and we always return `TRAIN`. Sorry about that :(

If you remove this line https://github.com/fabmob/e-mission-server-fabmob/blob/62104d3f789ade0a449123a39e672186ba8e3180/emission/analysis/classification/inference/mode/rule_engine.py#L230
it will default to returning the first train mode.

**Comment by PatGendre** [comment]
@shankari Ok thanks! if I understand well, I just have to remove this line and as currently the values we have in practice are either ['BUS','TRAM'] or ['BUS','SUBWAY'], train_mapped_modes[0] should be equal to 'TRAM' or 'SUBWAY', respectively.
There may be trickier corner cases but I don't see them in the logs.
So I will remove the line right away:-) And supposedly this deletion will be committed by you to master too, soon.

**Comment by PatGendre** [comment]
This explains why we had so few SUBWAY and TRAM detected. I will rerun the whole pipeline again, one day or another, to check if this is the case.

**Comment by shankari** [comment]
>  And supposedly this deletion will be committed by you to master too, soon.

Yup! As part of the misc fixes.

**Comment by st-patrick** [comment]
Hi all!

We also switched to the gis branch now and after recalculating all the modes, the detected modes are pretty much exactly the same as on the master branch.

Anyone have an idea what could be the problem here?
Pretty much the only thing that is analyzed correctly is walking but all other modes (cycling, train, car) just end up being processed as "Bus".

Thanks!
Patrick

**Comment by PatGendre** [comment]
Hi @st-patrick !
look maybe at the conf https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/conf/net/ext_service/overpass_server.json.sample ?
Possibly the call to the overpass API is not set up correctly ? (you check this in the pipeline logs)

**Comment by st-patrick** [comment]
Hey yes actually we didn't have the GIS branch setup inside the container since we though it was mounted^^ anyhow, fixed that and also copied the sample config.

Now, though, we are getting an error we cannot understand at all. Maybe this has to do with the segmentation issue?

This is the error log:

`
2019-11-14 14:18:19,840:ERROR:140198189315840:Sectioning failed for user ce8a1ed9-77f8-4c33-9243-93461b37083c
Traceback (most recent call last):
  File "/usr/src/app/emission/analysis/intake/segmentation/section_segmentation.py", line 52, in segment_current_sections
    segment_trip_into_sections(user_id, trip_entry, trip_entry.data.source)
  File "/usr/src/app/emission/analysis/intake/segmentation/section_segmentation.py", line 85, in segment_trip_into_sections
    segmentation_points = shcmsm.segment_into_sections(ts, distance_from_place, time_query)
  File "/usr/src/app/emission/analysis/intake/segmentation/section_segmentation_methods/smoothed_high_confidence_motion.py", line 170, in segment_into_sections
    self.squish_stops(motion_changes, section_list)
  File "/usr/src/app/emission/analysis/intake/segmentation/section_segmentation_methods/smoothed_high_confidence_motion.py", line 202, in squish_stops
    STOP_DISTANCE_THRESHOLD = max(eac.get_config()["section.startStopRadius"],
KeyError: 'section.startStopRadius'
2019-11-14 14:18:21,876:ERROR:140198189315840:Found key error 'section.startStopRadius' while processing trip Entry({'_id': ObjectId('5dcd6225ea3581013479f688'), 'user_id': UUID('ce8a1ed9-77f8-4c33-9243-93461b37083c'), 'metadata': {'key': 'segmentation/raw_trip', 'platform': 'server', 'write_ts': 1573741093.9543643, 'time_zone': 'America/Los_Angeles', 'write_local_dt': {'year': 2019, 'month': 11, 'day': 14, 'hour': 6, 'minute': 18, 'second': 13, 'weekday': 3, 'timezone': 'America/Los_Angeles'}, 'write_fmt_time': '2019-11-14T06:18:13.954364-08:00'}, 'data': {'source': 'DwellSegmentationTimeFilter', 'start_ts': 1437578093.881, 'start_local_dt': {'hour': 8, 'month': 7, 'second': 53, 'weekday': 2, 'year': 2015, 'timezone': 'America/Los_Angeles', 'day': 22, 'minute': 14}, 'start_fmt_time': '2015-07-22T08:14:53.881000-07:00', 'start_place': ObjectId('5dcd6225ea3581013479f687'), 'start_loc': {'type': 'Point', 'coordinates': [-122.0876886, 37.3887767]}, 'end_ts': 1437582214.517, 'end_local_dt': {'hour': 9, 'month': 7, 'second': 34, 'weekday': 2, 'year': 2015, 'timezone': 'America/Los_Angeles', 'day': 22, 'minute': 23}, 'end_fmt_time': '2015-07-22T09:23:34.517000-07:00', 'end_place': ObjectId('5dcd6225ea3581013479f689'), 'end_loc': {'type': 'Point', 'coordinates': [-122.0820411, 37.3920436]}, 'duration': 4120.635999917984, 'distance': 617.1676990580128}})
Traceback (most recent call last):
  File "/usr/src/app/emission/analysis/intake/cleaning/clean_and_resample.py", line 121, in save_cleaned_segments_for_timeline
    filtered_trip = get_filtered_trip(ts, trip)
  File "/usr/src/app/emission/analysis/intake/cleaning/clean_and_resample.py", line 208, in get_filtered_trip
    linked_tl = link_trip_timeline(trip_tl, section_map, stop_map)
  File "/usr/src/app/emission/analysis/intake/cleaning/clean_and_resample.py", line 784, in link_trip_timeline
    filled_in_stops = [_fill_stop(s, stop_map[s.get_id()], section_map) for s in tl.places]
  File "/usr/src/app/emission/analysis/intake/cleaning/clean_and_resample.py", line 784, in <listcomp>
    filled_in_stops = [_fill_stop(s, stop_map[s.get_id()], section_map) for s in tl.places]
  File "/usr/src/app/emission/analysis/intake/cleaning/clean_and_resample.py", line 819, in _fill_stop
    STOP_DISTANCE_THRESHOLD = max(eac.get_config()["section.startStopRadius"],
KeyError: 'section.startStopRadius'
`

**Comment by st-patrick** [comment]
ok so now we found the additional changes config file in conf/analysis/debug.conf.json.sample and copied those over. Now our error looks a bit different, something along the lines of currState not set for AttrDict.

We figured that since the reset script changed, too, our mistake might have been to reset the data with the new script while it was still the data from the master-branch-script we were trying to reset.
So we switched back to the master branch, did the reset, switched back to the gis branch and are currently processing ....
So far there's no error so if anything, it'll probably be some other error now.

Quick guide for anyone: before switching to gis-branch, reset the data from the pipeline with the reset script. Then, checkout the gis-branch. Following, copy all the new/modified sample files to the filename without ".sample":
conf/net/ext_service/overpass_server.json
conf/net/ext_service/overpass_transit_stops_query_template
conf/analysis/debug.conf.json

Then, run the pipeline again

**Comment by st-patrick** [comment]
ok, cool. So now bicycle is actually recognized. Walking also works most of the times, except for trips with a very short distance. Then, there's just a question mark.
All other modes (faster than bike) are simply car / IN_VEHICLE, no distinct modes for subway

But so far, we got the bicycle mode added, so that's nice

**Comment by shankari** [comment]
if they are IN_VEHICLE (speedometer icon) instead of CAR (car icon), then you are using `analysis/cleaned_section` instead of `analysis/inferred_section`. That is also configured in the conf file, so I suggest taking a second look there.
https://github.com/e-mission/e-mission-server/blob/master/conf/analysis/debug.conf.json.sample#L10

I offer that option in case somebody is using this for health tracking instead of CO2 and don't want to deal with the GIS integration.

**Comment by st-patrick** [comment]
no, actually our debug.conf.json is set to `analysis/inferred_section` and we wouldn't have changed that setting since we didn't even know about it.

Also, all the data for the phone app's metrics doesn't seem to be there anymore.

I set myself some debug output like so:
`
      console.log($scope.data.distance);
      console.log(agg_metrics);
      console.log(metric2valUser);
      console.log($scope.chartDataAggr);
      console.log($scope.chartDataUser);
`
... inside the showCharts function of metrics.js and it's all empty arrays.

I will investigate but maybe you have an idea what I need to adjust on the phone.
That way we can continue writing the steps to switch to the GIS branch or just update the repo accordingly

**Comment by shankari** [comment]
> no, actually our debug.conf.json is set to analysis/inferred_section and we wouldn't have changed that setting since we didn't even know about it.
> Also, all the data for the phone app's metrics doesn't seem to be there anymore.

That implies that the mode inference step is failing and inferred sections are not getting generated. What do you see in the logs?

A successful run should have something like

```
2019-11-13 14:05:04,551:INFO:139698597431040:For stage PipelineStages.MODE_INFERENCE, start_ts = 2019-11-13T05:23:06.164896
....
2019-11-13 14:05:04,571:DEBUG:139698597431040:~~~~~~~~~~About to get predicted value for
 section 5dcbb93a73c4e91616032fff (2019-11-13T00:45:29.001130-05:00 -> 2019-11-13T00:58:
46.001156-05:00)~~~~~~~~~~
2019-11-13 14:05:04,572:DEBUG:139698597431040:bbox_string = 40.64554407074768,-73.780469
49202789,40.64824354010516,-73.77777002267041
2019-11-13 14:05:05,919:DEBUG:139698597431040:Found 8 relations with ids [2621042, 2904582, 2904721, 2930030, 7895554, 7895590, 7895591, 8277402]
2019-11-13 14:05:05,920:DEBUG:139698597431040:Found 3 stops
2019-11-13 14:05:05,950:DEBUG:139698597431040:route relation with no nodes = {'name': 'NYCB - Q10', 'network': 'NYC Transit', 'operator': 'MTA', 'ref': 'Q10', 'route': 'bus', 'type': 'route'}
2019-11-13 14:05:05,961:DEBUG:139698597431040:route relation with no nodes = {'name': 'NYCB - B15', 'network': 'NYC Transit', 'operator': 'MTA', 'ref': 'B15', 'route': 'bus', 'type': 'route'}
2019-11-13 14:05:05,973:DEBUG:139698597431040:route relation with no nodes = {'name': 'NYCB - Q10 LTD', 'network': 'NYC Transit', 'operator': 'MTA', 'ref': 'Q10 LTD', 'route': 'bus', 'type': 'route'}
2019-11-13 14:05:05,973:DEBUG:139698597431040:Found 3 stops
2019-11-13 14:05:05,974:DEBUG:139698597431040:STOP 0: AttrDict({'type': 'node', 'id': 277752210, 'lat': 40.6468134, 'lon': -73.7798601, 'tags': {'layer': '5', 'light_rail': 'yes', 'name': 'Terminal 5', 'network': 'AirTrain JFK', 'opening_hours': '24/7', 'public_transport': 'station', 'railway': 'station', 'station': 'light_rail', 'wheelchair': 'yes', 'wikidata': 'Q7702624'}, 'routes': [{'id': 2621042, 'tags': {'colour': 'yellow', 'name': 'AirTrain JFK (railways)', 'ref': 'AirTrain JFK', 'route': 'railway', 'type': 'route', 'wikidata': 'Q406683'}}]})
....
2019-11-13 14:05:08,518:DEBUG:139698597431040:matching routes = [(2621042, 'AirTrain JFK'), (2621042, 'AirTrain JFK'), (7895554, 'JFK'), (7895554, 'JFK'), (7895590, 'JFK'), (7895590, 'JFK'), (7895591, 'JFK'), (7895591, 'JFK')]
...
2019-11-13 19:09:32,375:DEBUG:140285520701184:Inserting entry Entry(data': Metadata({'key': 'inference/prediction', 'predicted_mode_map': {'LIGHT_RAIL': 1}, 'start_ts': 1573662447.0, 'end_ts': 1573663686.0})}) into timeseries
2019-11-13 19:09:32,377:DEBUG:140285520701184:max confidence in prediction map = 1
2019-11-13 19:09:32,377:DEBUG:140285520701184:max keys in prediction map = ['LIGHT_RAIL']
2019-11-13 19:09:32,377:DEBUG:140285520701184:Updating sensed mode for section = 5dcc53e
773c4e91847faafe4 to PredictedModeTypes.LIGHT_RAIL
2019-11-13 19:09:32,378:DEBUG:140285520701184:insert called with entry of type <class 'emission.core.wrapper.entry.Entry'>
2019-11-13 19:09:32,378:DEBUG:140285520701184:entry was fine, no need to fix it
2019-11-13 19:09:32,378:DEBUG:140285520701184:Inserting entry Entry({'metadata': {'key': 'analysis/inferred_section', '...
```

You can also see whether you have `inference/prediction` and `analysis/inferred_section` entries in the database.

**Comment by st-patrick** [comment]
nope, that is not what our log looks like. We just get a general `Error while inferring modes` 
Also, I just grep'ed through the entire database and the string "infer" is not to be found in an collection.

Here is our output from pipeline processing with intake_multiprocess.py:

```
(emission) root@aeadd6c9fcde:/usr/src/app# ./e-mission-py.bash bin/intake_multiprocess.py 4
Connecting to database URL db
nominatim not configured either, place decoding must happen on the client
Connecting to database URL db
Connecting to database URL db
Connecting to database URL db
Connecting to database URL db
nominatim not configured either, place decoding must happen on the client
nominatim not configured either, place decoding must happen on the client
nominatim not configured either, place decoding must happen on the client
nominatim not configured either, place decoding must happen on the client
2019-11-14T16:58:34.983257+00:00**********UUID ce8a1ed9-77f8-4c33-9243-93461b37083c: moving to long term**********
2019-11-14T16:58:35.146503+00:00**********UUID ce8a1ed9-77f8-4c33-9243-93461b37083c: filter accuracy if needed**********
2019-11-14T16:58:35.207100+00:00**********UUID ce8a1ed9-77f8-4c33-9243-93461b37083c: segmenting into trips**********
2019-11-14T17:01:54.817363+00:00**********UUID ce8a1ed9-77f8-4c33-9243-93461b37083c: segmenting into sections**********
/usr/src/app/emission/analysis/intake/segmentation/section_segmentation_methods/flip_flop_detection.py:58: RuntimeWarning: invalid value encountered in double_scalars
  sm.update({"trip_pct": (curr_section_time * 100)/total_trip_time})
2019-11-14T17:02:17.253590+00:00**********UUID ce8a1ed9-77f8-4c33-9243-93461b37083c: smoothing sections**********
/opt/conda/envs/emission/lib/python3.6/site-packages/pandas/core/frame.py:891: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  "columns will be omitted.", UserWarning)
2019-11-14T17:02:27.635356+00:00**********UUID ce8a1ed9-77f8-4c33-9243-93461b37083c: cleaning and resampling timeline**********
2019-11-14T17:03:11.978222+00:00**********UUID ce8a1ed9-77f8-4c33-9243-93461b37083c: inferring transportation mode**********
unique_modes = ['BUS', 'SUBWAY'], but we support only two, [BUS, TRAIN]
Error while inferring modes, timestamp is unchanged
Traceback (most recent call last):
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 24, in predict_mode
    mip.runPredictionPipeline(user_id, time_query)
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 55, in runPredictionPipeline
    self.predictedProb = self.predictModesStep()
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 74, in predictModesStep
    predictedProb.append(get_prediction(i, section_entry))
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 113, in get_prediction
    return get_motorized_prediction(i, section_entry)
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 140, in get_motorized_prediction
    predicted_transit_mode = _get_transit_prediction(i, section_entry)
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 180, in _get_transit_prediction
    collapsed_transit_mode = collapse_modes(section_entry, predicted_transit_modes)
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 222, in collapse_modes
    assert False
AssertionError
2019-11-14T17:03:34.280117+00:00**********UUID ce8a1ed9-77f8-4c33-9243-93461b37083c: checking active mode trips to autocheck habits**********
2019-11-14T17:03:34.285702+00:00**********UUID ce8a1ed9-77f8-4c33-9243-93461b37083c: storing views to cache**********
```

**Comment by st-patrick** [comment]
sorry just read that's exactly what was described earlier. Setting assertions to false now...

**Comment by st-patrick** [comment]
It works! Not particularly correct but at least there are more modes now :) yay

**Comment by shankari** [comment]
You can look at the more detailed logs in `/var/tmp` or whatever you configured in `conf/log/intake.conf`. That will show you the kind of logs that I posted in https://github.com/e-mission/e-mission-docs/issues/468#issuecomment-553956062 and help you figure out why the GIS stuff doesn't work.

**Comment by shankari** [comment]
Fixed by https://github.com/e-mission/e-mission-server/pull/778
