### ISSUE TITLE
server pipeline crashes database regularly with only about 5 users

### ISSUE THREAD

**Issue by st-patrick** [e-mission/e-mission-docs#478]
Hello!

It seems every afternoon / evening, a little more data comes into the server because our testers are going home from work.

And almost every evening since the test started, the server crashes with an output that starts like this and then pretty much repeats the same exceptions over and over again until the database docker container finally crashes:

```
web-server_1  | Traceback (most recent call last):
web-server_1  |   File "/usr/src/app/emission/net/api/bottle.py", line 1012, in _handle
web-server_1  |     self.trigger_hook('after_request')
web-server_1  |   File "/usr/src/app/emission/net/api/bottle.py", line 706, in trigger_hook
web-server_1  |     return [hook(*args, **kwargs) for hook in self._hooks[__name][:]]
web-server_1  |   File "/usr/src/app/emission/net/api/bottle.py", line 706, in <listcomp>
web-server_1  |     return [hook(*args, **kwargs) for hook in self._hooks[__name][:]]
web-server_1  |   File "emission/net/api/cfc_webapp.py", line 437, in after_request
web-server_1  |     msTimeNow, duration)
web-server_1  |   File "/usr/src/app/emission/net/api/stats.py", line 13, in store_server_api_time
web-server_1  |     esds.store_server_api_time(user_id, call, ts, reading)
web-server_1  |   File "/usr/src/app/emission/storage/decorations/stats_queries.py", line 20, in store_server_api_time
web-server_1  |     store_stats_entry(user_id, "stats/server_api_time", call, ts, reading)
web-server_1  |   File "/usr/src/app/emission/storage/decorations/stats_queries.py", line 47, in store_stats_entry
web-server_1  |     return esta.TimeSeries.get_time_series(user_id).insert(new_entry)
web-server_1  |   File "/usr/src/app/emission/storage/timeseries/builtin_timeseries.py", line 350, in insert
web-server_1  |     ins_result = self.get_timeseries_db(entry.metadata.key).insert_one(entry)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/collection.py", line 667, in insert_one
web-server_1  |     with self._socket_for_writes() as sock_info:
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/contextlib.py", line 82, in __enter__
web-server_1  |     return next(self.gen)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/mongo_client.py", line 870, in _get_socket
web-server_1  |     with server.get_socket(self.__all_credentials) as sock_info:
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/contextlib.py", line 82, in __enter__
web-server_1  |     return next(self.gen)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/server.py", line 168, in get_socket
web-server_1  |     with self.pool.get_socket(all_credentials, checkout) as sock_info:
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/contextlib.py", line 82, in __enter__
web-server_1  |     return next(self.gen)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 850, in get_socket
web-server_1  |     sock_info = self._get_socket_no_auth()
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 890, in _get_socket_no_auth
web-server_1  |     sock_info = self._check(sock_info)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 942, in _check
web-server_1  |     return self.connect()
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 823, in connect
web-server_1  |     _raise_connection_failure(self.address, error)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 269, in _raise_connection_failure
web-server_1  |     raise AutoReconnect(msg)
web-server_1  | pymongo.errors.AutoReconnect: db:27017: [Errno 111] Connection refused
web-server_1  | Traceback (most recent call last):
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 803, in connect
web-server_1  |     sock = _configured_socket(self.address, self.opts)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 705, in _configured_socket
web-server_1  |     sock = _create_connection(address, options)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 689, in _create_connection
web-server_1  |     raise err
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 682, in _create_connection
web-server_1  |     sock.connect(sa)
web-server_1  | ConnectionRefusedError: [Errno 111] Connection refused
web-server_1  | 
web-server_1  | During handling of the above exception, another exception occurred:
web-server_1  | 
web-server_1  | Traceback (most recent call last):
web-server_1  |   File "/usr/src/app/emission/net/api/bottle.py", line 1012, in _handle
web-server_1  |     self.trigger_hook('after_request')
web-server_1  |   File "/usr/src/app/emission/net/api/bottle.py", line 706, in trigger_hook
web-server_1  |     return [hook(*args, **kwargs) for hook in self._hooks[__name][:]]
web-server_1  |   File "/usr/src/app/emission/net/api/bottle.py", line 706, in <listcomp>
web-server_1  |     return [hook(*args, **kwargs) for hook in self._hooks[__name][:]]
web-server_1  |   File "emission/net/api/cfc_webapp.py", line 437, in after_request
web-server_1  |     msTimeNow, duration)
web-server_1  |   File "/usr/src/app/emission/net/api/stats.py", line 13, in store_server_api_time
web-server_1  |     esds.store_server_api_time(user_id, call, ts, reading)
web-server_1  |   File "/usr/src/app/emission/storage/decorations/stats_queries.py", line 20, in store_server_api_time
web-server_1  |     store_stats_entry(user_id, "stats/server_api_time", call, ts, reading)
web-server_1  |   File "/usr/src/app/emission/storage/decorations/stats_queries.py", line 47, in store_stats_entry
web-server_1  |     return esta.TimeSeries.get_time_series(user_id).insert(new_entry)
web-server_1  |   File "/usr/src/app/emission/storage/timeseries/builtin_timeseries.py", line 350, in insert
web-server_1  |     ins_result = self.get_timeseries_db(entry.metadata.key).insert_one(entry)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/collection.py", line 667, in insert_one
web-server_1  |     with self._socket_for_writes() as sock_info:
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/contextlib.py", line 82, in __enter__
web-server_1  |     return next(self.gen)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/mongo_client.py", line 870, in _get_socket
web-server_1  |     with server.get_socket(self.__all_credentials) as sock_info:
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/contextlib.py", line 82, in __enter__
web-server_1  |     return next(self.gen)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/server.py", line 168, in get_socket
web-server_1  |     with self.pool.get_socket(all_credentials, checkout) as sock_info:
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/contextlib.py", line 82, in __enter__
web-server_1  |     return next(self.gen)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 850, in get_socket
web-server_1  |     sock_info = self._get_socket_no_auth()
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 890, in _get_socket_no_auth
web-server_1  |     sock_info = self._check(sock_info)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 942, in _check
web-server_1  |     return self.connect()
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 823, in connect
web-server_1  |     _raise_connection_failure(self.address, error)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 269, in _raise_connection_failure
web-server_1  |     raise AutoReconnect(msg)
web-server_1  | pymongo.errors.AutoReconnect: db:27017: [Errno 111] Connection refused
web-server_1  | Traceback (most recent call last):
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 803, in connect
web-server_1  |     sock = _configured_socket(self.address, self.opts)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 705, in _configured_socket
web-server_1  |     sock = _create_connection(address, options)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 689, in _create_connection
web-server_1  |     raise err
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 682, in _create_connection
web-server_1  |     sock.connect(sa)
web-server_1  | ConnectionRefusedError: [Errno 111] Connection refused
web-server_1  | 
web-server_1  | During handling of the above exception, another exception occurred:
web-server_1  | 
web-server_1  | Traceback (most recent call last):
web-server_1  |   File "/usr/src/app/emission/net/api/bottle.py", line 997, in _handle
web-server_1  |     out = route.call(**args)
web-server_1  |   File "/usr/src/app/emission/net/api/bottle.py", line 1998, in wrapper
web-server_1  |     rv = callback(*a, **ka)
web-server_1  |   File "emission/net/api/cfc_webapp.py", line 301, in summarize_metrics
web-server_1  |     user_uuid = getUUID(request)
web-server_1  |   File "emission/net/api/cfc_webapp.py", line 447, in getUUID
web-server_1  |     retUUID = enaa.getUUID(request, auth_method, inHeader)
web-server_1  |   File "/usr/src/app/emission/net/auth/auth.py", line 63, in getUUID
web-server_1  |     retUUID = getUUIDFromToken(authMethod, userToken)
web-server_1  |   File "/usr/src/app/emission/net/auth/auth.py", line 38, in getUUIDFromToken
web-server_1  |     return __getUUIDFromEmail__(userEmail)
web-server_1  |   File "/usr/src/app/emission/net/auth/auth.py", line 42, in __getUUIDFromEmail__
web-server_1  |     user=ecwu.User.fromEmail(userEmail)
web-server_1  |   File "/usr/src/app/emission/core/wrapper/user.py", line 37, in fromEmail
web-server_1  |     email2UUID = get_uuid_db().find_one({'user_email': userEmail})
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/collection.py", line 1109, in find_one
web-server_1  |     for result in cursor.limit(-1):
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/cursor.py", line 1132, in next
web-server_1  |     if len(self.__data) or self._refresh():
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/cursor.py", line 1055, in _refresh
web-server_1  |     self.__collation))
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/cursor.py", line 892, in __send_message
web-server_1  |     **kwargs)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/mongo_client.py", line 950, in _send_message_with_response
web-server_1  |     exhaust)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/mongo_client.py", line 961, in _reset_on_error
web-server_1  |     return func(*args, **kwargs)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/server.py", line 99, in send_message_with_response
web-server_1  |     with self.get_socket(all_credentials, exhaust) as sock_info:
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/contextlib.py", line 82, in __enter__
web-server_1  |     return next(self.gen)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/server.py", line 168, in get_socket
web-server_1  |     with self.pool.get_socket(all_credentials, checkout) as sock_info:
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/contextlib.py", line 82, in __enter__
web-server_1  |     return next(self.gen)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 850, in get_socket
web-server_1  |     sock_info = self._get_socket_no_auth()
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 890, in _get_socket_no_auth
web-server_1  |     sock_info = self._check(sock_info)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 942, in _check
web-server_1  |     return self.connect()
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 823, in connect
web-server_1  |     _raise_connection_failure(self.address, error)
web-server_1  |   File "/opt/conda/envs/emission/lib/python3.6/site-packages/pymongo/pool.py", line 269, in _raise_connection_failure
web-server_1  |     raise AutoReconnect(msg)
web-server_1  | pymongo.errors.AutoReconnect: db:27017: [Errno 111] Connection refused
web-server_1  | 
web-server_1  | During handling of the above exception, another exception occurred:

```

Has anyone encountered this before?
I just read through all the issues but couldn't find anything similar.

**Comment by st-patrick** [comment]
oh yes I realize that by the error message the DB probably crashes first (though not the docker container itself, that happens a little later).

Nevertheless, did anyone else encounter random crashes of the database container in the docker setup?

**Comment by shankari** [comment]
@st-patrick I set up a live demo of tripaware for Buildsys, and at least 5 of the students used it simultaneously to generate enough data for the demo. It is running on my home server, which is an old laptop running a lot of other services (e.g. nextcloud, mail server) as well.

And it is working fine.

Which OS are you running the docker containers on? I am running on linux.
What do you see the database logs?

**Comment by st-patrick** [comment]
it's a simple Ubuntu 18 container on digitalocean.
I'll check the db logs tomorrow, they'll probably reveal something.

I have a cronjob running every half hour, maybe it's not configured properly:
```
SHELL=/bin/bash
BASH_ENV="/root/.bashrc"
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/snap/bin

*/30 * * * * /bin/bash -c ". ~/.bashrc; docker exec -t docker_web-server_1 /bin/bash /usr/src/app/cron_intake.sh &>> intakedocker-crontest.txt"
```

**Comment by shankari** [comment]
@st-patrick since docker is really intended for use with microservices, I set up a separate container to run the analysis scripts (similar to the architecture of the multi layer stack). I don't think that docker-compose is in the examples yet but if people ask for it, I can check it in 😄 

For the next week or so, I only check in code when people ask for it..

**Comment by shankari** [comment]
> I have a cronjob running every half hour, maybe it's not configured properly:

If the DB only crashes in the evening, but you have the cronjob running every half hour, then I doubt they are related.

**Comment by st-patrick** [comment]
I'm pretty sure it was RAM related. The server was unresponsive again, especially when trying to run e.g. docker ps

I then checked processes with "top" and the swap process was very active and RAM was down to only 50 free MB.

I now upgraded our droplet to 4GB RAM so hopefully that'll resolve this.

**Comment by shankari** [comment]
Closing this due to lack of updates, please reopen if it recurs.
