### ISSUE TITLE
on gis based branch: "Error while inferring modes, timestamp is unchanged"

### ISSUE THREAD

**Issue by st-patrick** [e-mission/e-mission-docs#484]
Hey I get this error which I found an older issue to but the older issue was related to the previous pipeline model.

Also, for some days now, the app shows "invalid date" instead of the actual start and end time of the trip which I assume is connected to this.

I didn't make any changes to the code. though. Here's the full error output:

```
2019-12-19T10:39:47.509997+00:00**********UUID ff5962e2-4264-4bbf-8d10-afa0de017f72: smoothing sections**********
/opt/conda/envs/emission/lib/python3.6/site-packages/pandas/core/frame.py:891: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  "columns will be omitted.", UserWarning)
2019-12-19T10:39:50.885170+00:00**********UUID ff5962e2-4264-4bbf-8d10-afa0de017f72: cleaning and resampling timeline**********
2019-12-19T10:39:50.898433+00:00**********UUID 5f081c47-0701-4c88-b734-e99d76f9610f: smoothing sections**********
/opt/conda/envs/emission/lib/python3.6/site-packages/pandas/core/frame.py:891: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  "columns will be omitted.", UserWarning)
2019-12-19T10:39:55.933676+00:00**********UUID 5f081c47-0701-4c88-b734-e99d76f9610f: cleaning and resampling timeline**********
unique_modes = ['BUS', 'SUBWAY'], but we support only two, [BUS, TRAIN]
Error while inferring modes, timestamp is unchanged
Traceback (most recent call last):
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 24, in predict_mode
    mip.runPredictionPipeline(user_id, time_query)
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 55, in runPredictionPipeline
    self.predictedProb = self.predictModesStep()
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 74, in predictModesStep
    predictedProb.append(get_prediction(i, section_entry))
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 113, in get_prediction
    return get_motorized_prediction(i, section_entry)
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 140, in get_motorized_prediction
    predicted_transit_mode = _get_transit_prediction(i, section_entry)
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 180, in _get_transit_prediction
    collapsed_transit_mode = collapse_modes(section_entry, predicted_transit_modes)
  File "/usr/src/app/emission/analysis/classification/inference/mode/rule_engine.py", line 222, in collapse_modes
    assert False
AssertionError
```

another error in that same run of the pipeline is 
```
2019-12-19T10:42:28.543894+00:00**********UUID 5f442e2d-fc45-4032-a187-f3f859781b9f: segmenting into sections**********
/usr/src/app/emission/analysis/intake/segmentation/section_segmentation_methods/flip_flop_detection.py:58: RuntimeWarning: invalid value encountered in double_scalars
  sm.update({"trip_pct": (curr_section_time * 100)/total_trip_time})
```

and also errors like 
```
2019-12-19T10:44:31.918365+00:00**********UUID ce8a1ed9-77f8-4c33-9243-93461b37083c: moving to long term**********
Got error 'AttrDict' instance has no attribute 'currState' while saving entry AttrDict({'_id': ObjectId('5df7bda107dc9bae21c2c3a8'), 'metadata': {'key': 'statemachine/transition', 'platform': 'android', 'read_ts': 0, 'time_zone': 'Europe/Berlin', 'type': 'message', 'write_ts': 1576517023.851}, 'user_id': UUID('ce8a1ed9-77f8-4c33-9243-93461b37083c'), 'data': {'curr_state': 'local.state.waiting_for_trip_start', 'transition': 'local.transition.exited_geofence', 'ts': 1576517023}}) -> None
Got error 'AttrDict' instance has no attribute 'currState' while saving entry AttrDict({'_id': ObjectId('5df7bda107dc9bae21c2c3aa'), 'metadata': {'key': 'statemachine/transition', 'platform': 'android', 'read_ts': 0, 'time_zone': 'Europe/Berlin', 'type': 'message', 'write_ts': 1576517023.87}, 'user_id': UUID('ce8a1ed9-77f8-4c33-9243-93461b37083c'), 'data': {'curr_state': 'local.state.ongoing_trip', 'transition': 'local.transition.stopped_moving', 'ts': 1576517023}}) -> None
2019-12-19T10:44:32.730511+00:00**********UUID ce8a1ed9-77f8-4c33-9243-93461b37083c: filter accuracy if needed**********
```

could it be that the underlying data is corrupted somehow? It seems that with every run of the pipeline, more errors show up and I definitely didn't change any of the code in production.

**Comment by st-patrick** [comment]
actually I think the database had been compromised.

I had added another volume to the db container in docker-compose.yml
For whatever reason that caused docker to delete the existing containers and just create new ones from base image.
So all our changes were lost and only what persisted in the mounted volume of db was still available but then I ran the pipeline from master on that data and it seems that messed it up with entropy.

From that point, I wasn't able to get the data back and had to restore a backup

**Comment by st-patrick** [comment]
Though we did already have the timestamp error when everything was working fine.
One day, all the dates just turned into "invalid date" without me changing any server code.

**Comment by st-patrick** [comment]
ah gee, it's the same error we had before. It's just that I commited some changes to the server and checked those out, so it deleted all the conf files, since they're not added to git.

To quote mysel:

> Quick guide for anyone: before switching to gis-branch, reset the data from the pipeline with the reset script. Then, checkout the gis-branch. Following, copy all the new/modified sample files to the filename without ".sample":
conf/net/ext_service/overpass_server.json
conf/net/ext_service/overpass_transit_stops_query_template
conf/analysis/debug.conf.json
Then, run the pipeline again

also, set pretty much all assertions to false, here's our version of conf/analysis/debug.conf.json:
```
{
    "intake.segmentation.section_segmentation.sectionValidityAssertions": false,
    "intake.cleaning.clean_and_resample.speedDistanceAssertions": false,
    "intake.cleaning.clean_and_resample.sectionValidityAssertions": false,
    "intake.cleaning.filter_accuracy.enable": false,
    "classification.inference.mode.useAdvancedFeatureIndices": true,
    "classification.inference.mode.useBusTrainFeatureIndices": true,
    "classification.validityAssertions": false,
    "output.conversion.validityAssertions": false,
    "section.startStopRadius": 150,
    "section.endStopRadius": 150,
    "analysis.result.section.key": "analysis/inferred_section"
}
```

**Comment by shankari** [comment]
Glad to see that you figured it out 😄
