### ISSUE TITLE
AssertionError 'DataFrame' object has no attribute 'as_matrix'

### ISSUE THREAD

**Issue by xubowenhaoren** [e-mission/e-mission-docs#497]
Hi, 

After I deployed the example docker, I ran into issues when running the test data. I ran the input pipeline from the instructions [here](https://github.com/xubowenhaoren/e-mission-server#quick-start). My own steps are [here](https://github.com/xubowenhaoren/emission-docker-setup/blob/master/setup.md). After running the last step, I encountered the following errors: 

```
Connecting to database URL db
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
2020-02-03T08:05:28.659652+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: moving to long term**********
2020-02-03T08:05:28.710449+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: filter accuracy if needed**********
2020-02-03T08:05:28.745694+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: segmenting into trips**********
Found error curr_state.curr_run_ts = 1580716227.1752121 while processing pipeline for user ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf, skipping
Traceback (most recent call last):
  File "/usr/src/app/emission/pipeline/intake_stage.py", line 72, in run_intake_pipeline
    run_intake_pipeline_for_user(uuid)
  File "/usr/src/app/emission/pipeline/intake_stage.py", line 114, in run_intake_pipeline_for_user
    eaist.segment_current_trips(uuid)
  File "/usr/src/app/emission/analysis/intake/segmentation/trip_segmentation.py", line 52, in segment_current_trips
    time_query = epq.get_time_range_for_segmentation(user_id)
  File "/usr/src/app/emission/storage/pipeline_queries.py", line 42, in get_time_range_for_segmentation
    return get_time_range_for_stage(user_id, ps.PipelineStages.TRIP_SEGMENTATION)
  File "/usr/src/app/emission/storage/pipeline_queries.py", line 234, in get_time_range_for_stage
    assert curr_state.curr_run_ts is None, "curr_state.curr_run_ts = %s" % curr_state.curr_run_ts
AssertionError: curr_state.curr_run_ts = 1580716227.1752121
```
How can I fix this?

**Comment by shankari** [comment]
@xubowenhaoren  did you check the docs?
https://github.com/e-mission/e-mission-docs/search?q=curr_state.curr_run_ts&unscoped_q=curr_state.curr_run_ts

**Comment by xubowenhaoren** [comment]
Thank you for the input! After I manually reset the pipeline, it appears that I am still having `AssertionError`, albeit a different one this time: 

```
Connecting to database URL db
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
2020-02-03T17:46:51.791645+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: moving to long term**********
2020-02-03T17:46:51.807078+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: filter accuracy if needed**********
2020-02-03T17:46:51.814975+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: segmenting into trips**********
Found error 'DataFrame' object has no attribute 'as_matrix' while processing pipeline for user ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf, skipping
Traceback (most recent call last):
  File "/usr/src/app/emission/pipeline/intake_stage.py", line 72, in run_intake_pipeline
    run_intake_pipeline_for_user(uuid)
  File "/usr/src/app/emission/pipeline/intake_stage.py", line 114, in run_intake_pipeline_for_user
    eaist.segment_current_trips(uuid)
  File "/usr/src/app/emission/analysis/intake/segmentation/trip_segmentation.py", line 95, in segment_current_trips
    time_query)
  File "/usr/src/app/emission/analysis/intake/segmentation/trip_segmentation_methods/dwell_segmentation_time_filter.py", line 119, in segment_into_trips
    logging.debug("last5MinsDistances = %s with length %d" % (last5MinsDistances.as_matrix(), len(last5MinsDistances)))
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 5273, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'
```
I realized that in my previous steps, I had mistakenly used your habitica example json file without checking the content. Now I changed the url to be
```
{
        "url": "https://habitica.com"
}
```
However, the problem above persists. Should I open another issue for this?

**Comment by shankari** [comment]
This is not an error with habitica.
It is an error with the trip segmentation step, in which it looks like `as_matrix()` is not defined in the pandas dataframe object.
Nobody else has reported this, so it is almost certainly due to an incompatible/incorrect version of pandas.
Are you sure you installed the environment using the correct environment file? What is your version of pandas that you are running this against?

**Comment by shankari** [comment]
I just looked at your steps and you are reinstalling pandas manually using pip.
This will give you the most recent version of pandas which does not have `as_matrix`. You need to use the exact same version of pandas that is defined in the environment file.
https://github.com/xubowenhaoren/emission-docker-setup/blob/master/setup.md#log-in

**Comment by xubowenhaoren** [comment]
I had to install those dependencies, or I could not run the test script in the first place. Now I realized that `conda` and `pip` have different package managers, I need to check the conda configuration.

**Comment by xubowenhaoren** [comment]
Log when I re-deploy the docker image: 
```
WARNING: Some services (db, web-server) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Creating juypter-notebook_db_1 ... done
Creating juypter-notebook_web-server_1 ... done
Attaching to juypter-notebook_db_1, juypter-notebook_web-server_1
db_1          | 2020-02-03T18:59:44.371+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=3ea5ca5fccd7
db_1          | 2020-02-03T18:59:44.371+0000 I CONTROL  [initandlisten] db version v3.4.24
db_1          | 2020-02-03T18:59:44.371+0000 I CONTROL  [initandlisten] git version: 865b4f6a96d0f5425e39a18337105f33e8db504d
db_1          | 2020-02-03T18:59:44.371+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
db_1          | 2020-02-03T18:59:44.371+0000 I CONTROL  [initandlisten] allocator: tcmalloc
db_1          | 2020-02-03T18:59:44.371+0000 I CONTROL  [initandlisten] modules: none
db_1          | 2020-02-03T18:59:44.371+0000 I CONTROL  [initandlisten] build environment:
db_1          | 2020-02-03T18:59:44.371+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
db_1          | 2020-02-03T18:59:44.371+0000 I CONTROL  [initandlisten]     distarch: x86_64
db_1          | 2020-02-03T18:59:44.371+0000 I CONTROL  [initandlisten]     target_arch: x86_64
db_1          | 2020-02-03T18:59:44.371+0000 I CONTROL  [initandlisten] options: {}
db_1          | 2020-02-03T18:59:44.371+0000 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
db_1          | 2020-02-03T18:59:44.379+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
db_1          | 2020-02-03T18:59:44.379+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
db_1          | 2020-02-03T18:59:44.379+0000 I STORAGE  [initandlisten] 
db_1          | 2020-02-03T18:59:44.379+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
db_1          | 2020-02-03T18:59:44.379+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
db_1          | 2020-02-03T18:59:44.379+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=332M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
db_1          | 2020-02-03T18:59:44.869+0000 I STORAGE  [initandlisten] WiredTiger message [1580756384:869496][1:0x7f9c9b5b9d40], txn-recover: Main recovery loop: starting at 2/1347072
db_1          | 2020-02-03T18:59:44.871+0000 I STORAGE  [initandlisten] WiredTiger message [1580756384:871922][1:0x7f9c9b5b9d40], txn-recover: Recovering log 2 through 3
web-server_1  | DB host = db
db_1          | 2020-02-03T18:59:45.022+0000 I STORAGE  [initandlisten] WiredTiger message [1580756385:22839][1:0x7f9c9b5b9d40], txn-recover: Recovering log 3 through 3
web-server_1  | {
web-server_1  |     "timeseries": {
web-server_1  |         "url": "db"
web-server_1  |     }
web-server_1  | }
web-server_1  | Web host = 0.0.0.0
db_1          | 2020-02-03T18:59:45.308+0000 I CONTROL  [initandlisten] 
db_1          | 2020-02-03T18:59:45.309+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
db_1          | 2020-02-03T18:59:45.309+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
db_1          | 2020-02-03T18:59:45.310+0000 I CONTROL  [initandlisten] 
db_1          | 2020-02-03T18:59:45.315+0000 W INDEX    [initandlisten] Sparse option ignored for index spec { data.start_loc: "2dsphere" }
db_1          | 2020-02-03T18:59:45.316+0000 W INDEX    [initandlisten] Sparse option ignored for index spec { data.end_loc: "2dsphere" }
db_1          | 2020-02-03T18:59:45.328+0000 W INDEX    [initandlisten] Sparse option ignored for index spec { data.location: "2dsphere" }
db_1          | 2020-02-03T18:59:45.331+0000 W INDEX    [initandlisten] Sparse option ignored for index spec { data.loc: "2dsphere" }
db_1          | 2020-02-03T18:59:45.337+0000 W INDEX    [initandlisten] Sparse option ignored for index spec { data.loc: "2dsphere" }
db_1          | 2020-02-03T18:59:45.342+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
db_1          | 2020-02-03T18:59:45.343+0000 I NETWORK  [thread1] waiting for connections on port 27017
db_1          | 2020-02-03T18:59:46.029+0000 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
web-server_1  | [I 18:59:46.320 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
web-server_1  | [I 18:59:46.696 NotebookApp] Serving notebooks from local directory: /usr/src/app
web-server_1  | [I 18:59:46.697 NotebookApp] The Jupyter Notebook is running at:
web-server_1  | [I 18:59:46.698 NotebookApp] http://d94a6eeaa056:8888/?token=77649c370b6ceebbd95b92d0f97f940ee7e7feaae3d188ed
web-server_1  | [I 18:59:46.698 NotebookApp]  or http://127.0.0.1:8888/?token=77649c370b6ceebbd95b92d0f97f940ee7e7feaae3d188ed
web-server_1  | [I 18:59:46.698 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
web-server_1  | [C 18:59:46.707 NotebookApp] 
web-server_1  |     
web-server_1  |     To access the notebook, open this file in a browser:
web-server_1  |         file:///root/.local/share/jupyter/runtime/nbserver-13-open.html
web-server_1  |     Or copy and paste one of these URLs:
web-server_1  |         http://d94a6eeaa056:8888/?token=77649c370b6ceebbd95b92d0f97f940ee7e7feaae3d188ed
web-server_1  |      or http://127.0.0.1:8888/?token=77649c370b6ceebbd95b92d0f97f940ee7e7feaae3d188ed
```

**Comment by xubowenhaoren** [comment]
Now, after logging into the docker container and running the test data import, I get

```
./e-mission-py.bash bin/debug/load_timeline_for_day_and_user.py emission/tests/data/real_examples/shankari_2015-07-22 test_july_22
Traceback (most recent call last):
  File "bin/debug/load_timeline_for_day_and_user.py", line 5, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'
```

**Comment by shankari** [comment]
Please check the issues - e.g.
https://github.com/e-mission/e-mission-docs/issues/380#issuecomment-483727971
https://github.com/e-mission/e-mission-docs/issues/327

I will also point out that the issue of running scripts has been addressed in the README
https://github.com/e-mission/e-mission-docker/#using-scripts

Also, I said that the server will be running. What I meant was 
https://github.com/e-mission/e-mission-docker/#connecting-to-the-created-container

**Comment by xubowenhaoren** [comment]
After running `source activate emission`:
```
Connecting to database URL db
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/usr/src/app/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
2020-02-03T19:13:41.801429+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: moving to long term**********
2020-02-03T19:13:41.822955+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: filter accuracy if needed**********
2020-02-03T19:13:41.833058+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: segmenting into trips**********
/usr/src/app/emission/analysis/intake/segmentation/trip_segmentation_methods/dwell_segmentation_time_filter.py:119: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  logging.debug("last5MinsDistances = %s with length %d" % (last5MinsDistances.as_matrix(), len(last5MinsDistances)))
/usr/src/app/emission/analysis/intake/segmentation/trip_segmentation_methods/dwell_segmentation_time_filter.py:121: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  logging.debug("last10PointsDistances = %s with length %d, shape %s" % (last10PointsDistances.as_matrix(),
2020-02-03T19:13:55.398590+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: segmenting into sections**********
/opt/conda/envs/emission/lib/python3.6/site-packages/numpy/core/fromnumeric.py:52: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)
2020-02-03T19:13:56.808712+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: smoothing sections**********
/usr/src/app/emission/analysis/intake/cleaning/cleaning_methods/jump_smoothing.py:113: FutureWarning: 
The current behaviour of 'Series.argmin' is deprecated, use 'idxmin'
instead.
The behavior of 'argmin' will be corrected to return the positional
minimum in the future. For now, use 'series.values.argmin' or
'np.argmin(np.array(values))' to get the position of the minimum
row.
  retVal = non_cluster_segments.distance.argmin()
/usr/src/app/emission/analysis/intake/cleaning/location_smoothing.py:55: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  point_list = [ad.AttrDict(row) for row in points_df.to_dict('records')]
2020-02-03T19:13:58.336450+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: cleaning and resampling timeline**********
2020-02-03T19:14:01.740121+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: inferring transportation mode**********
Error while inferring modes, timestamp is unchanged
Traceback (most recent call last):
  File "/usr/src/app/emission/analysis/classification/inference/mode/pipeline.py", line 41, in predict_mode
    mip.runPredictionPipeline(user_id, time_query)
  File "/usr/src/app/emission/analysis/classification/inference/mode/pipeline.py", line 136, in runPredictionPipeline
    self.loadModelStage()
  File "/usr/src/app/emission/analysis/classification/inference/mode/pipeline.py", line 153, in loadModelStage
    self.model = seedp.ModeInferencePipelineMovesFormat.loadModel()
  File "/usr/src/app/emission/analysis/classification/inference/mode/seed/pipeline.py", line 93, in loadModel
    fd = open(SAVED_MODEL_FILENAME, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'seed_model.json'
2020-02-03T19:14:01.884653+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: checking active mode trips to autocheck habits**********
2020-02-03T19:14:01.887874+00:00**********UUID ec7b0d9f-cbff-4145-915f-b29c8dfa6eaf: storing views to cache**********
```

**Comment by xubowenhaoren** [comment]
In [issue 303](https://github.com/e-mission/e-mission-docs/issues/303), you mentioned two approaches for the `seed_model.json`. I am wondering which approach has a better/more mode detection?

**Comment by shankari** [comment]
@xubowenhaoren I have not actually run the two pipelines side by side, although I can now do so with the public dataset. However, most other deployers have found that the GIS-based version is better. It certainly supports more modes, distinguishing between train, subway, light rail etc.

**Comment by shankari** [comment]
Closing this since it has been addressed before. If the instructions to run scripts don't work, please re-open
