### ISSUE TITLE
an ERROR when calling the /timeline/getTrips API

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#682]
when calling the getTrips API as we send the user's data to his/her personal cloud,
we have encountered one error for one user, only once for the moment so maybe it's a corner case .
Here is the log
`2021-11-04 05:17:26,458:ERROR:139904398915328:Found error Found len(ret_list) = 18, expected <=1 while processing trip Entry({'_id': ObjectId('61087f0d27c623eef55c24c8'), 'user_id': UUID('e846e4c8-4d19-4add-b4d6-e3534c1df345'), 'metadata': {'key': 'analysis/cleaned_trip', 'platform': 'server', 'write_ts': 1627946765.3298173, 'time_zone': 'America/Los_Angeles', 'write_local_dt': {'year': 2021, 'month': 8, 'day': 2, 'hour': 16, 'minute': 26, 'second': 5, 'weekday': 0, 'timezone': 'America/Los_Angeles'}, 'write_fmt_time': '2021-08-02T16:26:05.329817-07:00'}, 'data': {'source': 'DwellSegmentationTimeFilter', 'end_ts': 1627886571.664, 'end_local_dt': {'year': 2021, 'month': 8, 'day': 2, 'hour': 8, 'minute': 42, 'second': 51, 'weekday': 0, 'timezone': 'Europe/Paris'}, 'end_fmt_time': '2021-08-02T08:42:51.664000+02:00', 'end_loc': {'type': 'Point', 'coordinates': [-1.9479954, 46.697848]}, 'raw_trip': ObjectId('61087f0a27c623eef55c2495'), 'start_ts': 1627886227.821, 'start_local_dt': {'year': 2021, 'month': 8, 'day': 2, 'hour': 8, 'minute': 37, 'second': 7, 'weekday': 0, 'timezone': 'Europe/Paris'}, 'start_fmt_time': '2021-08-02T08:37:07.821000+02:00', 'start_loc': {'type': 'Point', 'coordinates': [-1.9430402, 46.6970667]}, 'duration': 343.84299993515015, 'distance': 423.99537603083024, 'start_place': ObjectId('61087f0f27c623eef55c28d3'), 'end_place': ObjectId('61087f1127c623eef55c28d4')}})`

The error occurs just after this line in the log file
`2021-11-04 16:06:14,275:DEBUG:139904356951808:About to query {'metadata.key': 'analysis/inferred_section', 'user_id': UUID('e846e4c8-4
d19-4add-b4d6-e3534c1df345'), 'data.cleaned_section': ObjectId('61087f0d27c623eef55c24c9')}`
and terminates the query
'2021-11-04 16:06:14,376:DEBUG:139904356951808:END POST /timeline/getTrips/2021-08-02 e846e4c8-4d19-4add-b4d6-e3534c1df345 0.2319681644
4396973'
This results a 500 Error for the API user.

The error log comes from this method:
https://github.com/e-mission/e-mission-server/blob/2177582fdea9a52faa8c1a238e62b111dbbcedba/emission/storage/decorations/section_queries.py#L48

Maybe we can safely ignore the assert line and return None for the moment ? 
assert len(ret_list) <= 1, "Found len(ret_list) = %d, expected <=1" % len(ret_list)

Thanks for your help.

**Comment by shankari** [comment]
@PatGendre that is a weird assert to trigger. As you can see from the code around it

```
    ret_list = list(edb.get_analysis_timeseries_db().find(combo_query))
    # We currently have only one algorithm
    assert len(ret_list) <= 1, "Found len(ret_list) = %d, expected <=1" % len(ret_list)
    if len(ret_list) == 0:
        logging.debug("Found no inferred prediction, returning None")
        return None
```

We expect to have a 1:1 correspondence between cleaned and inferred sections. From the log, it looks like this user has 18 inferred sections for cleaned section with id `61087f0d27c623eef55c24c9`. Is this actually the case?

Why did we keep generating inferred sections after the first one was generated? Was there an issue with the inference step of the pipeline?

**Comment by PatGendre** [comment]
Hi @shankari 
Thanks!

> From the log, it looks like this user has 18 inferred sections for cleaned section with id 61087f0d27c623eef55c24c9. Is this actually the case?

Yes there are 18 inferred sections attached to this cleaned section in the database.
The 18 sections are exact clones (except for the object id of course) so maybe I can keep the first section and delete the 17 others.
It would be interesting to understand why the 18 copies were created but as we don't encounter the issue with other data it is not really essential in practice.

**Comment by PatGendre** [comment]
FYI I have deleted by hand the 17 "clones" of the inferred section, which solves our API call issue.
Nevertheless this does not explain we had 18 copies of the section in the inference step... I can look in the pipeline log if you want.

**Comment by shankari** [comment]
Yes, would be great to look in the pipeline log and figure it out. I have never seen this issue before! 😄

**Comment by PatGendre** [comment]
I looked for the cleaned section objectid in the pipeline log files, and only the first inferred section appears, I attach the log extract but it seems all right.
So the 17 other inferred sections have been created later in the database, I have no idea when...
[0308section.log](https://github.com/e-mission/e-mission-docs/files/7487973/0308section.log)

**Comment by PatGendre** [comment]
@shankari 
update : actually every day after, for at least 17 days,
[aug21sections.log](https://github.com/e-mission/e-mission-docs/files/7488276/aug21sections.log)
 the pipeline processed again the same section (but leaving the same WALKING predicted mode), I attach the extract of the logs related to this cleaned section

**Comment by shankari** [comment]
@PatGendre that is very weird. Are there other errors in the inference step of the pipeline for this user? The only code path I can see for this to happen is that in `runPredictionPipeline`:
- we map the cleaned section to an inferred section with mode `WALKING` (this is the log `Updating sensed mode for section = 61087f0d27c623eef55c24c9 to PredictedModeTypes.WALKING`)
- we then iterate over all the inferred sections, saving each one. we save this inferred section (this is the log `Inserting entry Entry.*inferred_section`)
- but **there is an error while saving a subsequent section**
- so `runPredictionPipeline` errors out, and we go into the catch clause

```
    except:
        logging.exception("Error while inferring modes, timestamp is unchanged")
        epq.mark_mode_inference_failed(user_id)
```

So we don't update the timestamp, and we try to run the inference step again and again for the same set of trips, which results in multiple copies of this inferred trip.

We have not run into this before because we have not partial failures of the save step. Before this issue, I have only seen issues where there's something wrong with the database, in which case all saves fail.

**Comment by PatGendre** [comment]
> Are there other errors in the inference step of the pipeline for this user?

@shankari no, no errors for this user nor for other users.   
I grepped "ret_list" (from the error message) and the only occurrence in the pipeline log is for that particular section. So maybe is it an "erratic" error due to some obscure reason and not worth investigating ?

**Comment by PatGendre** [comment]
@shankari FYI I've found some (rare) errors "Found len(ret_list) = 2" in recent logs, but only a few for each day

**Comment by shankari** [comment]
@PatGendre the error will not necessarily have `ret_list` in the text. Instead, you want to find the original multiple successful insert (`Inserting entry Entry.*inferred_section`) and then just manually scroll further in the logs and see if there is an error between the insert and the subsequent end of the stage (`For stage PipelineStages.MODE_INFERENCE, last_ts_processed is...`)

**Comment by PatGendre** [comment]
@shankari 
I don't if this is what you're looking for but short after the insertion of the cleaned section
there is this ERROR
`2021-08-03 01:26:51,564:DEBUG:139740539369280:Updating sensed mode for section = 61087f0d27c623eef55c24c9 to PredictedModeTypes.WALKING
2021-08-03 01:26:51,565:DEBUG:139740539369280:insert called with entry of type <class 'emission.core.wrapper.entry.Entry'>
2021-08-03 01:26:51,565:DEBUG:139740539369280:entry was fine, no need to fix it
2021-08-03 01:26:51,565:DEBUG:139740539369280:Inserting entry Entry({'user_id': UUID('e846e4c8-4d19-4add-b4d6-e3534c1df345'), 'metadata': {'key': 'analysis/inferred_section', 'platform': 'server', 'write_ts': 1627946765.4916646, 'time_zone': 'America/Los_Angeles', 'write_local_dt': {'year': 2021, 'month': 8, 'day': 2, 'hour': 16, 'minute': 26, 'second': 5, 'weekday': 0, 'timezone': 'America/Los_Angeles'}, 'write_fmt_time': '2021-08-02T16:26:05.491665-07:00'}, 'data': {'source': 'SmoothedHighConfidenceMotion', 'trip_id': ObjectId('61087f0d27c623eef55c24c8'), 'start_ts': 1627886227.821, 'start_local_dt': {'year': 2021, 'month': 8, 'day': 2, 'hour': 8, 'minute': 37, 'second': 7, 'weekday': 0, 'timezone': 'Europe/Paris'}, 'start_fmt_time': '2021-08-02T08:37:07.821000+02:00', 'start_loc': {'type': 'Point', 'coordinates': [-1.9430402, 46.6970667]}, 'end_ts': 1627886571.664, 'end_local_dt': {'year': 2021, 'month': 8, 'day': 2, 'hour': 8, 'minute': 42, 'second': 51, 'weekday': 0, 'timezone': 'Europe/Paris'}, 'end_fmt_time': '2021-08-02T08:42:51.664000+02:00', 'end_loc': {'type': 'Point', 'coordinates': [-1.9479954, 46.697848]}, 'duration': 343.84299993515015, 'speeds': [0.0, 1.5887037629549343, 1.4984820888746386, 1.4334734564117815, 1.9362143821543643, 0.24306796385686152, 0.07052745718066492, 2.7624436511507082, 2.897315448514442, 1.1985518952151673, 0.36329475583056065, 0.019225472116569976, 0.2641310424140932], 'distances': [0.0, 47.66111288864803, 44.95446266623916, 43.00420369235344, 58.08643146463093, 7.292038915705846, 2.1158237154199475, 82.87330953452124, 86.91946345543326, 35.956556856455016, 10.89884267491682, 0.5767641634970992, 3.6563660030094325], 'distance': 423.99537603083024, 'sensed_mode': 1, 'cleaned_section': ObjectId('61087f0d27c623eef55c24c9')}}) into timeseries
2021-08-03 01:26:51,569:DEBUG:139740539369280:insert_data called
2021-08-03 01:26:51,571:DEBUG:139740539369280:insert called with entry of type <class 'emission.core.wrapper.entry.Entry'>
2021-08-03 01:26:51,571:DEBUG:139740539369280:entry was fine, no need to fix it
2021-08-03 01:26:51,571:DEBUG:139740539369280:Inserting entry Entry({'_id': ObjectId('61087f3b27c623eef55c28e1'), 'user_id': UUID('e846e4c8-4d19-4add-b4d6-e3534c1df345'), 'metadata': Metadata({'key': 'inference/prediction', 'platform': 'server', 'write_ts': 1627946811.5698526, 'time_zone': 'America/Los_Angeles', 'write_local_dt': LocalDate({'year': 2021, 'month': 8, 'day': 2, 'hour': 16, 'minute': 26, 'second': 51, 'weekday': 0, 'timezone': 'America/Los_Angeles'}), 'write_fmt_time': '2021-08-02T16:26:51.569853-07:00'}), 'data': Modeprediction({'trip_id': ObjectId('61087f0d27c623eef55c24d7'), 'section_id': ObjectId('61087f0d27c623eef55c24d9'), 'algorithm_id': 2, 'predicted_mode_map': {'FERRY': 1}, 'start_ts': 1627887735.6210597, 'end_ts': 1627891518.0})}) into timeseries
2021-08-03 01:26:51,574:DEBUG:139740539369280:max confidence in prediction map = 1
2021-08-03 01:26:51,574:DEBUG:139740539369280:max keys in prediction map = ['FERRY']
2021-08-03 01:26:51,574:ERROR:139740539369280:Error while inferring modes, timestamp is unchanged
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 24, in predict_mode
    mip.runPredictionPipeline(user_id, time_query)
  File "/var/emission/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 57, in runPredictionPipeline
    self.savePredictionsStep()
  File "/var/emission/e-mission-server/emission/analysis/classification/inference/mode/rule_engine.py", line 99, in savePredictionsStep
    is_dict["data"]["sensed_mode"] = ecwm.PredictedModeTypes[easf.select_inferred_mode([mp])].value
  File "/vat/opt/miniconda3/envs/emission/lib/python3.7/enum.py", line 357, in __getitem__
    return cls._member_map_[name]
KeyError: 'FERRY'
`

There are 2 similar errors in the log, one for FERRY, the other for TROLLEYBUS.
I could not find where these Ferry and Trolleybus modes come from ...

**Comment by shankari** [comment]
@PatGendre that is probably it. The FERRY and TROLLEYBUS modes are probably coming from OpenStreetMap. Is the start and end of the section near FERRY terminals? 

If so, we need to decide how to handle such unexpected modes 😄

**Comment by PatGendre** [comment]
@shankari yes the modes certainly come from OSM :-) I didn't think about this! 

The test in la Rochelle, a port on the Atlantic, so there are ferries there. And right, the start loc of the section is the ferry quay of the Yeu island, not too far from la Rochelle :-)
And the project manager lives in Lyon, where there are trolleybuses ;-) (and strange that we did not notice this trolleybus error before)

The quickest answer would be to add 'FERRY' and 'TROLLEYBUS' to the supported_modes list, maybe ?
https://github.com/e-mission/e-mission-server/blob/c4ccff36dd4f42c525c8945068604c6e0c1d1bbc/emission/analysis/classification/inference/mode/rule_engine.py#L219

**Comment by shankari** [comment]
Either that, or disable the classification validity assertions.

**Comment by shankari** [comment]
I don't think we have icons defined for those modes in the UI though

**Comment by PatGendre** [comment]
> I don't think we have icons defined for those modes
good point! For trolley we can stick to BUS, but for the ferry we'd better have an icon... but this means updating the UI, not only the server...

**Comment by shankari** [comment]
> but this means updating the UI, not only the server...

Yup. Note that you will also need to update the carbon footprint calculations in that case.

**Comment by shankari** [comment]
I can change the code to handle the currently unhandled modes "better" if we can define what better is 😄 

One option might be to mark the mode as `UNKNOWN`, another might be to keep it as "FERRY" but then the phone app needs to be updated with icons as well.

As part of modifying the dashboard to handle the user labels, I handle footprint calculations for modes that we don't know the footprint for. It will just show a range (low - high).

Thoughts?

**Comment by PatGendre** [comment]
There is TROLLEYBUS as a mode tagged by OSM, which raises a KeyError.
And if we want to change code in a robust way, we'd have to handle possibly CABLECAR or any other more "exotic" transport mode.
When I grep KeyError in all the pipeline error logs, I also find PROPOSED.
(and also 'type' and 'userinput.keylist' but those keyErrors don't concern the mode I guess)

In practice my thoughts would be 
- maybe even before changing the code, to document how to handle a new mode, either detected by the pipeline or entered by the user, I suppose we have to modify the mode list, the icon (for the app UI), the CO2/Calories calculation, the pipeline analysis stage, at least
- for TROLLEYBUS, I would detect it as BUS (anyway for the CO2 calculation, the figures depend a lot on the actual vehicle, so trolleybus is not different from any other vehicle in that respect)
- for FERRY, personally I would also prefer the trip tagged as BUS rather than UNKNOWN, it is a kind of public transport after all. The user has the possibility to correct the mode if he/she wants to. Of course ideally we'd have to add a new mode with an icon and some CO2 emisison rule. 
- for PROPOSED I would translate it to UNKNOWN, but preferably I would change the pipeline algorithm so that the the PROPOSED routes are NOT taken into account.
