### ISSUE TITLE
intake_single pipeline after reset doesn't produce sections and trips

### ISSUE THREAD

**Issue by PatGendre** [e-mission/e-mission-docs#684]
I wanted to rerun the pipeline on my data (and for another user),
so I ran reset_pipeline.py from Nov 3, and than intake_single.py.
I have plenty of trips on my app (tagged as "draft" in the diary) but the intake_single.py doesn't produce new trips and section in the analysis_timeseries db. (so the trips stay as "draft" in the diary).

Which information should I look at in the pipeline logs so as to understand why this is so? Thanks !
(there is no evident error and the file is 34MB, I don't know where to look at first.

**Comment by shankari** [comment]
@PatGendre 

If the intake pipeline does not process new trips, then it must have generated an error somewhere. I would grep for the starting and ending timestamps of each stage.

```
$ grep "For stage" /var/tmp/intake*
```

We expect to see that the starting timestamp for each stage is around Nov 3, and the ending timestamp is close to today, similar to the below.

```
/var/tmp/intake_0.log.2:2021-09-21 16:15:11,615:INFO:139860906460992:For stage PipelineStages.EXPECTATION_POPULATION, start_ts = 2021-11-03T14:07:54.685420

/var/tmp/intake_0.log.2:2021-09-22 17:15:47,782:INFO:139691526514496:For stage PipelineStages.EXPECTATION_POPULATION, last_ts_processed = 2021-11-15T15:00:44.374000
```

- If the start_ts is more recent, the reset did not work
- If the last_ts is unchanged, then that particular stage did not work.

Then you can look at the details for that particular stage and see if there are any errors.

**Comment by PatGendre** [comment]
@shankari 
thanks a lot, I'll have a look and tell you!

**Comment by PatGendre** [comment]
@shankari thanks a lot for your help. 
I resetted the pipeline (to Nov 3) twice, on Nov 9 and on Nov 15. Unfortunately I cannot investigate today but I attach the files resulting from greppin the "For stage" datetimes.
For Nov 9, it is like you mentioned, and I shall investigate the trip segmentation I suppose (the first one), it looks like it did not end properly.
[stagets_1511.txt](https://github.com/e-mission/e-mission-docs/files/7546203/stagets_1511.txt)
[stagets_0911.txt](https://github.com/e-mission/e-mission-docs/files/7546204/stagets_0911.txt)

For Nov 15 it is quite strange, there is no last_ts_processed, as if there were a problem with the server??

**Comment by PatGendre** [comment]
Looking further in the log, 95% of the log is in the trip segmentation step,
I see twice this trip generation ERROR:    
`2021-11-15 18:53:21,016:DEBUG:139756323104576:tracking has been restarted, returning True
2021-11-15 18:53:21,017:DEBUG:139756323104576:get_entry_at_ts query = {'user_id': UUID('c0638b8a-d3fd-41b2-b683-5839b642531d'), 'metadata.key': 'background/filtered_location', 'data.ts': 1633629329}
2021-11-15 18:53:21,017:DEBUG:139756323104576:get_entry_at_ts result = None
2021-11-15 18:53:21,017:ERROR:139756323104576:Trip generation failed for user c0638b8a-d3fd-41b2-b683-5839b642531d
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/analysis/intake/segmentation/trip_segmentation.py", line 108, in segment_current_trips
    create_places_and_trips(user_id, segmentation_points, filter_method_names[filters_in_df[0]])
  File "/var/emission/e-mission-server/emission/analysis/intake/segmentation/trip_segmentation.py", line 231, in create_places_and_trips
    "data.ts", last_place_entry.data.enter_ts)).data
  File "/var/emission/e-mission-server/emission/core/wrapper/wrapperbase.py", line 42, in __init__
    super(WrapperBase, self).__init__(*args, **kwargs)
  File "/vat/opt/miniconda3/envs/emission/lib/python3.7/site-packages/attrdict/dictionary.py", line 17, in __init__
    super(AttrDict, self).__init__(*args, **kwargs)
TypeError: 'NoneType' object is not iterable
2021-11-15 18:53:21,098:DEBUG:139756323104576:About to save object PipelineState({'_id': ObjectId('61709fb7b2fc78dfe188fcaf'), 'user_id': UUID('c0638b8a-d3fd-41b2-b683-5839b642531d'), 'pipeline_stage': 1, 'curr_run_ts': None, 'last_processed_ts': 1633629629, 'last_ts_run': 1635984618.1013029})`

The last processed trip (generating the ERROR) dates from Nov 15, so it is not clear to me why the last processed ts is Oct 7.
But in the previous "moving to long term" stage, it seems there are data from Oct 7 still in the usercache...
`2021-11-15 18:51:12,093:INFO:139756323104576:**********UUID c0638b8a-d3fd-41b2-b683-5839b642531d: moving to long term**********
2021-11-15 18:51:12,121:DEBUG:139756323104576:Found 434 messages in response to query {'user_id': UUID('c0638b8a-d3fd-41b2-b683-5839b642531d'), '$or': [{'metadata.type': 'message'}, {'metadata.type': 'sensor-data'}, {'metadata.type': 'rw-document'}]}
2021-11-15 18:51:12,125:INFO:139756323104576:For stage PipelineStages.USERCACHE, start_ts = 2021-10-07T17:55:29
2021-11-15 18:51:12,125:DEBUG:139756323104576:About to save object PipelineState({'_id': ObjectId('6171f2c7d6d3ff9abde11d75'), 'user_id': UUID('c0638b8a-d3fd-41b2-b683-5839b642531d'), 'pipeline_stage': 0, 'curr_run_ts': 1636998667.125825, 'last_processed_ts': 1633629329, 'last_ts_run': 1636934932.5402527})`

In the previous intake log from Nov 9, the data in the UserCache dated from Nov 1...
`2021-11-09 11:07:41,747:INFO:140632577763136:For stage PipelineStages.USERCACHE, start_ts = 2021-11-01T18:51:54.314000`

In the Nov 9 log I have also a Trip generation failed  ERROR.

In both logs in the end I have errors in the "storing views to cache" stage : 
`Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 288, in get_geojson_for_timeline
    trip_geojson = trip_to_geojson(trip, tl)
  File "/var/emission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 247, in trip_to_geojson
    section_gj = section_to_geojson(section, tl)
  File "/var/emission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 156, in section_to_geojson
    ise = esds.cleaned2inferred_section(section.user_id, section.get_id())
  File "/var/emission/e-mission-server/emission/storage/decorations/section_queries.py", line 45, in cleaned2inferred_section
    curr_predicted_entry = _get_inference_entry_for_section(user_id, section_id, "analysis/inferred_section", "data.cleaned_section")
  File "/var/emission/e-mission-server/emission/storage/decorations/section_queries.py", line 56, in _get_inference_entry_for_section
    assert len(ret_list) <= 1, "Found len(ret_list) = %d, expected <=1" % len(ret_list)
AssertionError: Found len(ret_list) = 2, expected <=1
2021-11-09 11:08:17,206:ERROR:140632577763136:Storing views to cache failed for user c0638b8a-d3fd-41b2-b683-5839b642531d
Traceback (most recent call last):
  File "/var/emission/e-mission-server/emission/net/usercache/builtin_usercache_handler.py", line 109, in storeViewsToCache
    self.storeTimelineToCache(time_query)
  File "/var/emission/e-mission-server/emission/net/usercache/builtin_usercache_handler.py", line 180, in storeTimelineToCache
    trip_gj_list = self.get_trip_list_for_seven_days(start_ts)
  File "/var/emission/e-mission-server/emission/net/usercache/builtin_usercache_handler.py", line 269, in get_trip_list_for_seven_days
    trip_gj_list = gfc.get_geojson_for_ts(self.user_id, seventy_two_hours_ago_ts, start_ts)
  File "/var/emission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 272, in get_geojson_for_ts
    return get_geojson_for_timeline(user_id, tl)
  File "/var/emission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 293, in get_geojson_for_timeline
    raise e
  File "/var/emission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 288, in get_geojson_for_timeline
    trip_geojson = trip_to_geojson(trip, tl)
  File "/var/emission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 247, in trip_to_geojson
    section_gj = section_to_geojson(section, tl)
  File "/var/emission/e-mission-server/emission/analysis/plotting/geojson/geojson_feature_converter.py", line 156, in section_to_geojson
    ise = esds.cleaned2inferred_section(section.user_id, section.get_id())
  File "/var/emission/e-mission-server/emission/storage/decorations/section_queries.py", line 45, in cleaned2inferred_section
    curr_predicted_entry = _get_inference_entry_for_section(user_id, section_id, "analysis/inferred_section", "data.cleaned_section")
  File "/var/emission/e-mission-server/emission/storage/decorations/section_queries.py", line 56, in _get_inference_entry_for_section
    assert len(ret_list) <= 1, "Found len(ret_list) = %d, expected <=1" % len(ret_list)
AssertionError: Found len(ret_list) = 2, expected <=1
`

**Comment by PatGendre** [comment]
@shankari actually I should have checked in the first place if the pipeline reset worked (like you suggested!).
It did not complete because of this error
`Traceback (most recent call last):
  File "bin/reset_pipeline.py", line 101, in <module>
    epr.reset_user_to_ts(user_id, day_ts, args.dry_run)
  File "/var/emission/e-mission-server/emission/pipeline/reset.py", line 71, in reset_user_to_ts
    reset_ts, last_cleaned_place, last_raw_place = get_reset_ts(user_id, last_cleaned_place, is_dry_run)
  File "/var/emission/e-mission-server/emission/pipeline/reset.py", line 88, in get_reset_ts
    last_raw_place_id = last_cleaned_place["data"]["raw_places"][-1]
IndexError: list index out of range
`

**Comment by PatGendre** [comment]
I finally found the reason why the pipeline failed.
It was because there was some data already in the analysis_timeseries database coming from a previous user/token for one day after the date of the pipeline reset (due to manual db update). I delete the data and the pipeline passed :-)
