### ISSUE TITLE
Switch to instructions using the SDK directly instead of Android Studio

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#711]
- Makes is easier to lock down versions of android dependencies such as build tools
- Makes it easier to use alternative SDKs such as [VS Code](https://github.com/Microsoft/vscode) (open source code editor).

**Comment by shankari** [comment]
STEP 1: Download the android SDK from 
https://developer.android.com/studio/

**Question for reproducibility**: Is there a way to programmatically determine the file name so we can download it as part of the setup?

**Comment by shankari** [comment]
Install doesn't really seem to work

```
$ ./bin/sdkmanager --sdk_root=~/Library/Android/sdk_new
[=======================================] 100% Computing updates...
```

```
$ ls -al ~/Library/Android/sdk_new/
total 0
drwxr-xr-x  2 kshankar  NREL_NT\Domain Users   64 Mar 29 09:38 .
drwxr-xr-x  4 kshankar  NREL_NT\Domain Users  128 Mar 29 09:38 ..
```

**Comment by shankari** [comment]
ah, so it looks like with the command line install, there is no "default SDK install" as with Android Studio (https://developer.android.com/studio/command-line/sdkmanager)

```
Available Packages:
```

  Path                                                                                     | Version      | Description
  -------                                                                                  | -------      | -------
  add-ons;addon-google_apis-google-15                                                      | 3            | Google APIs
  add-ons;addon-google_apis-google-16                                                      | 4            | Google APIs
  add-ons;addon-google_apis-google-17                                                      | 4            | Google APIs

This is a Good Thing, because it allows us to lock down the SDK versions that we use.
We can either specify packages on the command line or in a file.
Let's go with the file option since it is easier to check in and keep consistent.

**Comment by shankari** [comment]
### Current install in android studio

#### SDK platform
<img width="747" alt="Screen Shot 2022-03-29 at 3 22 28 PM" src="https://user-images.githubusercontent.com/2423263/160716687-943e4161-8ef2-4a40-8b91-69c085023c20.png">
#### SDK tools
<img width="747" alt="Screen Shot 2022-03-29 at 3 22 41 PM" src="https://user-images.githubusercontent.com/2423263/160716718-178d3d93-5251-4004-bdbf-895a87354a28.png">
#### system images
<img width="1587" alt="Screen Shot 2022-03-29 at 3 23 59 PM" src="https://user-images.githubusercontent.com/2423263/160716822-f748703b-4e51-4e39-bfbe-ae73857cda37.png">

**Comment by shankari** [comment]
Even with this, it is hard to match the UI descriptions to the text descriptions.

For example, should I install

```
  add-ons;addon-google_apis-google-15                                                      | 3            | Google APIs
  add-ons;addon-google_apis-google-16                                                      | 4            | Google APIs
  add-ons;addon-google_apis-google-17                                                      | 4            | Google APIs
```

what about

```
  ndk-bundle                                                                               | 22.1.7171670 | NDK
  ndk;16.1.4479499                                                                         | 16.1.4479499 | NDK (Side by side) 16.1.4479499
  ndk;17.2.4988734                                                                         | 17.2.4988734 | NDK (Side by side) 17.2.4988734
```

Let's try to dump the current state as a text file.

**Comment by shankari** [comment]
[current_installed_list.gz](https://github.com/e-mission/e-mission-docs/files/8375393/current_installed_list.gz)

So we don't need the add-ons and we don't need the NDK.
Let's start by just installing this into the new SDK for a side-by-side comparison before the upgrade.

**Comment by shankari** [comment]
That worked

```
$ ls -al
total 8
drwxr-xr-x  14 kshankar  NREL_NT\Domain Users  448 Mar 29 16:14 .
drwxr-xr-x   4 kshankar  NREL_NT\Domain Users  128 Mar 29 09:38 ..
-rw-r--r--   1 kshankar  NREL_NT\Domain Users   16 Mar 29 16:43 .knownPackages
drwxr-xr-x   2 kshankar  NREL_NT\Domain Users   64 Mar 29 16:15 .temp
drwxr-xr-x   6 kshankar  NREL_NT\Domain Users  192 Mar 29 16:12 build-tools
drwxr-xr-x   3 kshankar  NREL_NT\Domain Users   96 Mar 29 12:27 cmdline-tools
drwxr-xr-x  20 kshankar  NREL_NT\Domain Users  640 Mar 29 15:45 emulator
drwxr-xr-x   4 kshankar  NREL_NT\Domain Users  128 Mar 29 16:14 extras
drwxr-xr-x   6 kshankar  NREL_NT\Domain Users  192 Mar 29 15:51 licenses
drwxr-xr-x   3 kshankar  NREL_NT\Domain Users   96 Mar 29 15:44 patcher
drwxr-xr-x  18 kshankar  NREL_NT\Domain Users  576 Mar 29 15:44 platform-tools
drwxr-xr-x   4 kshankar  NREL_NT\Domain Users  128 Mar 29 16:15 platforms
drwxr-xr-x  11 kshankar  NREL_NT\Domain Users  352 Mar 29 16:12 system-images
drwxr-xr-x  14 kshankar  NREL_NT\Domain Users  448 Mar 29 15:45 tools
```

**Comment by shankari** [comment]
Set to the new location

```
$ echo $ANDROID_SDK_ROOT
~/Library/Android/sdk/
$ export ANDROID_SDK_ROOT=~/Library/Android/sdk_new/
$ echo $ANDROID_SDK_ROOT
~/Library/Android/sdk_new/
```

**Comment by shankari** [comment]
Build successful!

```
$ npx cordova build android
...
BUILD SUCCESSFUL in 19s
49 actionable tasks: 11 executed, 38 up-to-date
Built the following apk(s):
	/Users/kshankar/e-mission/native_code_upgrade/platforms/android/app/build/outputs/apk/debug/app-debug.apk
```

Emulators are present

```
./cmdline-tools/latest/bin/avdmanager list targets
Available Android targets:==============] 100% Fetch remote repository...
----------
id: 1 or "android-30"
     Name: Android API 30
     Type: Platform
     API level: 30
     Revision: 3
----------
id: 2 or "android-31"
     Name: Android API 31
     Type: Platform
     API level: 31
     Revision: 1
```

Emulator launched

```
Built the following apk(s):
	/Users/kshankar/e-mission/native_code_upgrade/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/Users/kshankar/Library/Android/sdk_new (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Using Android SDK: /Users/kshankar/Library/Android/sdk_new
Deploying to emulator emulator-5554
Using apk: /Users/kshankar/e-mission/native_code_upgrade/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Package name: edu.berkeley.eecs.emission
INSTALL SUCCESS
LAUNCH SUCCESS
```

**Comment by shankari** [comment]
Can I choose the emulator I want to use? Yes.

```
$ ./emulator/emulator Pixel_3_API_29
INFO    | Android emulator version 31.2.9.0 (build_id 8316981) (CL:N/A)
ERROR   | No AVD specified. Use '@foo' or '-avd foo' to launch a virtual device named 'foo'

kshankar-35069s:sdk_new kshankar$ ./emulator/emulator @Pixel_3_API_29
INFO    | Android emulator version 31.2.9.0 (build_id 8316981) (CL:N/A)
WARNING | Crash service did not start

INFO    | configAndStartRenderer: setting vsync to 60 hz
WARNING | cannot add library /Users/kshankar/Library/Android/sdk_new/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib: failed
INFO    | added library /Users/kshankar/Library/Android/sdk_new/emulator/lib64/vulkan/libvulkan.dylib
INFO    | Started GRPC server at 127.0.0.1:8556, security: Local
INFO    | Advertising in: /Users/kshankar/Library/Caches/TemporaryItems/avd/running/pid_28703.ini
INFO    | Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

INFO    | boot completed
INFO    | boot time 31324 ms
INFO    | Increasing screen off timeout, logcat buffer size to 2M.
INFO    | Revoking microphone permissions for Google App.
INFO    | Shutting down gRPC endpoint
INFO    | Shutting down gRPC endpoint
```

While running cordova? No.

```
Built the following apk(s):
	/Users/kshankar/e-mission/native_code_upgrade/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/Users/kshankar/Library/Android/sdk_new (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Using Android SDK: /Users/kshankar/Library/Android/sdk_new
Command failed with exit code 1: avdmanager list avd
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
```

**Comment by shankari** [comment]
This is not a complete dealbreaker, since we can always just run one emulator at a time, which will cause the app to run in it. But it is annoying to not have multiple avds run at the same time.

**Comment by shankari** [comment]
ok, so this is because cordova is running the avdmanager in `$ANDROID_SDK_ROOT/tools/bin` instead of the one in `$ANDROID_SDK_ROOT/cmdtools/latest/bin`.

```
$ ./tools/bin/avdmanager
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

**Comment by shankari** [comment]
The file which opens the `node_modules//cordova-android/lib/emulator.js` which has the line

```
            return Promise.reject(new CordovaError('Could not find `avdmanager` on your $PATH! Are you sure the Android SDK is installed and available?'));
```

let's try setting the path correctly and see if it works.

**Comment by shankari** [comment]
Progress:

```
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/Users/kshankar/Library/Android/sdk_new (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Using Android SDK: /Users/kshankar/Library/Android/sdk_new
not found: emulator
```

**Comment by shankari** [comment]
WORKED!

```
BUILD SUCCESSFUL in 1s
49 actionable tasks: 49 up-to-date
Built the following apk(s):
	/Users/kshankar/e-mission/native_code_upgrade/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/Users/kshankar/Library/Android/sdk_new (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Using Android SDK: /Users/kshankar/Library/Android/sdk_new
Waiting for emulator to start...
INFO    | Android emulator version 31.2.9.0 (build_id 8316981) (CL:N/A)
INFO    | configAndStartRenderer: setting vsync to 60 hz
WARNING | cannot add library /Users/kshankar/Library/Android/sdk_new/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib: failed
INFO    | added library /Users/kshankar/Library/Android/sdk_new/emulator/lib64/vulkan/libvulkan.dylib
Waiting for emulator to boot (this may take a while)...BOOT COMPLETE
Deploying to emulator emulator-5584
Using apk: /Users/kshankar/e-mission/native_code_upgrade/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Package name: edu.berkeley.eecs.emission
INSTALL SUCCESS
LAUNCH SUCCESS
```

**Comment by shankari** [comment]
At this point, I think I have everything that I need to work with cordova.
Next step: Change the README, the setup scripts, and ensure that we can successfully build from a freshly checked out repo.

**Comment by shankari** [comment]
- checked out new repo into tmp
- created directory `sdk`
- unzipped command line tools into `sdk` and moved into `cmdline-tools/latest`
- re-installed packages with ... and accepted all terms and conditions (takes a long time, hung, had to be restarted a couple of times)
- set the PATH (`export PATH=/tmp/start_from_scratch/sdk/cmdline-tools/latest/bin:/tmp/start_from_scratch/sdk/emulator:~/.gem/ruby/2.6.0/bin:$PATH`)
- setup and activated as usual

build and emulate both work

```
$ npx cordova emulate android
BUILD SUCCESSFUL in 1s
49 actionable tasks: 49 up-to-date
Built the following apk(s):
	/private/tmp/start_from_scratch/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/private/tmp/start_from_scratch/sdk (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Using Android SDK: /private/tmp/start_from_scratch/sdk
Waiting for emulator to start...
INFO    | Android emulator version 31.2.9.0 (build_id 8316981) (CL:N/A)
INFO    | configAndStartRenderer: setting vsync to 60 hz
WARNING | cannot add library /private/tmp/start_from_scratch/sdk/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib: failed
INFO    | added library /private/tmp/start_from_scratch/sdk/emulator/lib64/vulkan/libvulkan.dylib
Waiting for emulator to boot (this may take a while)...BOOT COMPLETE
Deploying to emulator emulator-5584
Using apk: /private/tmp/start_from_scratch/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Package name: edu.berkeley.eecs.emission
INFO    | Critical: Failed to load https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true: The 'Access-Control-Allow-Origin' header has a value 'qrc://' that is not equal to the supplied origin. Origin 'qrc://' is therefore not allowed access. (qrc:/html/js/location-mock-web-channel.js:0, (null))

INFO    | Critical: Failed to load https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true: The 'Access-Control-Allow-Origin' header has a value 'qrc://' that is not equal to the supplied origin. Origin 'qrc://' is therefore not allowed access. (qrc:/html/js/location-mock-web-channel.js:0, (null))

INSTALL SUCCESS
LAUNCH SUCCESS
```

**Comment by shankari** [comment]
Next steps: update README, update setup script, remove android studio

**Comment by shankari** [comment]
Initial fix in place. Removing android studio now.
Will attempt to automate some of the fixes before closing this issue.

**Comment by shankari** [comment]
<img width="825" alt="Screen Shot 2022-03-30 at 8 55 05 AM" src="https://user-images.githubusercontent.com/2423263/160878276-0f2c2a72-edbe-4db2-b719-e78a1b544b25.png">

**Comment by shankari** [comment]
wrt automation, tried to see whether gradle would install the SDK itself, but it does not.

```
* Where:
Script '/Users/kshankar/e-mission/native_code_upgrade/platforms/android/CordovaLib/cordova.gradle' line: 69

* What went wrong:
A problem occurred evaluating script.
> No installed build tools found. Install the Android build tools version 30.0.3 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by shankari** [comment]
wrt https://github.com/e-mission/e-mission-docs/issues/711#issuecomment-1082048496
Although the UI requires clicking through the agreement, after the clickthrough, we just get a https URL which is downloadable via curl.
So it is possible to automate this.

**Comment by shankari** [comment]
NOTE: the new SDK-only install does not include skins, and I don't see the ability to download skins other than through Android Studio. All the avds created so far were created in the UI and have skins associated with them by default.

Primary options are:
1. copy skins from the previous SDK (amn't I glad I copied it instead of deleting)
1. remove skin-related entries from the avd config files (in `~/.android/avd/<target.avd/config.ini`)

Going with the first option for now since it is more easily reversible. Adding the skins folder here in case it helps anybody else.
[sample_skins.tar.gz](https://github.com/e-mission/e-mission-docs/files/8415556/sample_skins.tar.gz)

**Comment by shankari** [comment]
After adding the skins folder, everything works

**Comment by shankari** [comment]
gist with some notes on creating new AVDs using sdkmanager tools alone
https://gist.github.com/mrk-han/66ac1a724456cadf1c93f4218c6060ae
(without hardware profiles or skins)
