### ISSUE TITLE
Deploy the NREL OpenPATH app to staging

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#732]
I didn't think that we needed this since it should be a simple matter of changing the URL, but I'm getting a 404 error, so maybe I do.

Completed task:
- Switch to autogenerated token (https://github.com/e-mission/e-mission-phone/pull/833)

Current known tasks (in order):
1. Connect to the server
2. Switch to the new surveys
3. Translate the new surveys
4. Switch to the new summary and terms
5. Translate the new summary and terms
6. Switch the app name and package name
7. Create placeholder store entries
8. Deploy to internal testing channels

We may want to switch to an internal fork at step 2 or just make the changes to master.
But let's finish (1) first.

**Comment by shankari** [comment]
Ok, so if I change the `"connectUrl": "https://stage-host/study/study_name/"`, I get a 404 error
If I access it directly through a web URL
https://stage-host/study/study_name/profile/create

it redirects to https://stage-host/profile/create and returns a 405 error ("Method not allowed"). The 405 error is consistent with supporting only POST, not GET on that method.

Let's try:
- connecting using python
- try on android
- try changing the format of the URL to split the host and path differently in iOS

**Comment by shankari** [comment]
#### Trying on android

- I get a 403 instead of a 404

```
05-27 11:05:13.696 19238 19576 D JWTAuthPlugin: Force setting the prompted auth token = <token>
05-27 11:05:13.711 19238 19576 D BuiltinUserCache: Added value for key prompted-auth at time 1.653674713696E9
05-27 11:05:13.762 19238 19576 D ConnectionSettings: in getConnectURL, connectionSettings = {"connectUrl":"https:\/\/stage-host\/study\/study_name\/","aggregate_call_auth":"no_auth","android":{"auth":{"method":"prompted-auth","clientID":"ignored"}},"ios":{"auth":{"method":"prompted-auth","clientID":"ignored"}}}
05-27 11:05:13.771 19238 19576 D ConnectionSettings: in getConnectURL, returning https://stage-host/study/study_name/
05-27 11:05:13.772 19238 12620 I System.out: Posting data to https://stage-host/study/study_name//profile/create
05-27 11:05:13.773 19238 12620 I System.out: About to execute query SELECT data FROM userCache WHERE key = 'prompted-auth' AND type = 'local-storage' AND write_ts >= 0.0 AND write_ts <= 1.653674713773E12 ORDER BY write_ts DESC
05-27 11:05:13.793 19238 12620 I PromptedAuth: Auth found in local storage, now it should be stable
org.apache.http.message.BasicHttpResponse@a2df82c with status HTTP/1.1 403 Forbidden
```

**Comment by shankari** [comment]
### Trying on python 

- I get a 500. Ok so this is the only call for which we are actually getting to the server.
- Not sure why the request JSON is not set in properly 

```
>>> import requests
>>> url = "..."
>>> data = {"user": "abc123"}
>>> requests.post(url, data)
<Response [500]>
>>> response = requests.post(url, data)
>>> response
<Response [500]>
>>> response.text
'\n    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n    
<html>\n       
<head>\n           
<title>Error: 500 Internal Server Error</title>\n            
<style type="text/css">\n              
<pre>Internal Server Error</pre>\n              
<h2>Exception:</h2>\n              
<pre>TypeError(&quot;&#039;NoneType&#039; object is not subscriptable&quot;)</pre>\n              
<h2>Traceback:</h2>\n              
<pre>Traceback (most recent call last):\n  
File &quot;/usr/src/app/e-mission-server/emission/net/api/bottle.py&quot;, line 997, in _handle\n    out = route.call(**args)\n
File &quot;/usr/src/app/e-mission-server/emission/net/api/bottle.py&quot;, line 1998, in wrapper\n    rv = callback(*a, **ka)\n
File &quot;emission/net/api/cfc_webapp.py&quot;, line 312, in createUserProfile\n    userEmail = enaa._getEmail(request, auth_method)\n  
File &quot;/usr/src/app/e-mission-server/emission/net/auth/auth.py&quot;, line 74, in _getEmail\n    userToken = request.json[&#039;user&#039;]\n
TypeError: &#039;NoneType&#039; object is not subscriptable\n</pre>\n        </body>\n    </html>\n'
```

**Comment by shankari** [comment]
Continuing on python, but explicitly using json, we get a more informative response

```
'\n    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n    
<html>\n       
<head>\n            
<title>Error: 403 Forbidden</title>\n            
 <h1>Error: 403 Forbidden</h1>\n            

<p>Sorry, the requested URL <tt>&#039;https://...&#039;</tt>\n               caused an error:</p>\n            
<pre>(&#039;Invalid token abc123, not found in list of length 1&#039;,)</pre>\n        
</body>\n    
</html>\n'
```

Looking further at the configuration for our server, we had set it up with authtype = secret 
https://github.com/e-mission/e-mission-server/commit/460b9e480867edf98ce468ce9e96ec2d29e0a9d6
to support the closed recruitment option for NREL-Lo_Hi

Let's open it up since we no longer have that secret

**Comment by shankari** [comment]
Does not work even after reverting. This appears to be because the redeploy does not work.
- 1:05: made change
- 1:06 and 1:30: re-deployed using Jenkins
- 1:39pm: webapp logs still have secret

**Comment by shankari** [comment]
While waiting for the server to be resolved, let's look at the iOS issue.
Both android and python return a 403, for reasons that we understand.
However, iOS returns a 405. Let's see if we can get iOS to also return a 403.

In `postToHost`, we have 

```
_mUrl	NSURL *	@"/profile/create -- https://study-host/study/study_name/"	0x0000600003f845a0
NSObject	NSObject	
_urlString	NSString *	0x200001d80	0x0000000200001d80
_baseURL	NSURL *	0x80001000001c020	0x080001000001c020
_clients	__NSCFString *	@"/profile/create"	0x000060000125cea0
_reserved	NSURL *	@"https://study-host/study/study_name/"	0x000060000379ab50
```

Note that the baseURL is not set and instead the base URL is populated in something called `reserved`.

```
error	NSError *	domain: @"com.google.HTTPStatus" - code: 404	0x000060000123f870
_userInfo	__NSFrozenDictionaryM *	0x600001c07380	0x0000600001c07380
NSDictionary	NSDictionary	
```

According to the NSURL documentation:
https://developer.apple.com/documentation/foundation/nsurl?language=objc

this should work

```
NSURL *baseURL = [NSURL fileURLWithPath:@"file:///path/to/user/"];
NSURL *URL = [NSURL URLWithString:@"folder/file.html" relativeToURL:baseURL];
NSLog(@"absoluteURL = %@", [URL absoluteURL]);
```

**Comment by shankari** [comment]
Ah, printing out the absolute URL gives us a clue

```
NSLog(@"absoluteURL = %@", [URL absoluteURL]);
```

```
2022-05-27 17:25:36.802810-0700 em-devapp[36366:5489708] DEBUG: postToHost called with url = /pipeline/get_range_ts -- https://stage-host/study/study_name/
2022-05-27 17:25:50.258271-0700 em-devapp[36366:5489708] absoluteURL = https://stage-host/pipeline/get_range_ts
```

**Comment by shankari** [comment]
We create the URL like this

```
+(void)pushGetJSON:(NSDictionary*)toSend toURL:(NSString*)relativeURL completionHandler:(void (^)(NSData *data, NSURLResponse *response, NSError *error))completionHandler {
    NSMutableDictionary *toPush = [NSMutableDictionary dictionaryWithDictionary:toSend];
    
    NSURL* kBaseURL = [[ConnectionSettings sharedInstance] getConnectUrl];
    NSURL* absoluteURL = [NSURL URLWithString:relativeURL
                                 relativeToURL:kBaseURL];
    
    CommunicationHelper *executor = [[CommunicationHelper alloc] initPost:absoluteURL data:toPush completionHandler:completionHandler];
    [executor execute];
}
```

which is similar to 

```
NSURL *baseURL = [NSURL fileURLWithPath:@"file:///path/to/user/"];
NSURL *URL = [NSURL URLWithString:@"folder/file.html" relativeToURL:baseURL];
NSLog(@"absoluteURL = %@", [URL absoluteURL]);
```

This returns `file:///path/to/user/folder/file.html`, so we should return `https://stage-host/study/study_name/profile/update`
Let's experiment further with why this is not happening

**Comment by shankari** [comment]
This is not happening because the sample code doesn't work. For the copy-pasted example in the NSURL documentation

```
    NSURL *baseURL = [NSURL fileURLWithPath:@"file:///path/to/user/"];
    NSURL *URL = [NSURL URLWithString:@"folder/file.html" relativeToURL:baseURL];
    NSLog(@"absoluteURL = %@", [URL absoluteURL]);
```

the output is

```
2022-05-27 22:59:45.461654-0700 em-devapp[45938:5561235] absoluteURL = file:///file:/path/to/folder/file.html
```

**Comment by shankari** [comment]
Changing to the instance method does not fix it. The static method probably just turns around and calls the instance method.

```
    NSURL *baseURL = [NSURL fileURLWithPath:@"file:///path/to/user/"];
    NSURL *testAbsoluteURL = [[NSURL alloc] initWithString:@"folder/file.html" relativeToURL:baseURL];
    NSLog(@"testAbsoluteURL = %@", [testAbsoluteURL absoluteURL]);
```

returns 

```
2022-05-28 09:48:24.546339-0700 em-devapp[53565:5628169] testAbsoluteURL = file:///file:/path/to/folder/file.html
```

**Comment by shankari** [comment]
Aha! Appending at the string level works well

```
    NSString* baseURLString = @"file:///path/to/user/";
    NSString* absoluteURLString = [baseURLString stringByAppendingString:@"folder/file.html"];

    NSURL *testAbsoluteURL = [NSURL URLWithString:absoluteURLString];
    NSLog(@"testAbsoluteURL = %@", [testAbsoluteURL absoluteURL]);
```

returns

```
2022-05-28 09:55:31.839879-0700 em-devapp[54675:5638619] testAbsoluteURL = file:///path/to/user/folder/file.html
```

**Comment by shankari** [comment]
Making a similar change to the actual URL results in the expected

```
2022-05-28 10:01:20.240747-0700 em-devapp[55412:5645521] absoluteURL right after creation = https://stage-host/study/<study_name>//pipeline/get_range_ts
```

which, in turn, results in the same 403 error as android and python

```
error	NSError *	domain: @"com.google.HTTPStatus" - code: 403	0x00006000009bea00
```

and on looking at the error in detail

```
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 403 Forbidden</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans-serif;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 403 Forbidden</h1>
            <p>Sorry, the requested URL <tt>&#039;https://stage-host/pipeline/get_range_ts&#039;</tt>
               caused an error:</p>
            <pre>Invalid token [...], not found in list of length 1</pre>
        </body>
    </html>
```

**Comment by shankari** [comment]
While implementing this, let's change the exported value from the connection settings to return a string instead of a URL.
- No reason to convert from String -> URL -> String
- We can ensure that we convert all call sites

**Comment by shankari** [comment]
Let's now work on (2) and (3) from the original list while waiting for the server configuration to change.
We will go ahead and update these on the master branch. The existing demographic survey appears to be a placeholder from UNSW anyway and is not one that we really want to be the default.

**Comment by shankari** [comment]
there used to be very clear documentation of how to use xforms in enketo, but I can't find it now.
Fortunately, per this previous comment, https://github.com/e-mission/e-mission-docs/issues/376#issuecomment-484133975
we are supposed to use enketo transformer.
https://github.com/enketo/enketo-transformer

https://enketo.org/develop/#transformation

Since we have merged the survey code into master, let's add this as a devDependency as well to make it easier to update the forms.

The UNSW team has checked this into the rciti branch
https://github.com/e-mission/e-mission-phone/tree/rk-unsw/survey-resources

Merging it over to master and then using it on the xforms that we got from the enketo toolbox...

**Comment by shankari** [comment]
`npm install` fails with 

<details>
<summary>npm install failure</summary>

```
$ npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated node-pre-gyp@0.9.1: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> node1-libxmljsmt@1.0.0 install /Users/kshankar/e-mission/phone-rciti-branch/survey-resources/node_modules/node1-libxmljsmt
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v83-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v83-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v83-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node1-libxmljsmt@1.0.0 and node@14.18.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v83-darwin-x64.tar.gz
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
  CXX(target) Release/obj.target/xmljs/src/xml_document.o
../src/xml_document.cc:190:18: error: no matching member function for call to 'Get'
        if (obj->Get(Nan::New<v8::String>("declaration").ToLocalChecked())->IsFalse()) {
            ~~~~~^~~
/Users/kshankar/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/kshankar/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
../src/xml_document.cc:195:18: error: no matching member function for call to 'Get'
        if (obj->Get(Nan::New<v8::String>("format").ToLocalChecked())->IsTrue()) {
            ~~~~~^~~
...
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/kshankar/e-mission/phone-rciti-branch/survey-resources/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Darwin 20.6.0
node-pre-gyp ERR! command "/Users/kshankar/.nvm/versions/node/v14.18.1/bin/node" "/Users/kshankar/e-mission/phone-rciti-branch/survey-resources/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /Users/kshankar/e-mission/phone-rciti-branch/survey-resources/node_modules/node1-libxmljsmt
node-pre-gyp ERR! node -v v14.18.1
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute '/Users/kshankar/.nvm/versions/node/v14.18.1/bin/node /Users/kshankar/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/Users/kshankar/e-mission/phone-rciti-branch/survey-resources/node_modules/node1-libxmljsmt/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/kshankar/e-mission/phone-rciti-branch/survey-resources/node_modules/node1-libxmljsmt/build/Release --napi_version=8 --node_abi_napi=napi' (1)
npm WARN xform-transformer@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node1-libxmljsmt@1.0.0 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node1-libxmljsmt@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kshankar/.npm/_logs/2022-05-30T05_08_03_473Z-debug.log
```

</details>


It looks like there are no pre-built binaries, we fall back to source compile which then fails

**Comment by shankari** [comment]
Works! In English and Spanish (without translations) no less

| English | Spanish |
|------|------|
| <img width="320" alt="Screen Shot 2022-05-29 at 10 55 43 PM" src="https://user-images.githubusercontent.com/2423263/170926150-b576f1fd-5fab-4703-aa56-9f99451fefeb.png"> | <img width="320" alt="Screen Shot 2022-05-29 at 10 56 49 PM" src="https://user-images.githubusercontent.com/2423263/170926268-0a350962-9373-4761-8b64-db2111da7277.png"> |

Pending tasks:
- Finish spanish translation and make spanish the default for spanish users (https://github.com/enketo/enketo-core/blob/51c5c2f494f1515a67355543b435f6aaa4b151b4/tutorials/10-configuration.md#explicitly-set-the-default-form-language)
- Figure out if we can display the form sections on separate pages
- Deal properly with save vs. next

**Comment by shankari** [comment]
Let's edit it to be similar to the previous survey to deal properly with save vs. next:
- remove the UUID field
- remove the final "estimate of commute time" field since we can get that from OpenPATH
- turn on pagination

**Comment by shankari** [comment]
While ensuring that all the survey code supports spanish properly, ran into an issue where adding `translate` to the dismiss button in the popup turned it green. This is apparently because it now has an `ng-binding` associated with it. Using a span instead....

| Green button | button background transparent | overridden by `ng-binding` class | 
|-------|------|-----|
| <img width="395" alt="Screen Shot 2022-06-01 at 8 35 10 AM" src="https://user-images.githubusercontent.com/2423263/171443359-2dd0881e-2654-4c99-8d2b-c48910880511.png"> | <img width="326" alt="Screen Shot 2022-06-01 at 8 30 27 AM" src="https://user-images.githubusercontent.com/2423263/171443449-46cd1caa-4837-4157-907a-a87c86d24879.png"> | <img width="326" alt="Screen Shot 2022-06-01 at 8 32 51 AM" src="https://user-images.githubusercontent.com/2423263/171443438-8d1128f8-1db9-43dd-96b3-fd38d3e0fac5.png"> |

**Comment by shankari** [comment]
Here's the unreleased? patch to override the form language
https://github.com/enketo/enketo-core/commit/c31dccc811954b50bfd64be033935b8885a584f6

Let's apply it to our copy of the forms library and see if it works.
*Ans:* it does!

**Comment by shankari** [comment]
Final steps left:
- change the summary and consent from e-mission/berkeley IRB -> OpenPATH/NREL privacy policy
- change the default index.html for the container
  - should this return an OpenPATH index file or a 404?
  - let's stick with OpenPATH index file for now since that is what we have in docker

**Comment by shankari** [comment]
Finished the first step in 
https://github.com/e-mission/e-mission-phone/pull/837

Tracking second step in 
https://github.com/e-mission/e-mission-phone/pull/854

**Comment by shankari** [comment]
Merged both steps. Now, let's make the NREL OpenPATH-specific changes in the NREL fork.
Should check with legal on whether we can put them here, or whether we are concerned about making NREL logos available on GitHub.

These changes include:
- changing the logo
- changing the app name
- changing the package name

**Comment by shankari** [comment]
Made all the changes and published a staging version of the app on the stores.

**Comment by shankari** [comment]
While testing, ran into platform issue with iOS12
https://github.com/e-mission/e-mission-docs/issues/735

moving on since that is a corner case

**Comment by shankari** [comment]
Made some other changes:
- debugged push notifications
- ensured that iOS tokens were generated as APNS
- debugged android text strings
- removed the heatmap

Going to finish at least an initial implementation of the config feature and then publish the next version.

**Comment by shankari** [comment]
Config feature implemented and merged into the https://github.com/e-mission/e-mission-phone/tree/master_for_platform branch.

Ran into issue with scheduled tasks; they are currently built off the `emission/e-mission-server.dev.server-only` docker image, which installs the entire conda environment every time. This is sort of OK for long-running containers, but not for scheduled tasks which are launched every hour or so.

Tracking this in https://github.com/e-mission/e-mission-docs/issues/752

**Comment by shankari** [comment]
We would also like an improvement to the token generation. For the CEO e-bike program, we had the tokens include the program as a prefix - e.g. `stage_` which helps a lot while working with the datasets later. For the NREL OpenPATH app, we have done this for the program tokens, but we have not done this for the autogenerated tokens.

This means that later, we will not be able to as easily distinguish between the NREL commute and open access datasets. Inserting the study name into the token will help there as well.

Unfortunately, since we have already had people join both studies, including some people outside NREL, we need to handle this in a backward compat fashion.

The steps for this are:
- on the server:
  - already registered, not yet updated: token will not have study prefix, look it up directly
  - already registered, updated: token will have study prefix, strip out prefix and look it up
  - registered after this: token will have study prefix, look it up without stripping out prefix
- on the phone:
  - generate new tokens with the study prefix
  - at startup, replace non-study-prefixed token with one that has a study prefix

**Comment by shankari** [comment]
We have multiple deployments now; marking this as done and unpinning

**Comment by shankari** [comment]
final check for old-style tokens:
- on open access: stripped out all new style tokens `:g/nrelop_open-access/d`
- removed all tokens of the form 

```
For REDACTED: on motorola, trip count = 0, location count = 0, first trip = None, last trip = None, confirmed_pct  = approximately 0.00, last install: 2022-09-28T14:32:26.958000-06:00
```

We then have a bunch of users whose last trip is from 2022, except for 

```
For REDACTED: on Apple, trip count = 909, location count = 809964, first trip = 2022-07-09T12:07:26.999869-04:00, last trip = 2023-01-08T11:47:26.963294-05:00, confirmed_pct  = approximately 0.07, last install: 2022-07-07T13:09:33.702000-06:00
```

Given that labeling rate, it is pretty clear that they haven't launched the app for a while. 

Given this, it should be fine to remove the hack on both 
Maybe we should also get the last `usercache/get` timestamp just to check
