### ISSUE TITLE
Trip labelling is not working

### ISSUE THREAD

**Issue by montaguegabe** [e-mission/e-mission-docs#741]
At Metro Mobility the team has built the app for iOS and Android.

When a trip has taken it appears in "Diary" but not "Label" (neither in To Label, All Unlabeled, or All Trips).  In Diary, there are buttons "Mode" and "Purpose".  If you click them and select a mode and a purpose, the buttons turn green and a mode/purpose is **temporarily** selected.  However, if the app is quit, or the refresh button is clicked, the buttons turn red again.  **In summary: mode/purpose are not being recorded in any way**.

It is clear that the problem is on the frontend side, probably in the Javascript as it appears in both iOS and Android.  What is the expected behavior here? To me it seems like there should be a network request sent out when a mode/purpose selection is made to record the choices.  However this is not happening.

I can tell there is no network request made upon selection of a choice because:
- Unlike when the refresh button is pressed, there is no traffic logged to the server when a mode/purpose choice is made
- Also unlike when the refresh button is pressed, there are no logs from Xcode that have a URL in them.  Here are the logs from Xcode when I choose a "Mode" of "e-bike":
```
2022-06-15 12:19:21.817964-0400 emission[491:21000] data has 190 bytes, str has size 190
2022-06-15 12:19:21.825013-0400 emission[491:21000] in storeInput, after setting input.value = e-bike, draftInput = {"start_ts":1655307847.2070131,"end_ts":1655308008.72493,"label":"e-bike"}:undefined
2022-06-15 12:19:21.825164-0400 emission[491:21000] in storeInput, after setting input.value = e-bike, draftInput = {"start_ts":1655307847.2070131,"end_ts":1655308008.72493,"label":"e-bike"}: <null>
2022-06-15 12:19:21.825274-0400 emission[491:21000] -[NSNull UTF8String]: unrecognized selector sent to instance 0x1eb5cc558
2022-06-15 12:19:21.825646-0400 emission[491:21000] data has 74 bytes, str has size 74
2022-06-15 12:19:21.859524-0400 emission[491:21000] trip starting at undefined: creating new timeout of 30000:undefined
2022-06-15 12:19:21.859612-0400 emission[491:21000] trip starting at undefined: creating new timeout of 30000: <null>
2022-06-15 12:19:21.859687-0400 emission[491:21000] -[NSNull UTF8String]: unrecognized selector sent to instance 0x1eb5cc558
2022-06-15 12:19:21.859812-0400 emission[491:21000] trip starting at undefined: cancelling existing timeout undefined:undefined
2022-06-15 12:19:21.859875-0400 emission[491:21000] trip starting at undefined: cancelling existing timeout undefined: <null>
2022-06-15 12:19:21.859913-0400 emission[491:21000] -[NSNull UTF8String]: unrecognized selector sent to instance 0x1eb5cc558
2022-06-15 12:19:21.860552-0400 emission[491:21000] DEBUG:section 2022-06-15T11:44:07-04:00 -> 2022-06-15T11:46:48-04:00 bound incident addition
2022-06-15 12:19:21.860688-0400 emission[491:21000] DEBUG: section 2022-06-15T11:44:07-04:00 -> 2022-06-15T11:46:48-04:00 bound incident addition
2022-06-15 12:19:21.862179-0400 emission[491:21000] DEBUG:section 2022-06-15T11:44:07-04:00 -> 2022-06-15T11:46:48-04:00 bound incident addition
2022-06-15 12:19:21.862269-0400 emission[491:21000] DEBUG: section 2022-06-15T11:44:07-04:00 -> 2022-06-15T11:46:48-04:00 bound incident addition
```

This is in contrast to when I hit the refresh button and see many messages of the form:
```
2022-06-15 12:20:43.112662-0400 emission[491:21000] postToHost called with url = https://e-mission.metromobility.io:443/pipeline/get_complete_ts
```

I do not know how to Debug the app outside of Xcode.

**Comment by shankari** [comment]
In an email before this, you said that you were not running the analysis pipeline. 

_I would encourage you to do so - OpenPATH is an integrated system consisting of the app, server and analysis pipeline and will *not* work as expected without all components running smoothly._

> When a trip has taken it appears in "Diary" but not "Label" (neither in To Label, All Unlabeled, or All Trips). In Diary, there are buttons "Mode" and "Purpose". 

This is expected behavior. Draft trips do not show up in the label screen by default.
https://github.com/e-mission/e-mission-docs/blob/4fad0c4dd82893529bdc808fc5a8329f98ea7367/docs/manage/troubleshooting_server_faq.md#trips-on-the-phone-stay-in-draft-green-background-forever

> To me it seems like there should be a network request sent out when a mode/purpose selection is made to record the choices. 

This is an incorrect assumption; the mode and purpose selection are stored locally on the phone just like all other data collected and pushed at the end of the next trip. We are considering changing this, but have to design it carefully since we want to accommodate (low-income) users without data plans who might want to label trips while waiting at a bus stop, for example https://github.com/e-mission/e-mission-docs/issues/640

> I do not know how to Debug the app outside of Xcode.

https://github.com/e-mission/e-mission-docs/blob/4fad0c4dd82893529bdc808fc5a8329f98ea7367/docs/dev/front/high_level_faq.md#i-get-a-blank-screen-while-loading-the-e-mission-phone-ui

> However, if the app is quit, or the refresh button is clicked, the buttons turn red again.

This is probably because you have never run the intake pipeline for the user. In the expected configuration, the pipeline runs every hour, so this situation is unlikely to occur. There is probably a subtle bug that occurs if the user inputs labels before the pipeline runs for the first time, and we can use this issue to investigate and fix it. But the correct workaround for now is to run the analysis pipeline.

If you run the pipeline and the labeling still doesn't work, please send me your phone logs (Profile -> Email Logs) and I am happy to take a look.

**Comment by montaguegabe** [comment]
@shankari If you don't mind a quick question: how does the trip label data get sent off of the phone? If I just knew that I could diagnose the problem much better

**Comment by montaguegabe** [comment]
I am looking at https://github.com/e-mission/e-mission-docs/blob/4fad0c4dd82893529bdc808fc5a8329f98ea7367/docs/manage/troubleshooting_server_faq.md#is-the-data-getting-to-the-server-correctly

I am just worried by seeing nowhere in the code that touches `/usercache/put` or `/usercache/get`. I see a function that as far as I can tell is unused called `putOne`.

**Comment by shankari** [comment]
Note to self: this is probably because of the value returned by `get_complete_ts` when the pipeline has never been run. Note that we load unprocessed labels in the range of (`get_complete_ts`, `now`).
I bet we return -1 from `get_complete_ts` if the pipeline has never been run
So we try to load unprocessed labels in the range (-1, `now`) which doesn't match anything
and so we don't load any of the locally cached labels

**Comment by shankari** [comment]
@montaguegabe after running the pipeline, you should see non-draft (white) trips and trips in the label screen. Once you see that, the labeling will work

**Comment by shankari** [comment]
it's a bit more complicated than that, it looks like we return None

https://github.com/e-mission/e-mission-server/blob/20cbcd06eeaab88fc60ca96faaa00e10b060cf22/emission/storage/pipeline_queries.py#L139

or 

https://github.com/e-mission/e-mission-server/blob/20cbcd06eeaab88fc60ca96faaa00e10b060cf22/emission/net/api/pipeline.py#L19

But I bet that None gets translated to `null` or `undefined` on the phone and that's why this is not returning anything.

**Comment by shankari** [comment]
Testing this on the phone:
- Loaded raw data from `emission/tests/real_example` but **did not** run the pipeline
- Logged in from the UI
- Can confirm that the result of `CommHelper.getPipelineRangeTs()` is 

```
result: Object
  - end_ts: null
  - start_ts: null
```

so we query for 

```
pendingLabelQuery: Object
   - endTs: 1655353496
   - key: "write_ts"
   - startTs: -10
```


<img width="333" alt="Screen Shot 2022-06-15 at 9 25 59 PM" src="https://user-images.githubusercontent.com/2423263/173991112-73748969-1857-4a7e-86b4-5f85916f8eed.png">

But this should still return values...

**Comment by montaguegabe** [comment]
I ran the pipeline manually from a local docker container I think - not entirely sure.  The crontab appears to be outdated, as most of the commands referenced in it do not exist anymore:
```
5 * * * * ./e-mission-py.bash bin/intake_multiprocess.py 3 >> /tmp/log/intake.stdinout 2>&1
# 45 * * * * ./e-mission-py.bash bin/make_tiersys.py >> /tmp/log/make_tiersys.stdinout 2>&1
# 50 * * * * ./e-mission-py.bash bin/update_polarbear.py >> /tmp/log/update_polarbear.stdinout 2>&1
# 55 * * * * ./e-mission-py.bash bin/check_for_notifications.py >> /tmp/log/check_for_notifications.stdinout 2>&1
59 * * * * ./e-mission-py.bash bin/push/silent_ios_push.py 3600 >> /tmp/log/silent_ios_push.stdinout 2>&1
0 5 * * * ./e-mission-py.bash bin/build_label_model.py -a >> /tmp/log/better_model.log 2>&1
```

Only `intake_multiprocess` `silent_ios_push` and `build_label_model` I could find in the bin directory. I ran the first command and got the output:
```
(emission) root@54b16a3bbbb2:/usr/src/app/e-mission-server# ./e-mission-py.bash bin/intake_multiprocess.py 3
Connecting to database URL XXX
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
expectations.conf.json not configured, falling back to sample, default configuration
Connecting to database URL XXX
Connecting to database URL XXX
Connecting to database URL XXX
analysis.debug.conf.json not configured, falling back to sample, default configuration
analysis.debug.conf.json not configured, falling back to sample, default configuration
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
expectations.conf.json not configured, falling back to sample, default configuration
expectations.conf.json not configured, falling back to sample, default configuration
expectations.conf.json not configured, falling back to sample, default configuration
```

Hopefully this will start to get things working.  I also ran the last command `./e-mission-py.bash bin/build_label_model.py -a` and got output:
```
Connecting to database URL XXXX
Namespace(all=True, email_list=None, platform=None, user_list=None)
2022-06-16 04:27:43,354:INFO:received list with [] users
```

**Comment by shankari** [comment]
> Only intake_multiprocess silent_ios_push and build_label_model I could find in the bin directory. I ran the first command and got the output:

The others are for the gamification components which are not in the master branch. You will find them in the `ceo_ebike_project` branch. They are not necessary on master, the intake pipeline is the main one.

> Hopefully this will start to get things working.

This is not the expected output of the intake pipeline. It should find a bunch of users and output lines that outline the stages that it is running

```
2022-06-16 04:27:43,354:INFO:received list with [] users
```

seems to indicate that you have no data on the server. Do you have any users? Are there `/usercache/put` calls visible in the webapp logs, right after you finished a trip?

**Comment by montaguegabe** [comment]
I can see user IDs in the MongoDB database of users that register with the app, so the MongoDB database isn't empty. I don't know how to see logs right after a trip is finished because my phone can't be plugged in (maybe I can take my laptop with me)

I worry there might not be `/usercache/put` calls, because where would they be coming from? I can't find reference to that endpoint from any client code: https://github.com/e-mission/e-mission-phone/search?q=%2Fusercache%2Fput

**Comment by shankari** [comment]
> I worry there might not be /usercache/put calls, because where would they be coming from? 

They would be coming from the native code, since you are not guaranteed to have the app in the foreground and the javascript running all the time

> I don't know how to see logs right after a trip is finished because my phone can't be plugged in

That is why I built in cached logging infrastructure - you can email the logs to yourself

> I can see user IDs in the MongoDB database of users that register with the app

which database is this? and does it match the one that the intake.py pipeline is looking at?

**Comment by montaguegabe** [comment]
A yes, I can see that endpoint in BEMCommunicationHelper.m

I will look at emailing the logs to myself and see what they say.

It could also be that I set the server up to use token_list.json, but we haven't been registering using tokens from the list

**Comment by shankari** [comment]
I can confirm that I can reproduce this for a user where the pipeline was not run, and that once the pipeline runs, the same labels are loaded on refresh


### without pipeline run, problem reproduced 
https://user-images.githubusercontent.com/2423263/173993216-6167bb78-ff4c-427b-b158-ecba89245623.mov 

Run the pipeline

```
$ ./e-mission-py.bash bin/debug/intake_single_user.py -u a1e8c061-3932-4e9f-8d3a-8102b4c9458b
storage not configured, falling back to sample, default configuration
URL not formatted, defaulting to "Stage_database"
Connecting to database URL localhost
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
overpass not configured, falling back to default overleaf.de
transit stops query not configured, falling back to default
expectations.conf.json not configured, falling back to sample, default configuration
ERROR:root:habitica not configured, game functions not supported
Traceback (most recent call last):
  File "/Users/kshankar/e-mission/gis_branch_tests/emission/net/ext_service/habitica/proxy.py", line 22, in <module>
    key_file = open('conf/net/ext_service/habitica.json')
FileNotFoundError: [Errno 2] No such file or directory: 'conf/net/ext_service/habitica.json'
2022-06-15T21:38:17.938480-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: moving to long term**********
2022-06-15T21:38:17.953459-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: updating incoming user inputs**********
2022-06-15T21:38:18.007059-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: filter accuracy if needed**********
2022-06-15T21:38:18.048036-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: segmenting into trips**********
2022-06-15T21:38:22.700632-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: segmenting into sections**********
/Users/kshankar/e-mission/gis_branch_tests/emission/analysis/intake/segmentation/section_segmentation_methods/flip_flop_detection.py:59: RuntimeWarning: invalid value encountered in double_scalars
  sm.update({"trip_pct": (curr_section_time * 100)/total_trip_time})
2022-06-15T21:38:23.495452-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: smoothing sections**********
2022-06-15T21:38:24.042841-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: cleaning and resampling timeline**********
2022-06-15T21:38:25.704308-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: inferring transportation mode**********
Error while inferring modes, timestamp is unchanged

*** BUNCH OF VERIFICATION ERRORS DUE TO BEING ON THE VPN ***

2022-06-15T21:38:26.149547-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: inferring labels**********
2022-06-15T21:38:26.275870-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: populating expectations**********
2022-06-15T21:38:26.313863-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: creating confirmed objects **********
2022-06-15T21:38:26.404305-07:00**********UUID a1e8c061-3932-4e9f-8d3a-8102b4c9458b: storing views to cache**********
```

### after pipeline
https://user-images.githubusercontent.com/2423263/173993229-ca24ca8d-5ca4-49f7-9bbc-e125833a3766.mov

**Comment by montaguegabe** [comment]
Thank you so much Shankari!  It is getting late here so I am going to try `intake_single_user` tomorrow. I downloaded the logDB and see many calls to `/usercache/put` which makes me very relieved.  We were worried about making TestFlight and Android users update the app if the data wasn't going to the proper place, but even if it was being rejected due to authtokens, we could resolve that from our end after the fact.

Will let you know if I can reproduce your fix from the second video - that is very helpful to see what it should look like

**Comment by shankari** [comment]
> It could also be that I set the server up to use token_list.json, but we haven't been registering using tokens from the list

In that case, the user should not be able to register and there should be no entries in MongoDB. You might want to look carefully at the database with the users, or run the intake pipeline per user initially to see what is going on.

**Comment by montaguegabe** [comment]
Hi Shankari,

All we get when we run the command is:

```
Connecting to database URL mongodb://metromobility:xfSRP1q1JAOt8fcR@cluster0-shard-00-00.z56eq.mongodb.net:27017/Cluster0?ssl=true&replicaSet=atlas-a7u6ma-shard-0&authSource=admin&retryWrites=true&w=majority
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
expectations.conf.json not configured, falling back to sample, default configuration
2022-06-16T18:12:22.645614+00:00**********UUID 6cb37491-6a98-4fb6-bf46-d526d9cec475: moving to long term**********
2022-06-16T18:12:23.029994+00:00**********UUID 6cb37491-6a98-4fb6-bf46-d526d9cec475: updating incoming user inputs**********
```

There is no further output beyond that and the process terminates without any other messages. Any ideas why there might be a difference? I looked in MongoDB and found my UUID and pasted in the hex for it to the debug command

**Comment by shankari** [comment]
the logs for the intake pipeline go to the location configured in `conf/log/intake.*` do you see any errors there?

**Comment by montaguegabe** [comment]
I left at the default configuration - let me see..

**Comment by montaguegabe** [comment]
There is a lot of output in these logs, but `intake_single-errors.log` is empty, and the last bit of intake_single.log is:
```
2022-06-16 18:19:38,824:DEBUG:140481152988992:orig_ts_db_keys = ['manual/mode_confirm', 'manual/purpose_confirm'], analysis_ts_db_keys = []
2022-06-16 18:19:38,854:DEBUG:140481152988992:finished querying values for ['manual/mode_confirm', 'manual/purpose_confirm'], count = 0
2022-06-16 18:19:38,855:DEBUG:140481152988992:finished querying values for [], count = 0
2022-06-16 18:19:38,855:DEBUG:140481152988992:orig_ts_db_matches = 0, analysis_ts_db_matches = 0
2022-06-16 18:19:38,908:DEBUG:140481152988992:Matching 0 inputs to trips
2022-06-16 18:19:38,908:DEBUG:140481152988992:len(toMatchInputs) == 0, early return
2022-06-16 18:19:38,909:DEBUG:140481152988992:after run, last_user_input_done == None, must be early return
2022-06-16 18:19:38,938:INFO:140481152988992:For stage PipelineStages.USER_INPUT_MATCH_INCOMING, last_ts_processed is unchanged
2022-06-16 18:19:38,939:DEBUG:140481152988992:About to save object PipelineState({'_id': ObjectId('62ab743aac723225b4b810fb'), 'user_id': UUID('b6ee96c5-2768-404e-bc66-50c3a32927ff'), 'pipeline_stage': 12, 'curr_run_ts': None, 'last_processed_ts': None, 'last_ts_run': 1655403573.7366147})
2022-06-16 18:19:38,999:DEBUG:140481152988992:After saving state PipelineState({'_id': ObjectId('62ab743aac723225b4b810fb'), 'user_id': UUID('b6ee96c5-2768-404e-bc66-50c3a32927ff'), 'pipeline_stage': 12, 'curr_run_ts': None, 'last_processed_ts': None, 'last_ts_run': 1655403573.7366147}), list is [{'_id': ObjectId('62ab743aac723225b4b810fb'), 'user_id': UUID('b6ee96c5-2768-404e-bc66-50c3a32927ff'), 'pipeline_stage': 12, 'curr_run_ts': None, 'last_processed_ts': None, 'last_ts_run': 1655403573.7366147}]
2022-06-16 18:19:39,000:DEBUG:140481152988992:insert called with entry of type <class 'emission.core.wrapper.entry.Entry'>
2022-06-16 18:19:39,000:DEBUG:140481152988992:entry was fine, no need to fix it
2022-06-16 18:19:39,001:DEBUG:140481152988992:Inserting entry Entry({'_id': ObjectId('62ab743bac723225b4b810fc'), 'user_id': UUID('b6ee96c5-2768-404e-bc66-50c3a32927ff'), 'metadata': Metadata({'key': 'stats/pipeline_time', 'platform': 'server', 'write_ts': 1655403579.000238, 'time_zone': 'America/Los_Angeles', 'write_local_dt': LocalDate({'year': 2022, 'month': 6, 'day': 16, 'hour': 11, 'minute': 19, 'second': 39, 'weekday': 3, 'timezone': 'America/Los_Angeles'}), 'write_fmt_time': '2022-06-16T11:19:39.000238-07:00'}), 'data': {'name': 'USER_INPUT_MATCH_INCOMING', 'ts': 1655403579.0000863, 'reading': 0.2599049999989802}}) into timeseries
2022-06-16 18:19:39,323:DEBUG:140481152988992:Found no entries for b6ee96c5-2768-404e-bc66-50c3a32927ff, skipping
```

**Comment by shankari** [comment]
that is from `emission//pipeline/intake_stage.py`

```
        if edb.get_timeseries_db().find({"user_id": uuid}).distinct("metadata.key") == ["stats/pipeline_time"]:
            logging.debug("Found no entries for %s, skipping" % uuid)
            return
```

there are apparently no entries for this uuid in the timeseries database.
did the `moveToLongTerm` step work properly?
was there anything for it to move?

**Comment by montaguegabe** [comment]
There was nothing:
```
2022-06-16 18:11:08,626:INFO:140512258062144:processing UUID list = [UUID('6cb37491-6a98-4fb6-bf46-d526d9cec475')]
2022-06-16 18:11:08,640:INFO:140512258062144:**********UUID 6cb37491-6a98-4fb6-bf46-d526d9cec475: moving to long term**********
2022-06-16 18:11:09,234:DEBUG:140512258062144:Found 0 messages in response to query {'user_id': UUID('6cb37491-6a98-4fb6-bf46-d526d9cec475'), '$or': [{'metadata.type': 'message'}, {'metadata.type': 'sensor-data'}, {'metadata.type': 'rw-document'}]}
2022-06-16 18:11:09,235:DEBUG:140512258062144:No messages to process
2022-06-16 18:11:09,348:DEBUG:140512258062144:insert called with entry of type <class 'emission.core.wrapper.entry.Entry'>
2022-06-16 18:11:09,348:DEBUG:140512258062144:entry was fine, no need to fix it
2022-06-16 18:11:09,349:DEBUG:140512258062144:Inserting entry Entry ETC
```

**Comment by montaguegabe** [comment]
If it helps, I am able to list MongoDB documents in each of these storages:
![Screen Shot 2022-06-16 at 2 39 22 PM](https://user-images.githubusercontent.com/10249299/174142222-8af7ba78-8ce6-4e16-94ec-ba733a360240.png)

**Comment by shankari** [comment]
maybe the documents are not in the right format? The query that the pipeline runs is in the log - get the query to return values, and the rest of the pipeline will work.

**Comment by montaguegabe** [comment]
![Screen Shot 2022-06-16 at 2 54 47 PM](https://user-images.githubusercontent.com/10249299/174144601-556f46f7-93bd-4639-96c5-5cd45199160b.png)

It sounds like UUIDs should be data type, so this looks right. I just don't know how to get a user UUID I think

**Comment by shankari** [comment]
@montaguegabe any updates on this?

**Comment by montaguegabe** [comment]
Hi Shankari,

I realized the analysis server had been overwriting the database configuration as part of a script in the `em-server-multi-tier-cronjob` setup. I corrected this and now it connects to MongoDB. When I run `build_label_model` I get `Namespace(all=True, email_list=None, platform=None, user_list=None)
2022-06-24 03:20:35,302:INFO:received list with [] users`

I'm still confused - how do I get a user's UUID? Your explanation with python seems to presuppose that I have the string representation already, but I don't know how to get that - thanks!

**Comment by montaguegabe** [comment]
Inside the environment's python I run:
```
>>> esta.TimeSeries.get_uuid_list()
[]
```
So `get_uuid_list` returns no UUIDs

**Comment by montaguegabe** [comment]
Hi Shankari - the issue is that our data is split across two separate databases in MongoDB:

<img width="282" alt="Screen Shot 2022-06-24 at 12 13 46 AM" src="https://user-images.githubusercontent.com/10249299/175460921-2b970a60-0ec1-4128-aaac-cbc9d1483b14.png">

**Comment by montaguegabe** [comment]
At the risk of corrupting production data, I switched db.conf to talk to the Stage_database. Here is the error I got:
```
Namespace(all=True, email_list=None, platform=None, user_list=None)
Traceback (most recent call last):
  File "/usr/src/app/e-mission-server/bin/build_label_model.py", line 63, in <module>
    user_list = _get_user_list(args)
  File "/usr/src/app/e-mission-server/bin/build_label_model.py", line 18, in _get_user_list
    return _find_all_users()
  File "/usr/src/app/e-mission-server/bin/build_label_model.py", line 40, in _find_all_users
    return esta.TimeSeries.get_uuid_list()
  File "/usr/src/app/e-mission-server/emission/storage/timeseries/abstract_timeseries.py", line 37, in get_uuid_list
    import emission.storage.timeseries.builtin_timeseries as bits
  File "/usr/src/app/e-mission-server/emission/storage/timeseries/builtin_timeseries.py", line 19, in <module>
    esta.EntryType.DATA_TYPE: edb.get_timeseries_db(),
  File "/usr/src/app/e-mission-server/emission/core/get_database.py", line 178, in get_timeseries_db
    TimeSeries.create_index([("data.loc", pymongo.GEOSPHERE)])
  File "/root/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/pymongo/collection.py", line 2059, in create_index
    return self.__create_indexes([index], session, **cmd_options)[0]
  File "/root/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/pymongo/collection.py", line 1953, in __create_indexes
    session=session)
  File "/root/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/pymongo/collection.py", line 253, in _command
    user_fields=user_fields)
  File "/root/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/pymongo/pool.py", line 694, in command
    exhaust_allowed=exhaust_allowed)
  File "/root/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/pymongo/network.py", line 162, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/root/miniconda-4.8.3/envs/emission/lib/python3.7/site-packages/pymongo/helpers.py", line 168, in _check_command_response
    max_wire_version)
pymongo.errors.OperationFailure: An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, key: { data.loc: "2dsphere" }, name: "data.loc_2dsphere", 2dsphereIndexVersion: 3 }, existing index: { v: 2, key: { data.loc: "2dsphere" }, name: "data.loc_2dsphere", sparse: true, 2dsphereIndexVersion: 3 }, full error: {'ok': 0.0, 'errmsg': 'An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, key: { data.loc: "2dsphere" }, name: "data.loc_2dsphere", 2dsphereIndexVersion: 3 }, existing index: { v: 2, key: { data.loc: "2dsphere" }, name: "data.loc_2dsphere", sparse: true, 2dsphereIndexVersion: 3 }', 'code': 86, 'codeName': 'IndexKeySpecsConflict', '$clusterTime': {'clusterTime': Timestamp(1656044841, 21), 'signature': {'hash': b'\x0b_d{-\xa9,\x96\xd7m\xf2\xc5\xa9\x92C&\x99\xc5\xc9@', 'keyId': 7065361462666985501}}, 'operationTime': Timestamp(1656044841, 21)}
```

**Comment by shankari** [comment]
> `pymongo.errors.OperationFailure: An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, key: { data.loc: "2dsphere" }, name: "data.loc_2dsphere", 2dsphereIndexVersion: 3 }, existing index: { v: 2, key: { data.loc: "2dsphere" }, name: "data.loc_2dsphere", sparse: true, 2dsphereIndexVersion: 3 }, full error: {'ok': 0.0, 'errmsg': 'An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, key: { data.loc: "2dsphere" }, name: "data.loc_2dsphere", 2dsphereIndexVersion: 3 }, existing index: { v: 2, key: { data.loc: "2dsphere" }, name: "data.loc_2dsphere", sparse: true, 2dsphereIndexVersion: 3 }', 'code': 86, 'codeName': 'IndexKeySpecsConflict', '$clusterTime': {'clusterTime': Timestamp(1656044841, 21), 'signature': {'hash': b'\x0b_d{-\xa9,\x96\xd7m\xf2\xc5\xa9\x92C&\x99\xc5\xc9@', 'keyId': 7065361462666985501}}, 'operationTime': Timestamp(1656044841, 21)}`

I am pretty sure this is because of we changed the `data.loc` index to non-sparse to support DocumentDB (which is supposedly MongoDB compatible, but not fully). Simply dropping all the indexes will recreate them properly at the next connection - e.g. something like the following pseudo-code (untested code, do not copy paste)

```
import emission.core.get_database as edb
edb.Stage_database.Stage_timeseries.drop_indexes()
edb.Stage_database.Stage_analysis_timeseries.drop_indexes()
```

> I ran the analysis server commands without a proper db.conf at first, which would cause the database name to default to "Stage_database" but I have since fixed db.conf for the analysis server, so I would expect that "Cluster0" is the correct database name that should be working now, yet it doesn't. The only time the python is capable of fetching UUIDs is when it is talking to "Stage_database".

Maybe you also ran the webapp without a proper db.conf first? The db.conf is set up the same way in both containers. The uuid_db is (as you would expect) filled in when the user registers for the first time through the phone app -> webapp path.

**Comment by montaguegabe** [comment]
@shankari  thanks that seems to have fixed it! I am noticing `No such file or directory: 'seed_model.json'` during `intake_multiprocess`

as well as `'transition': 'T_GEOFENCE_CREATION_ERROR'`

**Comment by shankari** [comment]
You should use the `gis-based-mode-detection` branch. Otherwise, you need an sklearn random forest model saved to a file called `seed_model.json`, but I don't think you have one 😄

**Comment by montaguegabe** [comment]
Sounds good - will try that branch
