### ISSUE TITLE
App crashes on android 12 when trying to email logs

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#778]
Steps to reproduce:
- Build and install from master
- Go to profile
- "Email log"
- App crashes

```
08-19 15:23:57.890 32610  6855 E AndroidRuntime: Process: edu.berkeley.eecs.emission, PID: 32610
08-19 15:23:57.890 32610  6855 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
08-19 15:23:57.890 32610  6855 E AndroidRuntime: 	at java.util.ArrayList.remove(ArrayList.java:503)
08-19 15:23:57.890 32610  6855 E AndroidRuntime: 	at de.appplant.cordova.emailcomposer.Impl.getDraft(Impl.java:90)
08-19 15:23:57.890 32610  6855 E AndroidRuntime: 	at de.appplant.cordova.emailcomposer.EmailComposer$4.run(EmailComposer.java:173)
08-19 15:23:57.890 32610  6855 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-19 15:23:57.890 32610  6855 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-19 15:23:57.890 32610  6855 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
```

**Comment by shankari** [comment]
This is blocking #774 since I cannot email the logs to myself to see how the changes worked.

**Comment by shankari** [comment]
This is because `queryIntentActivities` returns an empty array on android 12.

#### Android 12

```
08-19 17:24:30.938 10619 12337 D EmailComposer: queryIntentActivities []
08-19 17:24:30.938 10619 12337 D EmailComposer: getEmailClients returning []
08-19 17:24:30.938 10619 12337 D EmailComposer: getEmailClientIds []
08-19 17:24:30.938 10619 12337 D EmailComposer: about to return targets []
```

#### Android 10

```
08-19 16:04:53.359 28522 28635 D EmailComposer: queryIntentActivities [ResolveInfo{1016e76 com.google.android.gm/.ComposeActivityGmailExternal m=0x208000}]
08-19 16:04:53.359 28522 28635 D EmailComposer: getEmailClients returning [ActivityInfo{2882c77 com.google.android.gm.ComposeActivityGmailExternal}]
08-19 16:04:53.359 28522 28635 D EmailComposer: getEmailClientIds [com.google.android.gm]
08-19 16:04:53.359 28522 28635 D EmailComposer: about to return targets [Intent { act=android.intent.action.SEND typ=*/* flg=0x11008001 pkg=com.google.android.gm (has extras) }]
```

**Comment by shankari** [comment]
It turns out that this because android 11 apparently requires `QUERY_ALL_PACKAGES` to call `queryIntentActivities`
https://stackoverflow.com/questions/65629268/queryintentactivities-returning-empty-list-in-android-11

which is documented here:
https://developer.android.com/training/package-visibility

**Comment by shankari** [comment]
Worked around it by applying this fix
https://github.com/katzer/cordova-plugin-email-composer/commit/8a75c665fe505a6a620d876069339c45f8b4b2f1

Looks like installing from github should also work for the long term.
But for now, I am unblocked on #774

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/881/commits/7916f0320b7b84af72b321ddbbe6deab36218c47
by bumping up version number
