### ISSUE TITLE
Regression in existing pipeline reset test

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#806]
While working on #805, I ran the existing pipeline to double check that it works, and found a couple of regressions.

```
======================================================================
FAIL: testResetToTsInMiddleOfPlace (__main__.TestPipelineReset)
- Load data for both days
----------------------------------------------------------------------
Traceback (most recent call last):
  File "emission/tests/pipelineTests/TestPipelineReset.py", line 223, in testResetToTsInMiddleOfPlace
    ad.AttrDict(ground_truth_1).data)
  File "emission/tests/pipelineTests/TestPipelineReset.py", line 59, in compare_result
    self.assertEqual(len(result), len(expect))
AssertionError: 7 != 4

======================================================================
FAIL: testResetToTsInMiddleOfTrip (__main__.TestPipelineReset)
- Load data for both days
----------------------------------------------------------------------
Traceback (most recent call last):
  File "emission/tests/pipelineTests/TestPipelineReset.py", line 287, in testResetToTsInMiddleOfTrip
    ad.AttrDict(ground_truth_1).data)
  File "emission/tests/pipelineTests/TestPipelineReset.py", line 59, in compare_result
    self.assertEqual(len(result), len(expect))
AssertionError: 7 != 4

----------------------------------------------------------------------
```

Let's fix them now, and then see why the CI didn't fail for these tests. If the tests are failing but report success, we may have more lurking bugs than we might know of!

**Comment by shankari** [comment]
Looking at the first of the two tests:

When the trips were retrieved before the reset, there were 5 trips across both days, and 4 trips on the 22nd

```
2022-10-05 14:29:16,144:DEBUG:4358970880:keys = (analysis/cleaned_place, analysis/confirmed_trip), len(places) = 4, len(trips) = 5

2022-10-05 14:29:16,143:DEBUG:4358970880:Considering trip 633df7284fada57441f0c2b5: 2016-07-22T09:26:08-07:00 -> 2016-07-22T11:44:50-07:00 
2022-10-05 14:29:16,144:DEBUG:4358970880:Considering trip 633df7284fada57441f0c2b6: 2016-07-22T16:38:06.693176-07:00 -> 2016-07-22T16:51:13-07:00 
2022-10-05 14:29:16,144:DEBUG:4358970880:Considering trip 633df7284fada57441f0c2b7: 2016-07-22T16:59:46.998718-07:00 -> 2016-07-22T17:05:52.818000-07:00 
2022-10-05 14:29:16,144:DEBUG:4358970880:Considering trip 633df72c4fada57441f0c30d: 2016-07-22T17:12:19.019962-07:00 -> 2016-07-22T17:21:36-07:00 
```

When the trips were retrieved after the reset, there were 8 trips, including 4 copies of the same trip, highlighted below.

```
2022-10-05 14:29:24,162:DEBUG:4358970880:keys = (analysis/cleaned_place, analysis/confirmed_trip), len(places) = 4, len(trips) = 8

2022-10-05 14:29:24,161:DEBUG:4358970880:Considering trip 633df7284fada57441f0c2b5: 2016-07-22T09:26:08-07:00 -> 2016-07-22T11:44:50-07:00 

2022-10-05 14:29:24,162:DEBUG:4358970880:Considering trip 633df7284fada57441f0c2b6: 2016-07-22T16:38:06.693176-07:00 -> 2016-07-22T16:51:13-07:00 
2022-10-05 14:29:24,162:DEBUG:4358970880:Considering trip 633df7344fada57441f0c387: 2016-07-22T16:38:06.693176-07:00 -> 2016-07-22T16:51:13-07:00 
2022-10-05 14:29:24,162:DEBUG:4358970880:Considering trip 633df7344fada57441f0c388: 2016-07-22T16:38:06.693176-07:00 -> 2016-07-22T16:51:13-07:00 
2022-10-05 14:29:24,162:DEBUG:4358970880:Considering trip 633df7344fada57441f0c389: 2016-07-22T16:38:06.693176-07:00 -> 2016-07-22T16:51:13-07:00 

2022-10-05 14:29:24,162:DEBUG:4358970880:Considering trip 633df7344fada57441f0c38a: 2016-07-22T16:59:46.998718-07:00 -> 2016-07-22T17:05:52.818000-07:00 
2022-10-05 14:29:24,162:DEBUG:4358970880:Considering trip 633df7344fada57441f0c38b: 2016-07-22T17:12:19.019962-07:00 -> 2016-07-22T17:21:36-07:00 
2022-10-05 14:29:24,162:DEBUG:4358970880:Considering trip 633df7334fada57441f0c34d: 2016-07-22T17:21:36-07:00 -> 2016-07-25T17:12:27.853000-07:00 
```

Let's dig deeper to see what is causing the duplicate trips.

**Comment by shankari** [comment]
Of the duplicate trips, note that the first one is different and the three duplicates seem to have been created in quick succession.

Searching through the log for the first instance of the first duplicate ID (633df7344fada57441f0c387), it is after the pipeline has finished running?!

```
2022-10-05 14:29:24,121:INFO:4358970880:For stage PipelineStages.CREATE_CONFIRMED_OBJECTS, last_ts_processed = 2016-07-26T00:30:36
2022-10-05 14:29:24,162:DEBUG:4358970880:Considering trip 633df7344fada57441f0c387: 2016-07-22T16:38:06.693176-07:00 -> 2016-07-22T16:51:13-07:00 
```

**Comment by shankari** [comment]
The confirmed trip stage finds 7 expected trips that it needs to map. Those are presumably the four duplicate trips and the 3 trips after.

How do we find these trips? By searching against the `data.ts`

```
2022-10-05 14:29:23,972:DEBUG:4358970880:curr_query = {'user_id': UUID('75403cf7-d128-4349-8834-47b9c5ec375c'), '$or': [{'metadata.key': 'analysis/expected_trip'}], 'data.end_ts': {'$lte': 1665005358.968599, '$gte': 1469231473}}, sort_key = data.end_ts
2022-10-05 14:29:23,975:DEBUG:4358970880:finished querying values for ['analysis/expected_trip'], count = 7
2022-10-05 14:29:23,979:DEBUG:4358970880:Returning entry with length 7 result
2022-10-05 14:29:23,998:DEBUG:4358970880:Converting 7 expected trips to confirmed ones
```

Is this because of `lte`/`gte` issues and the fact that we are querying based on the `data.ts` right now? Yup.

```
>>> arrow.get(1469231473).to("America/Los_Angeles")
2016-07-22T16:51:13-07:00
```

And I think we end up with multiple copies because of all the intermediate steps for the inferred labels.
How do we handle this for the existing reset values?

**Comment by shankari** [comment]
I can confirm that changing one line from `get_confirmed_timeline_from_dt` to `get_cleaned_timeline_from_dt` causes the test to pass. So this was a regression in https://github.com/e-mission/e-mission-server/commit/78a3ebb612077bea923d922e6cdfbca4ccfa1921

```
def get_geojson_for_dt(user_id, start_local_dt, end_local_dt):
    logging.debug("Getting geojson for %s -> %s" % (start_local_dt, end_local_dt))
    tl = esdtl.get_confirmed_timeline_from_dt(user_id, start_local_dt, end_local_dt)
    tl.fill_start_end_places()
    return get_geojson_for_timeline(user_id, tl)
```

Although we still end up with 7 expected trips to process so the actual regression was many commits ago, and the most recent regression would have just exposed it.

```
2022-10-05 16:14:56,274:DEBUG:4494208512:curr_query = {'user_id': UUID('cc092c68-3a31-4075-bc78-69f70c8e6ff6'), '$or': [{'metadata.key': 'analysis/expected_trip'}], 'data.end_ts': {'$lte': 1665011691.271411, '$gte': 1469231473}}, sort_key = data.end_ts
2022-10-05 16:14:56,275:DEBUG:4494208512:finished querying values for ['analysis/expected_trip'], count = 7
2022-10-05 16:14:56,275:DEBUG:4494208512:orig_ts_db_matches = 0, analysis_ts_db_matches = 7
2022-10-05 16:14:56,279:DEBUG:4494208512:Returning entry with length 7 result
2022-10-05 16:14:56,279:DEBUG:4494208512:Converting 7 expected trips to confirmed ones
```

**Comment by shankari** [comment]
>  How do we handle this for the existing reset values?

Working backwards, we get:

```
2022-10-05 16:14:56,243:INFO:4494208512:For stage PipelineStages.EXPECTATION_POPULATION, start_ts = 2016-07-22T23:51:13
2022-10-05 16:14:56,246:DEBUG:4494208512:curr_query = {'user_id': UUID('cc092c68-3a31-4075-bc78-69f70c8e6ff6'), '$or': [{'metadata.key': 'analysis/inferred_trip'}], 'data.end_ts': {'$lte': 1665011691.24387, '$gte': 1469231473}}, sort_key = data.end_ts
2022-10-05 16:14:56,248:DEBUG:4494208512:finished querying values for ['analysis/inferred_trip'], count = 6
2022-10-05 16:14:56,252:DEBUG:4494208512:Returning entry with length 6 result
```

```
2022-10-05 16:14:56,173:INFO:4494208512:For stage PipelineStages.LABEL_INFERENCE, start_ts = 2016-07-22T23:51:13
2022-10-05 16:14:56,176:DEBUG:4494208512:curr_query = {'user_id': UUID('cc092c68-3a31-4075-bc78-69f70c8e6ff6'), '$or': [{'metadata.key': 'analysis/cleaned_trip'}], 'data.end_ts': {'$lte': 1665011691.1737978, '$gte': 1469231473}}, sort_key = data.end_ts
2022-10-05 16:14:56,178:DEBUG:4494208512:finished querying values for ['analysis/cleaned_trip'], count = 5
2022-10-05 16:14:56,178:DEBUG:4494208512:orig_ts_db_matches = 0, analysis_ts_db_matches = 5
2022-10-05 16:14:56,181:DEBUG:4494208512:Returning entry with length 5 result
```

Actually, even for mode inference, we have the search by `data.end_ts`

```
2022-10-05 16:14:56,157:INFO:4494208512:For stage PipelineStages.MODE_INFERENCE, start_ts is None
2022-10-05 16:14:56,161:DEBUG:4494208512:curr_query = {'user_id': UUID('cc092c68-3a31-4075-bc78-69f70c8e6ff6'), '$or': [{'metadata.key': 'analysis/cleaned_section'}], 'data.end_ts': {'$lte': 1665011691.157681}}, sort_key = data.end_ts
2022-10-05 16:14:56,162:DEBUG:4494208512:finished querying values for ['analysis/cleaned_section'], count = 11
2022-10-05 16:14:56,167:DEBUG:4494208512:Returning entry with length 11 result
```

```
2022-10-05 16:14:56,143:DEBUG:4494208512:Finished creating and linking timeline, returning 5 places and 5 trips
2022-10-05 16:14:56,143:DEBUG:4494208512:keys = (analysis/cleaned_place, analysis/cleaned_trip), len(places) = 5, len(trips) = 5
```

**Comment by shankari** [comment]
Couple of notes from digging into the pipeline code.
- when we mark a particular pipeline state as done, we typically add a
  FUZZ_AVOID_LTE parameter to perturb the "done" slightly so that the same
  entry would not show up over and over. Not sure if we are doing this during the reset
- the timeType for all entries after section segmentation is based on
  data.end_ts; maybe we should change the default :)
- all this still doesn't explain why we go from 5 raw trips to 5 cleaned trips
  to 6 inferred trips to 7 expected trips. Why don't we go from 5 raw trips to
  6 cleaned trips? I wonder if we are deleting entries during the reset properly

We definitely delete all entries that start after the reset timestamp

```
    # handle all trip-like entries
    date_query_list.append({"data.start_ts": {"$gt": reset_ts}})
```

Let's see what happens with that when we delete

when we delete, we get 

```
2022-10-05 14:29:18,761:DEBUG:4358970880:last_place_enter_ts = 1469231473
2022-10-05 14:29:18,761:DEBUG:4358970880:reset_ts = 1469231473

>>> arrow.get(1469231473).to("America/Los_Angeles")
<Arrow [2016-07-22T16:51:13-07:00]>
```

and we delete a bunch of entries

```
2022-10-05 14:29:18,853:INFO:4358970880:About to delete 108 entries
2022-10-05 14:29:18,947:INFO:4358970880:About to delete entries with keys ['analysis/cleaned_place', 'analysis/cleaned_section', 'analysis/cleaned_trip', 'analysis/cleaned_untracked', 'analysis/confirmed_trip', 'analysis/expected_trip', 'analysis/inferred_labels', 'analysis/inferred_trip', 'analysis/recreated_location', 'inference/labels', 'segmentation/raw_place', 'segmentation/raw_section', 'segmentation/raw_trip', 'segmentation/raw_untracked']
```

Before the reset, the trips were

```
2022-10-05 14:29:17,939:DEBUG:4358970880:Comparing 2016-07-22T09:26:08-07:00 -> 2016-07-22T11:44:50-07:00 with 2016-07-22T09:26:08-07:00 -> 2016-07-22T11:44:50-07:00
2022-10-05 14:29:17,939:DEBUG:4358970880:Comparing 2016-07-22T16:38:06.693176-07:00 -> 2016-07-22T16:51:13-07:00 with 2016-07-22T16:38:06.693176-07:00 -> 2016-07-22T16:51:13-07:00
2022-10-05 14:29:17,939:DEBUG:4358970880:Comparing 2016-07-22T16:59:46.998718-07:00 -> 2016-07-22T17:05:52.818000-07:00 with 2016-07-22T16:59:46.998718-07:00 -> 2016-07-22T17:05:52.818000-07:00
2022-10-05 14:29:17,939:DEBUG:4358970880:Comparing 2016-07-22T17:12:19.019962-07:00 -> 2016-07-22T17:21:36-07:00 with 2016-07-22T17:12:19.019962-07:00 -> 2016-07-22T17:21:36-07:00
```

So 16:51 is an eminently fine place to end.

We will then retain this trip because the start is not greater than the reset.
And then, because of the lte, the trip is returned along with the newly created
ones, and we get our ever-increasing list.

I can even understand why this is not a problem for raw trips, but not sure why it is not for cleaned trips

```
2022-10-05 14:29:17,939:DEBUG:4358970880:Comparing 2016-07-22T16:38:06.693176-07:00 -> 2016-07-22T16:51:13-07:00 with 2016-07-22T16:38:06.693176-07:00 -> 2016-07-22T16:51:13-07:00
```

Query to get raw trips while cleaning

```
2022-10-05 14:29:22,447:DEBUG:4358970880:curr_query = {'user_id': UUID('75403cf7-d128-4349-8834-47b9c5ec375c'), '$or': [{'metadata.key': 'segmentation/raw_trip'}, {'metadata.key': 'segmentation/raw_untracked'}], 'data.start_ts': {'$lte': 1665005357.4372952, '$gte': 1469231473}}, sort_key = data.start_ts
```

Query to get cleaned trips for label inference

```
2022-10-05 14:29:23,777:DEBUG:4358970880:curr_query = {'user_id': UUID('75403cf7-d128-4349-8834-47b9c5ec375c'), '$or': [{'metadata.key': 'analysis/cleaned_trip'}], 'data.end_ts': {'$lte': 1665005358.773799, '$gte': 1469231473}}, sort_key = data.end_ts
2022-10-05 14:29:23,779:DEBUG:4358970880:finished querying values for ['analysis/cleaned_trip'], count = 5
```

**Comment by shankari** [comment]
At this point, although we don't fully understand the cleaned_trip issue, we do have some answers.

> Let's fix them now, and then see why the CI didn't fail for these tests. If the tests are failing but report success, we may have more lurking bugs than we might know of!

This is because this directory does not have an `__init__.py`, and so is not found by `discover`. It looks like all these tests actually fail.

**Comment by shankari** [comment]
So I actually commented out the latter part of the test and manually printed out the raw_trip, cleaned_trip and confirmed_trip and they all have the same

```
                     start_fmt_time               end_fmt_time
0         2016-07-22T09:26:08-07:00  2016-07-22T11:44:50-07:00
1  2016-07-22T16:40:23.024000-07:00  2016-07-22T16:51:13-07:00

                     start_fmt_time               end_fmt_time
0         2016-07-22T09:26:08-07:00  2016-07-22T11:44:50-07:00
1  2016-07-22T16:38:06.693176-07:00  2016-07-22T16:51:13-07:00

                     start_fmt_time               end_fmt_time
0         2016-07-22T09:26:08-07:00  2016-07-22T11:44:50-07:00
1  2016-07-22T16:38:06.693176-07:00  2016-07-22T16:51:13-07:00
```

At this point, I'm going to defer this last issue until later and see if I can fix the tests.

**Comment by shankari** [comment]
We do actually apply the FUZZ factor for trip segmentation and we don't apply it for non-trip segmentation because of
https://github.com/e-mission/e-mission-docs/issues/191#issuecomment-312917119

At this point, I am tempted to just special case the last three label assist stages and add the FUZZ there as well

**Comment by shankari** [comment]
Trying to fix it by adding a FUZZ to all the label assist classes; now we don't find any matching cleaned trips and the test fails

```
2022-10-05 22:52:01,147:INFO:4712373760:For stage PipelineStages.LABEL_INFERENCE, start_ts = 2016-07-26T00:30:36
2022-10-05 22:52:01,151:DEBUG:4712373760:curr_query = {'user_id': UUID('f89432a7-a4bb-4f2a-ac30-337a5162e721'), '$or': [{'metadata.key': 'analysis/cleaned_trip'}], 'data.end_ts': {'$lte': 1665035516.148017, '$gte': 1469493036.0}}, sort_key = data.end_ts
2022-10-05 22:52:01,151:DEBUG:4712373760:orig_ts_db_keys = [], analysis_ts_db_keys = ['analysis/cleaned_trip']
2022-10-05 22:52:01,153:DEBUG:4712373760:finished querying values for ['analysis/cleaned_trip'], count = 0
2022-10-05 22:52:01,155:DEBUG:4712373760:Returning entry with length 0 result
```

Note that the last processed ts seems to be pretty high, higher than one would imagine and also higher than the previous stages

```
2022-10-05 22:51:59,839:INFO:4712373760:For stage PipelineStages.CLEAN_RESAMPLING, start_ts = 2016-07-22T23:51:13
2022-10-05 22:52:01,101:INFO:4712373760:For stage PipelineStages.CLEAN_RESAMPLING, last_ts_processed = 2016-07-26T00:30:36

2022-10-05 22:52:01,147:INFO:4712373760:For stage PipelineStages.LABEL_INFERENCE, start_ts = 2016-07-26T00:30:36
2022-10-05 22:52:01,147:INFO:4712373760:For stage PipelineStages.LABEL_INFERENCE, start_ts = 2016-07-26T00:30:36
...
```

Note that the original fuzzified stage still has the correct timestamp

```
2022-10-05 22:51:57,205:INFO:4712373760:For stage PipelineStages.TRIP_SEGMENTATION, start_ts = 2016-07-22T23:56:13
```

**Comment by shankari** [comment]
This is because we forgot to set `multi=True` for the fuzzed updates, so only the first state was updated.
After fixing that, all existing tests pass.
