### ISSUE TITLE
cannot encode object: Arrow in the stage pipeline

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#860]
Found that my trips had not processed overnight. After much wrestling with AWS logs, found that this was because of

```
2023-03-09 01:09:36,167:INFO:139996284163904:**********UUID 9c084ef4-2f97-4196-bd37-950c17938ec6: moving to long term**********
2023-03-09 01:09:36,687:ERROR:139996284163904:Found error cannot encode object: <Arrow [2023-03-09T01:09:36.568759+00:00]>, of type: <class 'arrow.arrow.Arrow'> while processing pipeline for user 9c084ef4-2f97-4196-bd37-950c17938ec6, skipping
```

<details>
<summary>Full logs are here</summary>

```
2023-03-09 01:09:36,503:DEBUG:139996284163904:Found 2434 messages in response to query {'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), '$or': [{'metadata.type': 'message'}, {'metadata.type': 'sensor-data'}, {'metadata.type': 'rw-document'}]}
2023-03-09 01:09:36,506:DEBUG:139996284163904:About to save object PipelineState({'_id': ObjectId('62abd513403ef600bd32e40f'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 0, 'curr_run_ts': 1678324171.506532, 'last_processed_ts': 1678319632.152, 'last_ts_run': 1678320557.545079})
2023-03-09 01:09:36,513:DEBUG:139996284163904:After saving state PipelineState({'_id': ObjectId('62abd513403ef600bd32e40f'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 0, 'curr_run_ts': 1678324171.506532, 'last_processed_ts': 1678319632.152, 'last_ts_run': 1678320557.545079}), list is [{'_id': ObjectId('62ab76aea73d8a3b648e9d5c'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 2, 'curr_run_ts': None, 'last_processed_ts': 1678319478.968, 'last_ts_run': 1678320602.4475164}, {'_id': ObjectId('62ab76b0a73d8a3b648e9d69'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 3, 'curr_run_ts': None, 'last_processed_ts': 1678319478.968, 'last_ts_run': 1678320616.4690325}, {'_id': ObjectId('62f6614a349a250e2c47dfeb'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 16, 'curr_run_ts': None, 'last_processed_ts': 1672969112.385, 'last_ts_run': 1678323696.2709243}, {'_id': ObjectId('62ab76e1a73d8a3b648e9e92'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 9, 'curr_run_ts': None, 'last_processed_ts': None, 'last_ts_run': 1678320627.11383}, {'_id': ObjectId('62ab769da73d8a3b648e9d49'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 6, 'curr_run_ts': None, 'last_processed_ts': None, 'last_ts_run': 1678320561.4625926}, {'_id': ObjectId('62ab769da73d8a3b648e9d4b'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 1, 'curr_run_ts': None, 'last_processed_ts': 1678319632.117, 'last_ts_run': 1678320561.4861522}, {'_id': ObjectId('62ab76b4a73d8a3b648e9e67'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 4, 'curr_run_ts': None, 'last_processed_ts': 1678319355.491, 'last_ts_run': 1678320623.9572968}, {'_id': ObjectId('62abd513403ef600bd32e40f'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 0, 'curr_run_ts': 1678324171.506532, 'last_processed_ts': 1678319632.152, 'last_ts_run': 1678320557.545079}, {'_id': ObjectId('62ab76e1a73d8a3b648e9e69'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 14, 'curr_run_ts': None, 'last_processed_ts': 1678319355.491, 'last_ts_run': 1678320626.0723188}, {'_id': ObjectId('62ab76e1a73d8a3b648e9e80'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 15, 'curr_run_ts': None, 'last_processed_ts': 1678319355.491, 'last_ts_run': 1678320626.8239987}, {'_id': ObjectId('62ab769da73d8a3b648e9d47'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 12, 'curr_run_ts': None, 'last_processed_ts': 1672973050.94, 'last_ts_run': 1678320558.013414}, {'_id': ObjectId('62ab76b0a73d8a3b648e9d74'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 11, 'curr_run_ts': None, 'last_processed_ts': 1678319478.968, 'last_ts_run': 1678320619.4597182}, {'_id': ObjectId('62ab76e1a73d8a3b648e9e89'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'pipeline_stage': 13, 'curr_run_ts': None, 'last_processed_ts': 1678319355.491, 'last_ts_run': 1678320626.909081}]
2023-03-09 01:09:36,525:DEBUG:139996284163904:Found 126 messages in response to query {'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), '$or': [{'metadata.type': 'message'}, {'metadata.type': 'sensor-data'}, {'metadata.type': 'rw-document'}], 'metadata.write_ts': {'$lte': 1678324171.506532, '$gte': 1678319632.152}}
2023-03-09 01:09:36,681:DEBUG:139996284163904:Inserting entry Entry({'_id': ObjectId('640931d0b3a81ef266a186a3'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'metadata': Metadata({'key': 'stats/pipeline_error', 'platform': 'server', 'write_ts': 1678324176.6808336, 'time_zone': 'America/Los_Angeles', 'write_local_dt': LocalDate({'year': 2023, 'month': 3, 'day': 8, 'hour': 17, 'minute': 9, 'second': 36, 'weekday': 2, 'timezone': 'America/Los_Angeles'}), 'write_fmt_time': '2023-03-08T17:09:36.680834-08:00'}), 'data': {'name': 'WHOLE_PIPELINE', 'ts': 1678324176.680776, 'reading': None}}) into timeseries
2023-03-09 01:09:36,687:ERROR:139996284163904:Found error cannot encode object: <Arrow [2023-03-09T01:09:36.568759+00:00]>, of type: <class 'arrow.arrow.Arrow'> while processing pipeline for user 9c084ef4-2f97-4196-bd37-950c17938ec6, skipping
2023-03-09T01:09:36.167856+00:00**********UUID 9c084ef4-2f97-4196-bd37-950c17938ec6: moving to long term**********
```

</details>

**Comment by shankari** [comment]
Backtrace is pretty straightforward. We have to find the actual entry which has an arrow object instead of a timestamp.


```
2023-03-09 01:09:36,687:ERROR:139996284163904:Found error cannot encode object: <Arrow [2023-03-09T01:09:36.568759+00:00]>, of type: <class 'arrow.arrow.Arrow'> while processing pipeline for user 9c084ef4-2f97-4196-bd37-950c17938ec6, skipping
--
Traceback (most recent call last):
File "/usr/src/app/emission/pipeline/intake_stage.py", line 73, in run_intake_pipeline
run_intake_pipeline_for_user(uuid)
File "/usr/src/app/emission/pipeline/intake_stage.py", line 85, in run_intake_pipeline_for_user
uh.moveToLongTerm()
File "/usr/src/app/emission/net/usercache/builtin_usercache_handler.py", line 93, in moveToLongTerm
ts.bulk_insert(unified_entry_list, etsa.EntryType.DATA_TYPE)
File "/usr/src/app/emission/storage/timeseries/builtin_timeseries.py", line 360, in bulk_insert
multi_result = ts_enum_map[data_type].insert_many(entries, ordered=False)
File "/root/miniconda-4.12.0/envs/emission/lib/python3.7/site-packages/pymongo/collection.py", line 761, in insert_many
blk.execute(write_concern, session=session)
File "/root/miniconda-4.12.0/envs/emission/lib/python3.7/site-packages/pymongo/bulk.py", line 528, in execute
return self.execute_command(generator, write_concern, session)
File "/root/miniconda-4.12.0/envs/emission/lib/python3.7/site-packages/pymongo/bulk.py", line 360, in execute_command
self.is_retryable, retryable_bulk, s, self)
File "/root/miniconda-4.12.0/envs/emission/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
return self._retry_internal(retryable, func, session, bulk)
File "/root/miniconda-4.12.0/envs/emission/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1416, in _retry_internal
return func(session, sock_info, retryable)
File "/root/miniconda-4.12.0/envs/emission/lib/python3.7/site-packages/pymongo/bulk.py", line 355, in retryable_bulk
retryable, full_result)
File "/root/miniconda-4.12.0/envs/emission/lib/python3.7/site-packages/pymongo/bulk.py", line 309, in _execute_command
result, to_send = bwc.execute(ops, client)
File "/root/miniconda-4.12.0/envs/emission/lib/python3.7/site-packages/pymongo/message.py", line 906, in execute
request_id, msg, to_send = self._batch_command(docs)
File "/root/miniconda-4.12.0/envs/emission/lib/python3.7/site-packages/pymongo/message.py", line 900, in _batch_command
self.codec, self)
File "/root/miniconda-4.12.0/envs/emission/lib/python3.7/site-packages/pymongo/message.py", line 1398, in _do_bulk_write_command
namespace, operation, command, docs, check_keys, opts, ctx)
File "/root/miniconda-4.12.0/envs/emission/lib/python3.7/site-packages/pymongo/message.py", line 1323, in _do_batched_op_msg
operation, command, docs, check_keys, ack, opts, ctx)
bson.errors.InvalidDocument: cannot encode object: <Arrow [2023-03-09T01:09:36.568759+00:00]>, of type: <class 'arrow.arrow.Arrow'>
```

**Comment by shankari** [comment]
note also that the entries were saved into the usercache just fine. So the arrow must be inserted when we run the pipeline, in the formatting stage.

**Comment by shankari** [comment]
Bingo! From `emission/net/usercache/formatters/android/trip_addition_input.py`

```
def format(entry):
    import arrow

    entry["data"]["start_ts"] = 0
    entry["data"]["end_ts"] = arrow.get()
    return fgl.format(entry)
```

What I don't understand is how this ever worked

**Comment by shankari** [comment]
> What I don't understand is how this ever worked

It's because this is only on android. On iOS, we don't overwrite the start and end timestamp
And we only test on iOS with the emulator
And this was not caught during the code review either

I am not even sure why I added it; removing, redeploying, and resetting the pipeline

**Comment by shankari** [comment]
Reset the pipeline, it ran successfully.
Fixed in https://github.com/e-mission/e-mission-server/pull/895/commits/01e0bb31cd0bb45a638344a45ba446a3d7bc8de7
