### ISSUE TITLE
Error while matching trip additions on the server

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#861]
```
Traceback (most recent call last):

File "/usr/src/app/emission/analysis/userinput/matcher.py", line 81, in create_confirmed_objects
last_expected_trip_done = create_confirmed_trips(user_id, time_query)
File "/usr/src/app/emission/analysis/userinput/matcher.py", line 110, in create_confirmed_trips
esdt.get_additions_for_trip_object(ts, tct)
File "/usr/src/app/emission/storage/decorations/trip_queries.py", line 191, in get_additions_for_trip_object
return get_not_deleted_candidates(valid_user_input(ts, trip_obj), potential_candidates)
File "/usr/src/app/emission/storage/decorations/trip_queries.py", line 168, in get_not_deleted_candidates
not_deleted_active = [efpc for efpc in all_active_list if efpc["match_id"] not in all_deleted_id]
File "/usr/src/app/emission/storage/decorations/trip_queries.py", line 168, in <listcomp>
not_deleted_active = [efpc for efpc in all_active_list if efpc["match_id"] not in all_deleted_id]
KeyError: 'match_id'
```

**Comment by shankari** [comment]
```
>>> all_additions = pd.json_normalize(list(edb.get_timeseries_db().find({"metadata.key": "manual/trip_addition_input"})))
>>> all_additions.columns
Index(['_id', 'user_id', 'metadata.key', 'metadata.platform',
       'metadata.read_ts', 'metadata.time_zone', 'metadata.type',
       'metadata.write_ts', 'metadata.write_local_dt.year',
       'metadata.write_local_dt.month', 'metadata.write_local_dt.day',
       'metadata.write_local_dt.hour', 'metadata.write_local_dt.minute',
       'metadata.write_local_dt.second', 'metadata.write_local_dt.weekday',
       'metadata.write_local_dt.timezone', 'metadata.write_fmt_time',
       'data.label', 'data.name', 'data.version', 'data.xmlResponse',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.attr.xmlns:jr',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.attr.xmlns:orx',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.attr.id',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.start',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.end',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.Date',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.Start_time',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.End_time',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.Activity_Type',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.Personal_Care_activities',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.Employment_related_a_Education_activities',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.Domestic_activities',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.Recreation_and_leisure',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.Voluntary_work_and_care_activities',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.Other',
       'data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.meta.instanceID',
       'data.start_ts', 'data.end_ts', 'data.match_id',
       'data.start_local_dt.year', 'data.start_local_dt.month',
       'data.start_local_dt.day', 'data.start_local_dt.hour',
       'data.start_local_dt.minute', 'data.start_local_dt.second',
       'data.start_local_dt.weekday', 'data.start_local_dt.timezone',
       'data.start_fmt_time', 'data.end_local_dt.year',
       'data.end_local_dt.month', 'data.end_local_dt.day',
       'data.end_local_dt.hour', 'data.end_local_dt.minute',
       'data.end_local_dt.second', 'data.end_local_dt.weekday',
       'data.end_local_dt.timezone', 'data.end_fmt_time', 'data.status'],
      dtype='object')
```

**Comment by shankari** [comment]
Huh. All the trip addition inputs do have a match id

```
>>> all_additions[["data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.Activity_Type", "data.match_id"]]
  data.jsonDocResponse.a88RxBtE3jwSar3cwiZTdn.group_hg4zz25.Activity_Type                         data.match_id
0       personal_care_activities domestic_activities                       e97af965-b2c1-4745-897a-f25d9628cac6
1                                              other                       86efc21f-36a5-4c30-95fe-a0e7392296e0
2                                              other                       01a14662-bcba-44a5-8f63-3232036c06ef
3                                              other                       86efc21f-36a5-4c30-95fe-a0e7392296e0
4                                              other                       f6968c46-91cc-407d-b471-2cdb969fbe02
```

**Comment by shankari** [comment]
Ah, we are looking for the `match_id` in the main object and not in data

```
not_deleted_active = [efpc for efpc in all_active_list if efpc["match_id"] not in all_deleted_id]
KeyError: 'match_id'
```

This matching only happens if the user filled in the input when the trip was in draft mode. If the user filled in when it was in cleaned mode, a different matching algorithm would run. So I suspect we didn't actually test out the draft mode use case.

**Comment by shankari** [comment]
Actually, we use the `match_id` directly from the entry in both cases, but ONLY for deleted entries.
I bet we didn't test running the pipeline with deleted entries.

```
    elif ui.data.status == ecwtui.InputStatus.DELETED:
        after_del_list = [ta for ta in confirmed_trip["data"]["trip_addition"] if ta["match_id"] != ui["match_id"]]
        confirmed_trip["data"]["trip_addition"] = after_del_list
```

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-server/pull/895/commits/9aed65d5948e61ba284e5a3ee29b4f9bc2b81290
