### ISSUE TITLE
Error on initial click of "Dashboard" [phone] [staging]

### ISSUE THREAD

**Issue by JGreenlee** [e-mission/e-mission-docs#862]
On staging v1.1.5. OnePlus 6T Android 11

```
Error loading aggregate data, averages not available
Cannot read properties of undefined (reading 'unlabeled')
TypeError: Cannot read properties of undefined (reading 'unlabeled')
  at cc.getMet (https://localhost/js/metrics-factory.js:195:21)
  at $scope.fillCalorieAggVals (https://localhost/js/metrics.js:780:34)
  at $scope.fillAggregateValues (https://localhost/js/metrics.js:669:16)
  at https://localhost/js/metrics.js:569:18
```

<img src="https://user-images.githubusercontent.com/15843932/224392268-25c727f7-27bb-4a95-ae7d-661092996cf4.png" height="500">

**Comment by JGreenlee** [comment]
```js
let currentMETs = cc.getMETs();
if (!currentMETs[mode]) {
  console.warn("CalorieCal.getMet() Illegal mode: " + mode);
  return defaultIfMissing; //So the calorie sum does not break with wrong return type
}
```
This occurs when `mode` is `"unlabeled"`.
I think we just need to more safely check if the `mode` exists on `currentMETs`. We can use optional chaining `if (!currentMETs?.[mode]) ...`

**Comment by allenmichael099** [comment]
I'm getting a similar issue with staging v1.1.8 on iPhone 7 Plus and iPhone 8. "undefined is not an object." Sending logs shortly.
<img src="https://user-images.githubusercontent.com/56986329/226478004-dbce52f4-9913-4f03-89a9-20cfd5315930.PNG" width=35% height=20%>

**Comment by shankari** [comment]
I ran into a similar issue on the staging environment while testing out a new token that had no associated trips.

<img src="https://user-images.githubusercontent.com/2423263/226816797-60a13f59-c1c8-4b6c-95c0-ebc2b858df7b.png" width="320px"/>

```
TypeError: Cannot read property 'toFixed' of undefined
    at humanize (https://localhost/js/metrics.js:1437:32)
    at link (https://localhost/js/metrics.js:1444:28)
    at https://localhost/lib/ionic/js/ionic.bundle.js:22987:44
    at invokeLinkFn (https://localhost/lib/ionic/js/ionic.bundle.js:22993:9)
    at nodeLinkFn (https://localhost/lib/ionic/js/ionic.bundle.js:22392:11)
    at https://localhost/lib/ionic/js/ionic.bundle.js:22732:13
    at processQueue (https://localhost/lib/ionic/js/ionic.bundle.js:29127:28)
    at https://localhost/lib/ionic/js/ionic.bundle.js:29143:27
    at Scope.$eval (https://localhost/lib/ionic/js/ionic.bundle.js:30395:28)
    at Scope.$digest (https://localhost/lib/ionic/js/ionic.bundle.js:30211:31) <rangedisplay range="carbonData.aggrCarbon">
(anonymous) @ ionic.bundle.js:26794
ionic.bundle.js:26794 TypeError: Cannot read property 'toFixed' of undefined
    at humanize (https://localhost/js/metrics.js:1437:32)
    at link (https://localhost/js/metrics.js:1444:28)
    at https://localhost/lib/ionic/js/ionic.bundle.js:22987:44
    at invokeLinkFn (https://localhost/lib/ionic/js/ionic.bundle.js:22993:9)
    at nodeLinkFn (https://localhost/lib/ionic/js/ionic.bundle.js:22392:11)
    at https://localhost/lib/ionic/js/ionic.bundle.js:22732:13
    at processQueue (https://localhost/lib/ionic/js/ionic.bundle.js:29127:28)
    at https://localhost/lib/ionic/js/ionic.bundle.js:29143:27
    at Scope.$eval (https://localhost/lib/ionic/js/ionic.bundle.js:30395:28)
    at Scope.$digest (https://localhost/lib/ionic/js/ionic.bundle.js:30211:31) <rangedisplay range="caloriesData.aggrCalories">
```

**Comment by shankari** [comment]
Fixed (I think) by not showing the dashboard on non-MULTILABEL inputs
https://github.com/e-mission/e-mission-docs/issues/875

Please reopen if you encounter this again
