### ISSUE TITLE
Activities get deleted when the pipeline is run multiple times

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#863]
I am not sure whether this happens only for multiple runs, or also for a single run.
But the trip additions are getting deleted after some time.
@sebastianbarry can you please investigate this?

| Screenshot from last night (includes activity) | Screenshot from today morning (does not include activity) |
|-----------|-------------|
| ![Screenshot_20230310-234743](https://user-images.githubusercontent.com/2423263/224503596-0972fe30-bf83-43f1-a545-44b3334a87b1.png) | ![Screenshot_20230311-093537](https://user-images.githubusercontent.com/2423263/224503597-d993a4e0-95e6-416e-b8a8-8ed052af5f43.png) |

**Comment by sebastianbarry** [comment]
I was not able to reproduce this issue on my emulator using the following setup:

Emulator version: Google Playstore API / Google Pixel emulator
E-mission-phone: https://github.com/sebastianbarry/e-mission-phone/tree/places-survey
E-mission-server: https://github.com/sebastianbarry/e-mission-server/tree/add-composite-trip
Program version:  `{name: "Devapp Program (Tripconfirm survey + Timeuse Survey)", joinurl: "emission://join_study?label=dev-emulator-program-tripconfirm&source=github" }` (@shankari it looks like you are using a different program since you don't have the place additions, which file are you using?)

Process to reproduce issue: 
1. Load data onto the emulator (using the jul-25-2016 data)
2. Create a place addition and a trip addition on one of the trips and places
3. Run "End trip + force sync"
4. Run pipeline
5. Refresh label screen, and see that the place and trip additions both remain (original issue is not reproduced)
6. Repeat steps [3] through [5] multiple times (about 10 times and still have not reproduced issue)

**Comment by shankari** [comment]
As we discussed over Teams, this is on staging, so we can't use the devapp configs. It has to be a staging config.
And if you have set up the test phones, you will see that this is at
https://e-mission.github.io/nrel-openpath-deploy-configs/

**Comment by shankari** [comment]
The version we have on staging is:
phone: https://github.com/e-mission/e-mission-phone/tree/survey_refactor_expansion
server: https://github.com/shankari/e-mission-server/tree/add_trip_place_additions

Please test that version.

Also test the trip confirm and the trip additions at the same as I did.

**Comment by shankari** [comment]
you should also look at the logs to make sure that the trip additions actually made it to the server and were displayed from the confirmed trip when we retrieve after running the pipeline

**Comment by shankari** [comment]
Looking through the staging logs, here's where we did the matching

```
2023-03-11 01:09:20,607:DEBUG:140683376465728:handling user input
Entry({'_id': ObjectId('640bd0ee80ea0c78c23d1293'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'metadata': {'key': 'manual/trip_addition_input', 'platform': 'android', 'read_ts': 0, 'time_zone': 'America/Los_Angeles', 'type': 'message', 'write_ts': 1678409100.675, 'write_local_dt': {'year': 2023, 'month': 3, 'day': 9, 'hour': 16, 'minute': 45, 'second': 0, 'weekday': 3, 'timezone': 'America/Los_Angeles'}, 'write_fmt_time': '2023-03-09T16:45:00.675000-08:00'}, 'data': {'label': '1 Recreation/Leisure, ', 'name': 'TimeUseSurvey', 'version': 9, 'xmlResponse': '<a88RxBtE3jwSar3cwiZTdn xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" id="a88RxBtE3jwSar3cwiZTdn">\n          <start>2023-03-09T16:44:25.242-08:00</start>\n          <end>2023-03-09T16:44:25.244-08:00</end>\n          <group_hg4zz25>\n            <Date>2023-01-15</Date>\n            <Start_time>13:47:51.042-08:00</Start_time>\n            <End_time>14:05:09.054-08:00</End_time>\n            <Activity_Type>recreation_and_leisure</Activity_Type>\n            <Personal_Care_activities/>\n            <Employment_related_a_Education_activities/>\n            <Domestic_activities/>\n            <Recreation_and_leisure>spending_time_with_family_friends</Recreation_and_leisure>\n            <Voluntary_work_and_care_activities/>\n            <Other/>\n          </group_hg4zz25>\n          <meta>\n            <instanceID>uuid:7e637e35-6d50-48a9-8543-b690c8842073</instanceID>\n          </meta>\n        </a88RxBtE3jwSar3cwiZTdn>', 'jsonDocResponse': {'a88RxBtE3jwSar3cwiZTdn': {'attr': {'xmlns:jr': 'http://openrosa.org/javarosa', 'xmlns:orx': 'http://openrosa.org/xforms', 'id': 'a88RxBtE3jwSar3cwiZTdn'}, 'start': '2023-03-09T16:44:25.242-08:00', 'end': '2023-03-09T16:44:25.244-08:00', 'group_hg4zz25': {'attr': {}, 'Date': '2023-01-15', 'Start_time': '13:47:51.042-08:00', 'End_time': '14:05:09.054-08:00', 'Activity_Type': 'recreation_and_leisure', 'Personal_Care_activities': '', 'Employment_related_a_Education_activities': '', 'Domestic_activities': '', 'Recreation_and_leisure': 'spending_time_with_family_friends', 'Voluntary_work_and_care_activities': '', 'Other': ''}, 'meta': {'attr': {}, 'instanceID': 'uuid:7e637e35-6d50-48a9-8543-b690c8842073'}}}, 'start_ts': 1673819271.042, 'end_ts': 1673820309.054, 'match_id': '1c339aa0-9cfb-47b7-90b5-7d8ea5e27787', 'start_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 13, 'minute': 47, 'second': 51, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'start_fmt_time': '2023-01-15T13:47:51.042000-08:00', 'end_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 14, 'minute': 5, 'second': 9, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'end_fmt_time': '2023-01-15T14:05:09.054000-08:00'}})
for 
Entry({'_id': ObjectId('63c479e28acbfb2e2d817bed'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'metadata': {'key': 'analysis/confirmed_trip', 'platform': 'server', 'write_ts': 1673820641.9453063, 'time_zone': 'America/Los_Angeles', 'write_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 14, 'minute': 10, 'second': 41, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'write_fmt_time': '2023-01-15T14:10:41.945306-08:00'}, 'data': {'source': 'DwellSegmentationTimeFilter', 'end_ts': 1673820309.054, 'end_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 14, 'minute': 5, 'second': 9, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'end_fmt_time': '2023-01-15T14:05:09.054000-08:00', 'end_loc': {'type': 'Point', 'coordinates': [-122.0874099, 37.38724]}, 'raw_trip': ObjectId('63c479c38acbfb2e2d817bb4'), 'start_ts': 1673819271.042, 'start_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 13, 'minute': 47, 'second': 51, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'start_fmt_time': '2023-01-15T13:47:51.042000-08:00', 'start_loc': {'type': 'Point', 'coordinates': [-122.0865301, 37.3909614]}, 'duration': 1038.0119998455048, 'distance': 532.5967894770885, 'start_place': ObjectId('63b7915306818a7ecb397da4'), 'end_place': ObjectId('63c479db8acbfb2e2d817be4'), 'cleaned_trip': ObjectId('63c479d98acbfb2e2d817bbe'), 'inferred_labels': [{'labels': {'mode_confirm': 'bike', 'purpose_confirm': 'exercise'}, 'p': 0.07924464487034949}, {'labels': {'mode_confirm': 'bike', 'purpose_confirm': 'personal_med'}, 'p': 0.14397970687711387}, {'labels': {'mode_confirm': 'walk', 'purpose_confirm': 'exercise'}, 'p': 0.38729425028184894}, {'labels': {'mode_confirm': 'walk', 'purpose_confirm': 'home'}, 'p': 0.3013528748590756}, {'labels': {'mode_confirm': 'walk', 'purpose_confirm': 'library'}, 'p': 0.07812852311161218}], 'inferred_trip': ObjectId('63c479e18acbfb2e2d817be7'), 'expectation': {'to_label': True}, 'confidence_threshold': 0.55, 'expected_trip': ObjectId('63c479e18acbfb2e2d817beb'), 'user_input': {'trip_user_input': {'_id': ObjectId('640bd0ee80ea0c78c23d1292'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'metadata': {'key': 'manual/trip_user_input', 'platform': 'android', 'read_ts': 0, 'time_zone': 'America/Los_Angeles', 'type': 'message', 'write_ts': 1678409061.3, 'write_local_dt': {'year': 2023, 'month': 3, 'day': 9, 'hour': 16, 'minute': 44, 'second': 21, 'weekday': 3, 'timezone': 'America/Los_Angeles'}, 'write_fmt_time': '2023-03-09T16:44:21.300000-08:00'}, 'data': {'label': '1 purpose, 1 mode', 'name': 'TripConfirmSurvey', 'version': 1.2, 'xmlResponse': '<data xmlns:jr="http://openrosa.org/javarosa" xmlns:odk="http://www.opendatakit.org/xforms" xmlns:orx="http://openrosa.org/xforms" id="snapshot_xml">\n          <start>2023-03-09T16:42:02.127-08:00</start>\n          <end>2023-03-09T16:44:07.644-08:00</end>\n          <destination_purpose>change_mode</destination_purpose>\n          <travel_mode>walk</travel_mode>\n          <Total_people_in_trip_party>2</Total_people_in_trip_party>\n          <Non_household_member_s_on_trip>0</Non_household_member_s_on_trip>\n          <Vehicle_trip_Parking_location>1</Vehicle_trip_Parking_location>\n          <Parking_cost>0</Parking_cost>\n          <Total_toll_charges_p_uring_the_trip_AUD>0</Total_toll_charges_p_uring_the_trip_AUD>\n          <Transit_fees_AUD/>\n          <Taxi_fees/>\n          <meta>\n            <instanceID>uuid:f3a6b028-adeb-41d2-acef-aafa0dd7a679</instanceID>\n          </meta>\n        </data>', 'jsonDocResponse': {'data': {'attr': {'xmlns:jr': 'http://openrosa.org/javarosa', 'xmlns:odk': 'http://www.opendatakit.org/xforms', 'xmlns:orx': 'http://openrosa.org/xforms', 'id': 'snapshot_xml'}, 'start': '2023-03-09T16:42:02.127-08:00', 'end': '2023-03-09T16:44:07.644-08:00', 'destination_purpose': 'change_mode', 'travel_mode': 'walk', 'Total_people_in_trip_party': '2', 'Non_household_member_s_on_trip': '0', 'Vehicle_trip_Parking_location': '1', 'Parking_cost': '0', 'Total_toll_charges_p_uring_the_trip_AUD': '0', 'Transit_fees_AUD': '', 'Taxi_fees': '', 'meta': {'attr': {}, 'instanceID': 'uuid:f3a6b028-adeb-41d2-acef-aafa0dd7a679'}}}, 'start_ts': 1673819271.042, 'end_ts': 1673820309.054, 'match_id': '4c05f050-6b77-48df-99c6-ad50af29ef7b', 'start_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 13, 'minute': 47, 'second': 51, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'start_fmt_time': '2023-01-15T13:47:51.042000-08:00', 'end_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 14, 'minute': 5, 'second': 9, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'end_fmt_time': '2023-01-15T14:05:09.054000-08:00'}}}}})
```

which appeared to be correct

After we did the matching, the resulting trip has the trip addition included

```
2023-03-11 01:09:20,607:DEBUG:140683376465728:Saving entry Entry({'_id': ObjectId('63c479e28acbfb2e2d817bed'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'metadata': {'key': 'analysis/confirmed_trip', 'platform': 'server', 'write_ts': 1673820641.9453063, 'time_zone': 'America/Los_Angeles', 'write_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 14, 'minute': 10, 'second': 41, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'write_fmt_time': '2023-01-15T14:10:41.945306-08:00'}, 'data': {'source': 'DwellSegmentationTimeFilter', 'end_ts': 1673820309.054, 'end_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 14, 'minute': 5, 'second': 9, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'end_fmt_time': '2023-01-15T14:05:09.054000-08:00', 'end_loc': {'type': 'Point', 'coordinates': [-122.0874099, 37.38724]}, 'raw_trip': ObjectId('63c479c38acbfb2e2d817bb4'), 'start_ts': 1673819271.042, 'start_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 13, 'minute': 47, 'second': 51, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'start_fmt_time': '2023-01-15T13:47:51.042000-08:00', 'start_loc': {'type': 'Point', 'coordinates': [-122.0865301, 37.3909614]}, 'duration': 1038.0119998455048, 'distance': 532.5967894770885, 'start_place': ObjectId('63b7915306818a7ecb397da4'), 'end_place': ObjectId('63c479db8acbfb2e2d817be4'), 'cleaned_trip': ObjectId('63c479d98acbfb2e2d817bbe'), 
'inferred_labels': [{'labels': {'mode_confirm': 'bike', 'purpose_confirm': 'exercise'}, 'p': 0.07924464487034949}, {'labels': {'mode_confirm': 'bike', 'purpose_confirm': 'personal_med'}, 'p': 0.14397970687711387}, {'labels': {'mode_confirm': 'walk', 'purpose_confirm': 'exercise'}, 'p': 0.38729425028184894}, {'labels': {'mode_confirm': 'walk', 'purpose_confirm': 'home'}, 'p': 0.3013528748590756}, {'labels': {'mode_confirm': 'walk', 'purpose_confirm': 'library'}, 'p': 0.07812852311161218}], 'inferred_trip': ObjectId('63c479e18acbfb2e2d817be7'), 'expectation': {'to_label': True}, 'confidence_threshold': 0.55, 'expected_trip': ObjectId('63c479e18acbfb2e2d817beb'),
'user_input': {'trip_user_input': {'_id': ObjectId('640bd0ee80ea0c78c23d1292'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'metadata': {'key': 'manual/trip_user_input', 'platform': 'android', 'read_ts': 0, 'time_zone': 'America/Los_Angeles', 'type': 'message', 'write_ts': 1678409061.3, 'write_local_dt': {'year': 2023, 'month': 3, 'day': 9, 'hour': 16, 'minute': 44, 'second': 21, 'weekday': 3, 'timezone': 'America/Los_Angeles'}, 'write_fmt_time': '2023-03-09T16:44:21.300000-08:00'}, 'data': {'label': '1 purpose, 1 mode', 'name': 'TripConfirmSurvey', 'version': 1.2, 'xmlResponse': '<data xmlns:jr="http://openrosa.org/javarosa" xmlns:odk="http://www.opendatakit.org/xforms" xmlns:orx="http://openrosa.org/xforms" id="snapshot_xml">\n          <start>2023-03-09T16:42:02.127-08:00</start>\n          <end>2023-03-09T16:44:07.644-08:00</end>\n          <destination_purpose>change_mode</destination_purpose>\n          <travel_mode>walk</travel_mode>\n          <Total_people_in_trip_party>2</Total_people_in_trip_party>\n          <Non_household_member_s_on_trip>0</Non_household_member_s_on_trip>\n          <Vehicle_trip_Parking_location>1</Vehicle_trip_Parking_location>\n          <Parking_cost>0</Parking_cost>\n          <Total_toll_charges_p_uring_the_trip_AUD>0</Total_toll_charges_p_uring_the_trip_AUD>\n          <Transit_fees_AUD/>\n          <Taxi_fees/>\n          <meta>\n            <instanceID>uuid:f3a6b028-adeb-41d2-acef-aafa0dd7a679</instanceID>\n          </meta>\n        </data>', 'jsonDocResponse': {'data': {'attr': {'xmlns:jr': 'http://openrosa.org/javarosa', 'xmlns:odk': 'http://www.opendatakit.org/xforms', 'xmlns:orx': 'http://openrosa.org/xforms', 'id': 'snapshot_xml'}, 'start': '2023-03-09T16:42:02.127-08:00', 'end': '2023-03-09T16:44:07.644-08:00', 'destination_purpose': 'change_mode', 'travel_mode': 'walk', 'Total_people_in_trip_party': '2', 'Non_household_member_s_on_trip': '0', 'Vehicle_trip_Parking_location': '1', 'Parking_cost': '0', 'Total_toll_charges_p_uring_the_trip_AUD': '0', 'Transit_fees_AUD': '', 'Taxi_fees': '', 'meta': {'attr': {}, 'instanceID': 'uuid:f3a6b028-adeb-41d2-acef-aafa0dd7a679'}}}, 'start_ts': 1673819271.042, 'end_ts': 1673820309.054, 'match_id': '4c05f050-6b77-48df-99c6-ad50af29ef7b', 'start_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 13, 'minute': 47, 'second': 51, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'start_fmt_time': '2023-01-15T13:47:51.042000-08:00', 'end_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 14, 'minute': 5, 'second': 9, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'end_fmt_time': '2023-01-15T14:05:09.054000-08:00'}}},
'trip_addition': [Entry({'_id': ObjectId('640bd0ee80ea0c78c23d1293'), 'user_id': UUID('9c084ef4-2f97-4196-bd37-950c17938ec6'), 'metadata': {'key': 'manual/trip_addition_input', 'platform': 'android', 'read_ts': 0, 'time_zone': 'America/Los_Angeles', 'type': 'message', 'write_ts': 1678409100.675, 'write_local_dt': {'year': 2023, 'month': 3, 'day': 9, 'hour': 16, 'minute': 45, 'second': 0, 'weekday': 3, 'timezone': 'America/Los_Angeles'}, 'write_fmt_time': '2023-03-09T16:45:00.675000-08:00'}, 'data': {'label': '1 Recreation/Leisure, ', 'name': 'TimeUseSurvey', 'version': 9, 'xmlResponse': '<a88RxBtE3jwSar3cwiZTdn xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" id="a88RxBtE3jwSar3cwiZTdn">\n          <start>2023-03-09T16:44:25.242-08:00</start>\n          <end>2023-03-09T16:44:25.244-08:00</end>\n          <group_hg4zz25>\n            <Date>2023-01-15</Date>\n            <Start_time>13:47:51.042-08:00</Start_time>\n            <End_time>14:05:09.054-08:00</End_time>\n            <Activity_Type>recreation_and_leisure</Activity_Type>\n            <Personal_Care_activities/>\n            <Employment_related_a_Education_activities/>\n            <Domestic_activities/>\n            <Recreation_and_leisure>spending_time_with_family_friends</Recreation_and_leisure>\n            <Voluntary_work_and_care_activities/>\n            <Other/>\n          </group_hg4zz25>\n          <meta>\n            <instanceID>uuid:7e637e35-6d50-48a9-8543-b690c8842073</instanceID>\n          </meta>\n        </a88RxBtE3jwSar3cwiZTdn>', 'jsonDocResponse': {'a88RxBtE3jwSar3cwiZTdn': {'attr': {'xmlns:jr': 'http://openrosa.org/javarosa', 'xmlns:orx': 'http://openrosa.org/xforms', 'id': 'a88RxBtE3jwSar3cwiZTdn'}, 'start': '2023-03-09T16:44:25.242-08:00', 'end': '2023-03-09T16:44:25.244-08:00', 'group_hg4zz25': {'attr': {}, 'Date': '2023-01-15', 'Start_time': '13:47:51.042-08:00', 'End_time': '14:05:09.054-08:00', 'Activity_Type': 'recreation_and_leisure', 'Personal_Care_activities': '', 'Employment_related_a_Education_activities': '', 'Domestic_activities': '', 'Recreation_and_leisure': 'spending_time_with_family_friends', 'Voluntary_work_and_care_activities': '', 'Other': ''}, 'meta': {'attr': {}, 'instanceID': 'uuid:7e637e35-6d50-48a9-8543-b690c8842073'}}}, 'start_ts': 1673819271.042, 'end_ts': 1673820309.054, 'match_id': '1c339aa0-9cfb-47b7-90b5-7d8ea5e27787', 'start_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 13, 'minute': 47, 'second': 51, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'start_fmt_time': '2023-01-15T13:47:51.042000-08:00', 'end_local_dt': {'year': 2023, 'month': 1, 'day': 15, 'hour': 14, 'minute': 5, 'second': 9, 'weekday': 6, 'timezone': 'America/Los_Angeles'}, 'end_fmt_time': '2023-01-15T14:05:09.054000-08:00'}})]}}) into timeseries
```

**Comment by shankari** [comment]
Confirmed that the `trip_addition` is received on the phone

```
trip.trip_addition: Array(1)
0:
data:
end_fmt_time: "2023-03-10T16:35:44.259000-08:00"
end_local_dt: {year: 2023, month: 3, day: 10, hour: 16, minute: 35, …}
end_ts: 1678494944.259
jsonDocResponse: {a88RxBtE3jwSar3cwiZTdn: {…}}
label: "1 Domestic, "
match_id: "66233cc0-869b-4727-8195-bfb5570f278c"
name: "TimeUseSurvey"
start_fmt_time: "2023-03-10T16:29:01.706890-08:00"
start_local_dt: {year: 2023, month: 3, day: 10, hour: 16, minute: 29, …}
start_ts: 1678494541.70689
version: 9
xmlResponse: "<a88RxBtE3jwSar3cwiZTdn xmlns:jr=\"http://openrosa.org/javarosa\" xmlns:orx=\"http://openrosa.org/xforms\" id=\"a88RxBtE3jwSar3cwiZTdn\">\n          <start>2023-03-10T22:11:46.015-08:00</start>\n          <end>2023-03-10T22:11:46.017-08:00</end>\n          <group_hg4zz25>\n            <Date>2023-03-10</Date>\n            <Start_time>16:29:01.706-08:00</Start_time>\n            <End_time>16:35:44.259-08:00</End_time>\n            <Activity_Type>domestic_activities</Activity_Type>\n            <Personal_Care_activities/>\n            <Employment_related_a_Education_activities/>\n            <Domestic_activities>paying_household_bills</Domestic_activities>\n            <Recreation_and_leisure/>\n            <Voluntary_work_and_care_activities/>\n            <Other/>\n          </group_hg4zz25>\n          <meta>\n            <instanceID>uuid:b33b166d-1e9e-41ca-81fb-02fc8f44ebb9</instanceID>\n          </meta>\n        </a88RxBtE3jwSar3cwiZTdn>"
__proto__: Object
metadata: {key: "manual/trip_addition_input", platform: "android", read_ts: 0, time_zone: "America/Los_Angeles", type: "message", …}
user_id: {$uuid: "9c084ef42f974196bd37950c17938ec6"}
_id: {$oid: "640c2eba80ea0c78c23d38f4"}
```

**Comment by shankari** [comment]
what are we displaying?

```
    <ion-item class="notes-list" style="background-color: transparent">
        <ul>
            <li class="notes-list-entry" ng-repeat="entry in additionEntries | orderBy: 'data.start_ts'">
```

which is passed in

```
  .directive("enketoNotesList", function () {
    return {
      restrict: 'E',
      scope: {
        timelineEntry: '=', // the trip or place for which we are displaying notes
        additionEntries: '=', // an array of trip- or place- additionEntries to display
        timezone: '=',
      },
```

which is populated from `tripAddition`

```
            <enketo-notes-list timeline-entry="trip" addition-entries="trip.tripAddition" timezone="trip.start_local_dt.timezone"></enketo-notes-list>
```

Where do we copy from `trip_addition` to `tripAddition`?

**Comment by shankari** [comment]
We are supposed to be copying from the `trip_addition` to `tripAddition` here.
But `trip.trip_addition` is an array of entries without the `inputType2retKey` mapping for `MODE`, `PURPOSE`, etc
Not sure how this ever worked.

Let's verify this for both surveys and trip additions 

```
  enbs.populateManualInputs = function (trip, nextTrip, inputType, inputList) {
      // Check unprocessed labels first since they are more recent
      const unprocessedLabelEntry = InputMatcher.getAdditionsForTrip(trip, inputList);
      var userInputEntry = unprocessedLabelEntry;
      if (!angular.isDefined(userInputEntry)) {
          userInputEntry = trip.trip_addition[enbs.inputType2retKey(inputType)];
      }
      enbs.populateInput(trip.tripAddition, inputType, userInputEntry);
      // Logger.log("Set "+ inputType + " " + JSON.stringify(userInputEntry) + " for trip starting at " + JSON.stringify(trip.start_fmt_time));
      enbs.editingTrip = angular.undefined;
  }
```

**Comment by shankari** [comment]
Trip user input is an object with single key `trip_user_input`, 

```
trip.user_input: Object
trip_user_input:
data: {label: "1 purpose, 1 mode", name: "TripConfirmSurvey", version: 1.2, xmlResponse: "<data xmlns:jr=\"http://openrosa.org/javarosa\" xmln…f5</instanceID>\n          </meta>\n        </data>", jsonDocResponse: {…}, …}
metadata: {key: "manual/trip_user_input", platform: "android", read_ts: 0, time_zone: "America/Los_Angeles", type: "message", …}
user_id: {$uuid: "9c084ef42f974196bd37950c17938ec6"}
_id: {$oid: "640cdae080ea0c7e0184a880"}
```

For the survey:

```
inputType
"SURVEY"
etbs.inputType2retKey("SURVEY")
"trip_user_input"
trip.user_input[etbs.inputType2retKey(inputType)];
{_id: {…}, user_id: {…}, metadata: {…}, data: {…}}
```

For the trip additions, `trip.trip_addition` is a non-zero array, but 

```
unprocessedLabelEntry
[]
```

so the if statement is never true and we never use the trip additions we read from the server. I am not sure how this ever worked.

```
      if (!angular.isDefined(userInputEntry)) {
          userInputEntry = trip.trip_addition[enbs.inputType2retKey(inputType)];
      }
```

**Comment by shankari** [comment]
We now get a new error

```
while reading confirmed tripsCannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at Object.enbs.inputType2retKey (https://localhost/js/survey/enketo/enketo-add-note-button.js:196:21)
    at Object.enbs.populateManualInputs (https://localhost/js/survey/enketo/enketo-add-note-button.js:174:52)
    at Object.enbs.populateInputsAndInferences (https://localhost/js/survey/enketo/enketo-add-note-button.js:156:14)
    at https://localhost/js/diary/infinite_scroll_list.js:152:25
    at Array.forEach (<anonymous>)
    at https://localhost/js/diary/infinite_scroll_list.js:149:16
```

The implementation is

```
  enbs.inputType2retKey = function(inputType) {
    return enbs.key.split("/")[1];
  }
```

This works in the trip confirm button because we have

```
etbs.key = "manual/trip_user_input";
```

There is no such `key` in the notes button, likely because we want to reuse the button for trip and place buttons.
We also don't really want to find a particular key in the `trip_addition` field since it is a list, and not a dict.

Let's just remove that completely.

**Comment by shankari** [comment]
Yay! That works!
<img width="200" alt="Screenshot 2023-03-12 at 7 18 15 PM" src="https://user-images.githubusercontent.com/2423263/224593142-f42beeca-5695-41aa-81b8-a52d282829d4.png">

**Comment by shankari** [comment]
Committing the fix to the `survey_refactor_expansion` branch so that it is complete.

**Comment by shankari** [comment]
For the record, the new "composite trip" code does not fix this

https://github.com/e-mission/e-mission-phone/pull/919/files#diff-70c48dc732f8cbfc6d5b7a5b67911991100d21200ea91f8df5bbc6e10cba384eL173

I don't think that the approach to testing the end to end pipeline is actually working

```
enbs.populateManualInputs = function (timelineEntry, nextTimelineEntry, inputType, inputList) {
      // Check unprocessed labels first since they are more recent
      const unprocessedLabelEntry = InputMatcher.getAdditionsForTimelineEntry(timelineEntry, inputList);
      var userInputEntry = unprocessedLabelEntry;
      if (!angular.isDefined(userInputEntry)) {
          userInputEntry = timelineEntry.timelineEntry_addition[enbs.inputType2retKey(inputType)];
      }
      enbs.populateInput(timelineEntry.additions, inputType, userInputEntry);
```

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/commit/683da75ae02c3c9b20f50459d75d476c5c66cc65
