### ISSUE TITLE
🐛 Error while loading trips with a Spanish version

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#909]
The label screen generates the following error in the Spanish version

```
ERROR:while reading confirmed tripsInvalid time value
RangeError: Invalid time value
    at dh.getFormattedDateAbbr (https://localhost/js/diary/services.js:62:8)
    at $scope.populateBasicClasses (https://localhost/js/diary/infinite_scroll_list.js:468:56)
    at https://localhost/js/diary/infinite_scroll_list.js:200:20
    at Array.forEach (<anonymous>)
    at https://localhost/js/diary/infinite_scroll_list.js:189:16
```

Works fine in the english version. Investigating further...

**Comment by shankari** [comment]
I first thought that it might be due to the opts, but it is not

```
Intl.DateTimeFormat("es").format(new Date())
'21/5/2023'
Intl.DateTimeFormat("es", { weekday: 'short', month: 'short', day: 'numeric' }).format(new Date())
'dom, 21 may'
```

**Comment by shankari** [comment]
the translate service does return spanish

```
$translate.use()
'es'
```

**Comment by shankari** [comment]
Got it! It's because of the wrapped format -> parse -> format. In English `moment.format('LLL')` returns something that is parseable by Date. In Spanish, it doesn't

```
t.format("LLL")
'20 de enero de 1970 3:47'
new Date (t.format("LLL"))
Invalid Date
```

@JGreenlee remind me again why we are using this somewhat convoluted method instead of just getting the date from the timestamp directly?

**Comment by shankari** [comment]
For example, we can wrap a date around a moment directly and that seems to work

```
new Date (t)
Sat May 13 2023 18:35:37 GMT-0700 (hora de verano del Pacífico)
Intl.DateTimeFormat("es", { weekday: 'short', month: 'short', day: 'numeric' }).format(new Date(t))
'sáb, 13 may'
```

**Comment by shankari** [comment]
One line fix for this. This is not a hack but a full fix.

```
diff --git a/www/js/diary/services.js b/www/js/diary/services.js
index b9b70af5..0618cfac 100644
--- a/www/js/diary/services.js
+++ b/www/js/diary/services.js
@@ -59,7 +59,7 @@ angular.module('emission.main.diary.services', ['emission.plugin.logger',
     if (!t._isAMomentObject) t = moment(t);
     const opts = { weekday: 'short', month: 'short', day: 'numeric' };
     return Intl.DateTimeFormat($translate.use(), opts)
-      .format(new Date(t.format('LLL')));
+      .format(new Date(t));
   }

   dh.isCommon = function(id) {
```

| Before | After |
|-------|-------|
| ![Screenshot_1684696758](https://github.com/e-mission/e-mission-docs/assets/2423263/7a178e43-350f-4ed0-b908-21a6e369237c) | ![Screenshot_1684700797](https://github.com/e-mission/e-mission-docs/assets/2423263/3d10de82-c70b-4cea-8e94-553bb86ac9de) |

**Comment by shankari** [comment]
Fixed in https://github.com/e-mission/e-mission-phone/pull/983/commits/286b707cd2e5921e101f5b75a69a65751b72532c
