### ISSUE TITLE
🚸 User getting logged out multiple times and getting a connection error

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#930]
We spoke to a user today who was having issues with the app. While we were on the call, from around 2:30 to 3:00 MT, the following sequence of events occurred:
- she launched the app but got a 500 error
- she relaunched the app but got a connection error
   - she was able to access the join page and the api page from her phone
- she relaunched the app but "it went to the demographics"
- after getting through the demographics, I could see the related logs on the server, but there was no data

@JGreenlee I am missing anything?

This is clearly buggy and should be fixed.

**Comment by shankari** [comment]
First finding: The user said that they had used the same opcode every time, but it was actually different. I see three different opcodes in the logs

```
274,1686584255.436,2023-06-12T09:37:35.436000-06:00,OPCodePlugin : Force setting the prompted auth token = opcodeA
489955,1687291642.82,2023-06-20T14:07:22.820000-06:00,OPCodePlugin : Force setting the prompted auth token = opcodeB
678822,1687985889.643,2023-06-28T14:58:09.643000-06:00,OPCodePlugin : Force setting the prompted auth token = opcodeC
```

Just to clarify, `opcodeA != opcodeB != opcode C`

So that explains why there was no data after getting through the demographics

**Comment by shankari** [comment]
Second finding: In each of those cases, the stored config was empty, causing us to display the join page

```
24,1686584010.199,2023-06-12T09:33:30.199000-06:00,"js : Config not downloaded, need to show join screen"
50,1686584074.431,2023-06-12T09:34:34.431000-06:00,"js : UI_CONFIG: Stored dynamic config successfully, result = ""OK"""
274,1686584255.436,2023-06-12T09:37:35.436000-06:00,OPCodePlugin : Force setting the prompted auth token = opcodeA

346916,1686847332.802,2023-06-15T10:42:12.802000-06:00,"js : Config not downloaded, need to show join screen"
489617,1687291395.862,2023-06-20T14:03:15.862000-06:00,"js : Config not downloaded, need to show join screen"
489899,1687291619.463,2023-06-20T14:06:59.463000-06:00,"js : UI_CONFIG: Stored dynamic config successfully, result = ""OK"""
489955,1687291642.82,2023-06-20T14:07:22.820000-06:00,OPCodePlugin : Force setting the prompted auth token = opcodeB

678686,1687985785.512,2023-06-28T14:56:25.512000-06:00,"js : Config not downloaded, need to show join screen"
678731,1687985815.905,2023-06-28T14:56:55.905000-06:00,"js : UI_CONFIG: Stored dynamic config successfully, result = ""OK"""
678822,1687985889.643,2023-06-28T14:58:09.643000-06:00,OPCodePlugin : Force setting the prompted auth token = opcodeC
```

**Comment by shankari** [comment]
ok... so it looks like the UI config is deleted periodically after being stored successfully. I can think of two reasons for this:
1. the app is deleting files periodically: apparently Samsung is known to do this - 
   a. https://www.36mobiles.com/mobile/auto-delete-unnecessary-data-samsung
   b. https://r2.community.samsung.com/t5/Galaxy-M/Files-getting-automatically-deleted/td-p/6212635
   c. https://r2.community.samsung.com/t5/Tech-Talk/How-to-turn-off-auto-delete-unnecessary-files/td-p/9470453
I think that this is less likely because clearly the delete process didn't delete the loggerDB (otherwise we won't have any logs to show this behavior). But I guess it could have happened that the delete process deleted the usercache and not the loggerDB

2. The SQLite query commands are returning blank results for some subset of the queries. Is this intermittent or persistent?
Is it all queries or some queries?

**Comment by JGreenlee** [comment]
This user frequently tried to re-scan their QRCode(s), didn't they? Can we find logs for how many times they tried to re-scan, and if any of those were unsuccessful?

I am thinking when you re-scan, it downloads a new config.
But if network is spotty / temporarily unavailable, the config might fail to download. What would happen in that case?

**Comment by shankari** [comment]
They had 3 separate opcodes and downloaded the config correctly every time.
And the connection failures were not because network was spotty; it was because the SQLite query for the connection config was returning blank, so we were trying to connect to the "localhost equivalent" (10.0.2.2) which, of course, failed

Stay tuned for additional details...

**Comment by shankari** [comment]
Digging deeper into (2)

> The SQLite query commands are returning blank results for some subset of the queries. Is this intermittent or persistent?
Is it all queries or some queries?

It looks like it is some queries and intermittent.

Concretely, the reason for the connection failures is that the connection config wasn't read properly, so it defaults to 10.0.2.2

```
678243,1687985328.225,2023-06-28T14:48:48.225000-06:00,ConnectionSettings : getConfigFromFile: configFilePath = null returning
678244,1687985328.227,2023-06-28T14:48:48.227000-06:00,"ConnectionSettings : in getConnectURL, connectionSettings = {""connectUrl"":""http:\/\/10.0.2.2:8080"",""android"":{""auth"":{""method"":""dummy-dev""}}}"
678245,1687985328.228,2023-06-28T14:48:48.228000-06:00,"ConnectionSettings : in getConnectURL, returning http://10.0.2.2:8080"
```

But just before that, we did read the config properly

```
678222,1687985327.078,2023-06-28T14:48:47.078000-06:00,"js : in readConfig, read_val = {""version"":1,"....
678223,1687985327.259,2023-06-28T14:48:47.259000-06:00,"js : Config downloaded, skipping join screen"
```

and some other configuration files as well

```
678224,1687985327.26,2023-06-28T14:48:47.260000-06:00,"js : in readIntroDone, read_val = ""2023-06-20T14:08:03-06:00"""
678225,1687985327.275,2023-06-28T14:48:47.275000-06:00,"js : in isIntroDone, returning true"
678227,1687985327.414,2023-06-28T14:48:47.414000-06:00,"js : uc_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""} ls_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""}"
678228,1687985327.434,2023-06-28T14:48:47.434000-06:00,"js : local and native values match, already synced"
678230,1687985327.484,2023-06-28T14:48:47.484000-06:00,"js : uc_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""} ls_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""}"
678231,1687985327.489,2023-06-28T14:48:47.489000-06:00,"js : local and native values match, already synced"
678232,1687985327.512,2023-06-28T14:48:47.512000-06:00,BuiltinUserCache : Args =  type = 'local-storage' AND key = 'referral_navigation'
678233,1687985327.515,2023-06-28T14:48:47.515000-06:00,"BuiltinUserCache : in removeLocalStorage, deleted 0 document entries"
678234,1687985327.521,2023-06-28T14:48:47.521000-06:00,js : uc_stored_val = null ls_stored_val = null
678235,1687985327.561,2023-06-28T14:48:47.561000-06:00,"js : local and native values match, already synced"
678236,1687985327.57,2023-06-28T14:48:47.570000-06:00,js : changing state to [object Object]
678238,1687985327.623,2023-06-28T14:48:47.623000-06:00,"js : uc_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""} ls_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""}"
678239,1687985327.786,2023-06-28T14:48:47.786000-06:00,"js : local and native values match, already synced"
678240,1687985327.852,2023-06-28T14:48:47.852000-06:00,"js : About to update profile with settings = {""phone_lang"":""en"",""curr_platform"":""android"",""manufacturer"":""samsung"",""client_os_version"":""12"",""client_app_version"":""1.3.3""}"
```

**Comment by shankari** [comment]
Ok so this is pretty weird. We clearly had the settings defined here

```
678144,1687985172.213,2023-06-28T14:46:12.213000-06:00,"ConnectionSettings : in getSettings, connectionSettings = {""connectUrl"":""https:\/\/denver-casr-openpath.nrel.gov\/api\/"",""aggregate_call_auth"":""user_only""}"
678145,1687985172.228,2023-06-28T14:46:12.228000-06:00,"ConnectionSettings : in getConnectURL, connectionSettings = {""connectUrl"":""https:\/\/denver-casr-openpath.nrel.gov\/api\/"",""aggregate_call_auth"":""user_only""}"
678146,1687985172.231,2023-06-28T14:46:12.231000-06:00,"ConnectionSettings : in getConnectURL, returning https://denver-casr-openpath.nrel.gov/api/"
```

Then we got a bunch of null data, along with a 503 error.

```
678147,1687985172.26,2023-06-28T14:46:12.260000-06:00,js : uc_stored_val = null ls_stored_val = null
678148,1687985172.262,2023-06-28T14:46:12.262000-06:00,"js : local and native values match, already synced"
678149,1687985172.271,2023-06-28T14:46:12.271000-06:00,js : uc_stored_val = null ls_stored_val = null
678150,1687985172.273,2023-06-28T14:46:12.273000-06:00,"js : local and native values match, already synced"
678151,1687985172.438,2023-06-28T14:46:12.438000-06:00,CommunicationHelper : Got response org.apache.http.message.BasicHttpResponse@e9d2618 with status HTTP/1.1 500 Internal Server Error
678152,1687985172.441,2023-06-28T14:46:12.441000-06:00,class gov.nrel.cims.openpath.R : Failed to get JSON object
```

Checking the server, the 503 error is because there was no `user` field. So the login was apparently deleted...

```
Traceback (most recent call last):
  File "/usr/src/app/emission/net/api/bottle.py", line 997, in _handle
    out = route.call(**args)
  File "/usr/src/app/emission/net/api/bottle.py", line 1998, in wrapper
    rv = callback(*a, **ka)
  File "/usr/src/app/emission/net/api/cfc_webapp.py", line 173, in getPipelineState
    user_uuid = getUUID(request)
  File "/usr/src/app/emission/net/api/cfc_webapp.py", line 474, in getUUID
    retUUID = enaa.getUUID(request, auth_method, inHeader)
  File "/usr/src/app/emission/net/auth/auth.py", line 58, in getUUID
    userToken = __getToken__(request, inHeader)
  File "/usr/src/app/emission/net/auth/auth.py", line 52, in __getToken__
    userToken = request.json['user']
KeyError: 'user'
```

Then `intro_done` is read successfully

```
678173,1687985197.154,2023-06-28T14:46:37.154000-06:00,"js : uc_stored_val = {""intro_done"":""2023-06-20T14:08:03-06:00""} ls_stored_val = {""intro_done"":""2023-06-20T14:08:03-06:00""}"
678174,1687985197.158,2023-06-28T14:46:37.158000-06:00,"js : local and native values match, already synced"
```

The config is read successfully, the required consent version is read successfully

```
678175,1687985197.161,2023-06-28T14:46:37.161000-06:00,"js : in readConfig, read_val 
678176,1687985197.172,2023-06-28T14:46:37.172000-06:00,"js : Config downloaded, skipping join screen"
678180,1687985197.214,2023-06-28T14:46:37.214000-06:00,"js : uc_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""} ls_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""}"
```

Tried to delete the `OP_GEOFENCE_CFG`, but did not delete anything

```
678209,1687985326.877,2023-06-28T14:48:46.877000-06:00,BuiltinUserCache : Args =  type = 'local-storage' AND key = 'OP_GEOFENCE_CFG'
678210,1687985326.891,2023-06-28T14:48:46.891000-06:00,"BuiltinUserCache : in removeLocalStorage, deleted 0 document entries"
```

Then we still have some stored values

```
678222,1687985327.078,2023-06-28T14:48:47.078000-06:00,"js : in readConfig, 
678223,1687985327.259,2023-06-28T14:48:47.259000-06:00,"js : Config downloaded, skipping join screen"
678227,1687985327.414,2023-06-28T14:48:47.414000-06:00,"js : uc_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""} ls_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""}"
678230,1687985327.484,2023-06-28T14:48:47.484000-06:00,"js : uc_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""} ls_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""}"
678234,1687985327.521,2023-06-28T14:48:47.521000-06:00,js : uc_stored_val = null ls_stored_val = null
```

But then we don't find any saved connection settings (although nothing has really happened between these two)

```
678242,1687985328.225,2023-06-28T14:48:48.225000-06:00,ConnectionSettings : configFilePath = null
678243,1687985328.225,2023-06-28T14:48:48.225000-06:00,ConnectionSettings : getConfigFromFile: configFilePath = null returning 
678244,1687985328.227,2023-06-28T14:48:48.227000-06:00,"ConnectionSettings : in getConnectURL, connectionSettings = {""connectUrl"":""http:\/\/10.0.2.2:8080"",""android"":{""auth"":{""method"":""dummy-dev""}}}"
678245,1687985328.228,2023-06-28T14:48:48.228000-06:00,"ConnectionSettings : in getConnectURL, returning http://10.0.2.2:8080"
```

And we only go into the `configFilePath` code stream if `getConfigFromDB` is null

```
            sharedInstance.connectionSettings = getConfigFromDB(ctxt);
            // Can comment out later once all existing installs have been updated
            // See https://github.com/e-mission/cordova-connection-settings/issues/9#issuecomment-325081511
            if (sharedInstance.connectionSettings == null) {
                InputStream configFileStream = getConfigFileStream(ctxt);
                Log.i(ctxt, TAG, "configFilePath = "+configFileStream);
                sharedInstance.connectionSettings = getConfigFromFile(ctxt, configFileStream);
            }
```

But we don't see any exceptions so it is not DB corruption or anything - the DB is just returning a NULL value

```
    private static JSONObject getConfigFromDB(Context ctxt) {
        try {
            JSONObject retVal = UserCacheFactory.getUserCache(ctxt).getLocalStorage(CONNECTION_SETTINGS_KEY, false);
            // We know that this is an object and not an array
            // so we don't need to handle any other use case
            // we catch generic JSONObjects as well anyway
            return retVal;
        } catch (JSONException e) {
            Log.e(ctxt, TAG, "Got exception while retrieving connection settings");
            Log.exception(ctxt, TAG, e);
            return null;
        }
    }
```

**Comment by shankari** [comment]
ok so the local storage implementation is

```
    public JSONObject getLocalStorage(String key, boolean withMetadata) throws JSONException {
        JSONArray wrappedArray = wrapJson(getValuesForInterval(key, LOCAL_STORAGE_TYPE, getAllTimeQuery(cachedCtx), withMetadata), withMetadata);
        if (wrappedArray.length() == 0) {
            return null;
        } else {
            return wrappedArray.getJSONObject(0);
        }
    }
```

I wonder if the time query is messed up somehow so `getAllTimeQuery` is missing this particular entry.
Will add additional logging to this function as well to see if we can figure out what is going on.

**Comment by shankari** [comment]
So far, we have seen three missing objects:
- connection config: stored as local storage
- dynamic config: stored as RWDocument
- opcode: stored as local storage

So there's no pattern in the type of storage.

And here's the implementation of `getAllTimeQuery`. I don't see how this can fail for later queries after succeeding for earlier ones. `System.currentTimeMillis()` should be strictly larger for later queries.

```
    public static UserCache.TimeQuery getAllTimeQuery(Context cachedContext) throws JSONException {
        UserCache.TimeQuery tq = new UserCache.TimeQuery(cachedContext.getString(R.string.metadata_usercache_write_ts),
                0, System.currentTimeMillis());
        return tq;
    }
```

**Comment by shankari** [comment]
Picking this up again:

Right around this set of failures, we do detect that the usercache value is null and copy over from local to usercache.
But we only:
- do this for the usercache (would have excluded dynamic config)
- do this for access through javascript (would have excluded connection settings and opcode in the native path)

```
677177,1687984965.367,2023-06-28T14:42:45.367000-06:00,"js : uc_stored_val = null ls_stored_val = {""intro_done"":""2023-06-20T14:08:03-06:00""} copying local intro_done to native..."
677185,1687984965.482,2023-06-28T14:42:45.482000-06:00,"js : uc_stored_val = null ls_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""} copying local data_collection_consented_protocol to native..."
677340,1687984979.971,2023-06-28T14:42:59.971000-06:00,"js : uc_stored_val = null ls_stored_val = {""carbon_dataset_locale"":""US""} copying local carbon_dataset_locale to native..."
677353,1687984980.034,2023-06-28T14:43:00.034000-06:00,"js : uc_stored_val = null ls_stored_val = {""foodCompare"":""cookie""} copying local foodCompare to native..."
```

**Comment by shankari** [comment]
so my proposed fix is:
- change all of this to be stored as local storage
- ideally, I would copy from javascript storage to usercache local storage in native code as well
  - however, native storage doesn't have access to javascript storage
  - so for now, I will probably just iterate over all localstorage entries in javascript and make sure that they match
- add client stats to this so that we can more easily figure out how often it is happening, and on which phone make/model etc

note that we need to add backward compat code to copy over the dynamic config from RW config to local storage as well. Argh!!

I think that is it at a high level; will add other changes that I find while implementing!

**Comment by JGreenlee** [comment]
Note that once we have a fully native app and are not running in a webview, there will no longer be `localstorage`.

We could switch everything to `localstorage` now, but we'd have to switch again to something else in the coming months.
That is a big part of why I was exploring other key-value storage options that support both web and native environments.

**Comment by shankari** [comment]
I looked at it again to make sure that aren't deleting anything by mistake.

We have the opcode while reading the token:

```
676713,1687984832.601,2023-06-28T14:40:32.601000-06:00,"ConnectionSettings : in getConnectURL, returning https://denver-casr-openpath.nrel.gov/api/"
676714,1687984832.603,2023-06-28T14:40:32.603000-06:00,"PromptedAuth : Auth found in local storage, now it should be stable"
676715,1687984832.838,2023-06-28T14:40:32.838000-06:00,CommunicationHelper : Got response org.apache.http.message.BasicHttpResponse@cb2e862 with status HTTP/1.1 200 OK
```

Then we copy over the loggerDB preparatory to emailing it (which presumably uses a bunch of space)

```
676717,1687984833.002,2023-06-28T14:40:33.002000-06:00,js : uc_stored_val = null ls_stored_val = null
676718,1687984833.006,2023-06-28T14:40:33.006000-06:00,"js : local and native values match, already synced"
676719,1687984833.008,2023-06-28T14:40:33.008000-06:00,js : uc_stored_val = null ls_stored_val = null
676720,1687984833.01,2023-06-28T14:40:33.010000-06:00,"js : local and native values match, already synced"
676721,1687984837.147,2023-06-28T14:40:37.147000-06:00,js : About to get email config
676722,1687984837.322,2023-06-28T14:40:37.322000-06:00,"js : default emailConfigString = {""address"":""shankari@eecs.berkeley.edu""}"
676723,1687984837.374,2023-06-28T14:40:37.374000-06:00,js : Going to email loggerDB
676724,1687984851.815,2023-06-28T14:40:51.815000-06:00,"js : email app closed while sending, {""to"":[""shankari@eecs.berkeley.edu""],""attachments"":[""app://databases/loggerDB""],""subject"":""emission logs"",""body"":""please fill in what is wrong"",""isHtml"":false,""app"":""mailto:"",""from"":"""",""chooserHeader"":""Open with"",""cc"":[],""bcc"":[]} not sure if we should do anything"
```

And we do try to delete `OP_GEOFENCE_CFG` but they 

```
677165,1687984965.281,2023-06-28T14:42:45.281000-06:00,BuiltinUserCache : Args =  type = 'local-storage' AND key = 'OP_GEOFENCE_CFG'
677166,1687984965.283,2023-06-28T14:42:45.283000-06:00,"BuiltinUserCache : in removeLocalStorage, deleted 0 document entries"
```

and then its gone

```
677176,1687984965.359,2023-06-28T14:42:45.359000-06:00,"js : uc_stored_val = null ls_stored_val = {""intro_done"":""2023-06-20T14:08:03-06:00""}"
677177,1687984965.367,2023-06-28T14:42:45.367000-06:00,"js : uc_stored_val = null ls_stored_val = {""intro_done"":""2023-06-20T14:08:03-06:00""} copying local intro_done to native..."
```

**Comment by shankari** [comment]
> Note that once we have a fully native app and are not running in a webview, there will no longer be localstorage.

Once we have a fully native app and are not running in a webview, will we even have this issue? If this is memory/storage related; the memory footprint of a fully native app will be very different from that of a hybrid app anyway.

I am also trying to add additional logging to figure out what is going on. It would be terrible if this would also affect actual sensed data instead of config information.

Depending on what data is being lost, we can also duplicate the data in other locations - two database files, for example, or one DB and one file.

And by that time, maybe we will have the resources to do better reliability testing - artificially lower memory, artificially fill up the disk....

**Comment by shankari** [comment]
And the interesting thing is that although the missing localstorage was all 

```
677177,1687984965.367,2023-06-28T14:42:45.367000-06:00,"js : uc_stored_val = null ls_stored_val = {""intro_done"":""2023-06-20T14:08:03-06:00""} copying local intro_done to native..."
677185,1687984965.482,2023-06-28T14:42:45.482000-06:00,"js : uc_stored_val = null ls_stored_val = {""protocol_id"":""2014-04-6267"",""approval_date"":""2016-07-14""} copying local data_collection_consented_protocol to native..."
677340,1687984979.971,2023-06-28T14:42:59.971000-06:00,"js : uc_stored_val = null ls_stored_val = {""carbon_dataset_locale"":""US""} copying local carbon_dataset_locale to native..."
677353,1687984980.034,2023-06-28T14:43:00.034000-06:00,"js : uc_stored_val = null ls_stored_val = {""foodCompare"":""cookie""} copying local foodCompare to native..."
```

we had way more missing readConfig

```
$ grep "in readConfig, read_val = {}" /tmp/loggerDB.casr_missing_data.withdate.log
23,1686584010.194,2023-06-12T09:33:30.194000-06:00,"js : in readConfig, read_val = {}"
346915,1686847332.8,2023-06-15T10:42:12.800000-06:00,"js : in readConfig, read_val = {}"
489616,1687291395.86,2023-06-20T14:03:15.860000-06:00,"js : in readConfig, read_val = {}"
489751,1687291494.982,2023-06-20T14:04:54.982000-06:00,"js : in readConfig, read_val = {}"
678685,1687985785.51,2023-06-28T14:56:25.510000-06:00,"js : in readConfig, read_val = {}"
```

**Comment by shankari** [comment]
While looking at the code, I do see that we also have

```
    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int oldVersion, int newVersion) {
        sqLiteDatabase.execSQL("DROP TABLE IF EXISTS " + TABLE_USER_CACHE);
        onCreate(sqLiteDatabase);
    }
```

which drops everything without any logging!

I don't think that was the case here, since the localstorage values were available after the dynamicConfig was blank and the dynamicConfig was available after the localstorage was blank. But might want to change that to a NOP and at least log it.

**Comment by shankari** [comment]
We also have a function that lists all the existing keys in the database. Will call that on every launch as well, just to make sure that we understand what is available and what is not.

**Comment by shankari** [comment]
@JGreenlee wrt local storage, all is not lost 😄 
https://stackoverflow.com/questions/62115591/local-storage-react-native

**Comment by shankari** [comment]
Fixed with all the related PRs being merged.
Deployed as NREL OpenPATH version 1.3.7
