### ISSUE TITLE
Error creating confirmed trips

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#939]
```
2023-08-05 22:27:55,950:DEBUG:140639316731712:no last confirmed place found, created place with id 64cecceba9d94240d18fa94e
2023-08-05 22:27:56,793:ERROR:140639316731712:Error while creating confirmed objects, timestamp is unchanged
Traceback (most recent call last):
File "/usr/src/app/emission/analysis/userinput/matcher.py", line 94, in create_confirmed_objects
confirmed_tl = create_and_link_timeline(ts, timeline, last_confirmed_place)
File "/usr/src/app/emission/analysis/userinput/matcher.py", line 140, in create_and_link_timeline
assert matching_confirmed_trip is not None,\
AssertionError: no matching confirmed trip for cleaned trip curr_confirmed_start_place.data.ending_trip=ObjectId('64b8e82f77dac51cabd54514')
```

The simple fix is probably to just reset the pipeline, but first let us see what happened.

**Comment by shankari** [comment]
ok, so I can verify that the related cleaned trip does not exist

```
>>> edb.get_analysis_timeseries_db().find_one({"_id": boi.ObjectId("64b8e82f77dac51cabd54514")})
>>> 
```

**Comment by shankari** [comment]
Here is the related cleaned place

```
{'_id': ObjectId('64b8e84377dac51cabd5457a'),
'metadata': {'key': 'analysis/cleaned_place',
'write_fmt_time': '2023-07-20T00:54:43.176901-07:00'},
'raw_places': [ObjectId('64b8e7ec77dac51cabd54506'), ObjectId('64b8419f5be711c44514e8bd')],
'ending_trip': ObjectId('64b8e82f77dac51cabd54514'), 'starting_trip': ObjectId('64b8e83477dac51cabd54529')}}
```

From the logs, when we read all trips and places, we get two places that seem to overlap (start at the same time, but end at different times.

```
2023-08-05 22:27:50,883:DEBUG:140639316731712:Considering place 64b8e84377dac51cabd5457b: t1  -> t2
2023-08-05 22:27:50,884:DEBUG:140639316731712:Considering place 64b8e84377dac51cabd5457a: t1 -> t3
```

And right after that, we have a couple of places with the same pattern, and with a similar but not identical `exit_ts`
Let's see what happened when these trips were created

```
2023-08-05 22:27:50,884:DEBUG:140639316731712:Considering place 64b8e84377dac51cabd5457c: t4 -> ~ t2
2023-08-05 22:27:50,885:DEBUG:140639316731712:Considering place 64b8e84677dac51cabd5457e: t4 -> t5
```

**Comment by shankari** [comment]
There's a pretty big gap between

```
2023-07-19 20:04:05,158:DEBUG:140679282300736:Raw place is 64b8419f5be711c44514e8bd and corresponding location is 64b83de861091632ee1b5c01

2023-07-19 20:04:25,013:DEBUG:140679282300736:retrieved object Entry({'_id': ObjectId('64b841b85be711c44514e92c')}) and added to id_map




2023-07-20 07:53:16,409:DEBUG:140117980165952:last place doc = {'_id': ObjectId('64b8419f5be711c44514e8bd'),
'metadata': {'key': 'segmentation/raw_place',
'write_fmt_time': '2023-07-19T13:03:43.076344-07:00'}}
```

**Comment by shankari** [comment]
Just to confirm

```
>>> for cp in all_cleaned_places:
...     if "64b8419f5be711c44514e8bd" in [str(i) for i in cp["data"]["raw_places"]]:
...             print(cp["_id"])
...
64b8e84377dac51cabd5457a
64b841b55be711c44514e920
```

But there are no more any composite places

```
>>> all_confirmed_places = list(edb.get_analysis_timeseries_db().find({"metadata.key": "analysis/confirmed_place"}))
>>> for cp in all_confirmed_places:
...     if "64b8419f5be711c44514e8bd" in [str(i) for i in cp["data"]["raw_places"]]:
...             print(cp["_id"])
...
64b841b85be711c44514e92c
```

And that confirmed place is around as well

So why did we include this in a new cleaned place during a subsequent run?

**Comment by shankari** [comment]
During the second run, this had only an ending trip and was the last place doc
```
2023-07-20 07:53:16,409:DEBUG:140117980165952:last place doc = {'_id': ObjectId('64b8419f5be711c44514e8bd'), 'metadata': {'key': 'segmentation/raw_place', 
'ending_trip': ObjectId('64b8419f5be711c44514e8bc')
```

then we created the other raw place as the end place for a new trip.

```
2023-07-20 07:53:16,926:DEBUG:140117980165952:Inserting entry Entry({'_id': ObjectId('64b8e7ec77dac51cabd54505'), 'metadata': Metadata({'key': 'segmentation/raw_trip',
'start_place': ObjectId('64b8419f5be711c44514e8bd'),
 'end_place': ObjectId('64b8e7ec77dac51cabd54506'),
```

**Comment by shankari** [comment]
ok, so it looks like there were in fact two threads running in parallel

```
2023-07-20 07:53:17,500:DEBUG:140117980165952:Saving entry Entry({'_id': ObjectId('64b8e7ec77dac51cabd54506'), 'metadata': Metadata({'key': 'segmentation/raw_place', 'enter_fmt_time': '24.999360-06:00', 'exit_fmt_time': '06.958944-06:00',

2023-07-20 07:53:17,643:DEBUG:140399344711488:Saving entry Entry({'_id': ObjectId('64b8e7ec717e30447d3a1911'), 'metadata': Metadata({'key': 'segmentation/raw_place', 'enter_fmt_time': '24.999360-06:00', 'exit_fmt_time': '06.958944-06:00'
```

That raises two questions:
1. why didn't our `curr_run_ts`mechanism work? I am guessing it is because we don't use an atomic test-and-set operation. But we don't use an atomic operation because we launch the pipeline only periodically. So two threads should not really attempt to access the same resource at the same time. Instead, we guard against long-running operations.
   - note that maybe we should make it atomic because even if the threads are launched at different times, depending on the ordering of the users in the two threads and the time taken to execute tasks for one user, we might happen to check the timestamp at the same time.
1. why did we have two launches of the task at essentially the same time?

**Comment by shankari** [comment]
Confirmed that both threads were launched at almost the same time

```
2023-07-20 07:53:11,261:INFO:140117980165952:**********UUID ...: segmenting into trips**********
2023-07-20 07:53:11,264:INFO:140399344711488:**********UUID ...: segmenting into trips**********
```

And are in different task logs.

```
openpath/analysis-cron-intake/7901761edcfa4944852d6d85ee9cc730
openpath/analysis-cron-intake/06eac48e2c014e2587c0ed872d5a7221
```

So what happened in each task before the trip segmentation?

**Comment by shankari** [comment]
```
2023-07-20 07:53:11,261:INFO:140117980165952:**********UUID 7578fe6a-e3dc-4a41-88a4-a226dbe1060d: segmenting into trips**********
2023-07-20 07:53:11,263:INFO:140117980165952:For stage PipelineStages.TRIP_SEGMENTATION, start_ts = 2023-07-19T19:47:33.168318
2023-07-20 07:53:11,263:DEBUG:140117980165952:About to save object PipelineState({'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.263149, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785})
2023-07-20 07:53:11,270:DEBUG:140117980165952:After saving state PipelineState({'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.263149, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785}),
list is [{'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.263149, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785},
```

In the other thread

```
2023-07-20 07:53:11,264:INFO:140399344711488:**********UUID 7578fe6a-e3dc-4a41-88a4-a226dbe1060d: segmenting into trips**********
2023-07-20 07:53:11,266:INFO:140399344711488:For stage PipelineStages.TRIP_SEGMENTATION, start_ts = 2023-07-19T19:47:33.168318
2023-07-20 07:53:11,266:DEBUG:140399344711488:About to save object PipelineState({'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.2662766, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785})
2023-07-20 07:53:11,271:DEBUG:140399344711488:After saving state PipelineState({'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.2662766, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785}),
list is [{'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.2662766, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785}]
```

Aha! with interleaving, we get

```diff
- Thread1: 2023-07-20 07:53:11,261:INFO:140117980165952:**********UUID 7578fe6a-e3dc-4a41-88a4-a226dbe1060d: segmenting into trips**********
+ Thread2: 2023-07-20 07:53:11,264:INFO:140399344711488:**********UUID 7578fe6a-e3dc-4a41-88a4-a226dbe1060d: segmenting into trips**********
- Thread1: 2023-07-20 07:53:11,263:INFO:140117980165952:For stage PipelineStages.TRIP_SEGMENTATION, start_ts = 2023-07-19T19:47:33.168318
- Thread1: 2023-07-20 07:53:11,263:DEBUG:140117980165952:About to save object PipelineState({'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.263149, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785})
+ Thread2: 2023-07-20 07:53:11,266:INFO:140399344711488:For stage PipelineStages.TRIP_SEGMENTATION, start_ts = 2023-07-19T19:47:33.168318
+ Thread2: 2023-07-20 07:53:11,266:DEBUG:140399344711488:About to save object PipelineState({'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.2662766, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785})
- Thread1: 2023-07-20 07:53:11,270:DEBUG:140117980165952:After saving state PipelineState({'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.263149, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785}), list is [{'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.263149, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785},
+ Thread2: 2023-07-20 07:53:11,271:DEBUG:140399344711488:After saving state PipelineState({'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.2662766, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785}), list is [{'_id': ObjectId('6482630302413e9c36b01569'), 'pipeline_stage': 1, 'curr_run_ts': 1689839586.2662766, 'last_processed_ts': 1689796053.168318, 'last_ts_run': 1689797014.5692785}]
```

Yup! Classic TEST-AND-SET error, we have a race between the "About to save" from thread1 and the start_ts check from thread2.

Now, let's see when the threads started and how we ended up with being so close.

**Comment by shankari** [comment]
It is fairly clear that the issue is related to the atomic read/write. Even if it turns out to be an error that these were scheduled so close together, it may happen again by random chance; if one thread is running while the next task starts. I believe that is not supposed to happen (two scheduled tasks running in parallel), but can happen with cronjobs or other less sophisticated scheduling mechanisms.

There is no fix for the existing data except resetting the pipeline so let's go ahead with that in parallel with our ongoing investigation. Resetting to `2023-07-19` to be on the safe side.

**Comment by shankari** [comment]
For the record, they were launched at almost the exact same time. Need to check with ops on why that might happen:


[openpath/analysis-cron-intake/06eac48e2c014e2587c0ed872d5a7221](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/openpath-prod-ccebikes-analysis-intake/log-events/openpath$252Fanalysis-cron-intake$252F06eac48e2c014e2587c0ed872d5a7221)

```
2023-07-19T22:23:36.685-07:00 | Found configuration, overriding...
2023-07-19T22:23:36.692-07:00 | Live reload disabled,
2023-07-19T22:23:36.692-07:00 | Activating the environment...
2023-07-19T22:23:36.962-07:00 | Run intake multiprocess..
```

[openpath/analysis-cron-intake/7901761edcfa4944852d6d85ee9cc730](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/openpath-prod-ccebikes-analysis-intake/log-events/openpath$252Fanalysis-cron-intake$252F7901761edcfa4944852d6d85ee9cc730)

```
2023-07-19T23:23:38.825-07:00 | Found configuration, overriding...
2023-07-19T23:23:38.853-07:00 | Live reload disabled,
2023-07-19T23:23:38.853-07:00 | Activating the environment...
2023-07-19T23:23:39.402-07:00 | Run intake multiprocess..
```

**Comment by shankari** [comment]
All servers were down as of `7/19 8:31 PM`
Ops restarted several of them manually. I wonder if this is related
@jgu2 I thought we were ensuring that only one intake process was running at a time?
